### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory THUDM/chatglm-6b

### ISSUE THREAD

**Issue by davedat** [THUDM/ChatGLM-6B#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行 python web_demo.py 时
提示：“OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory THUDM/chatglm-6b” 是啥情况，
已从huggingface上下载模型文件，还是提示该错误。

(venv) u20@DESKTOP-R2NTTVV:/mnt/e/gpt/ChatGLM-6B-main$ python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
  File "/mnt/e/gpt/ChatGLM-6B-main/venv/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/e/gpt/ChatGLM-6B-main/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2274, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory THUDM/chatglm-6b.

### Steps To Reproduce

python web_demo.py

### Environment

```markdown
- OS:win10 wsl ubuntu20.04
- Python:3.8.10
- Transformers:4.27.1
- PyTorch:2.0.1+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by LiAI-tech** [comment]
这个因该对照https://huggingface.co/THUDM/chatglm-6b/tree/main 这里，因该[pytorch_model.bin.index.json](https://huggingface.co/THUDM/chatglm-6b/blob/main/pytorch_model.bin.index.json)这个文件有问题，重新下载即可
