### ISSUE TITLE
No such file or directory: '/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/configuration_chatglm.py'[BUG/Help] <title>

### ISSUE THREAD

**Issue by hexiaojin1314** [THUDM/ChatGLM-6B#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sh ds_train_finetune.sh
然后出现了这个报错，实际configuration_chatglm.py文件是存在

### Steps To Reproduce

sh ds_train_finetune.sh

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by briup1** [comment]
我也报这个错误

**Comment by briup1** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/modules/transformers_modules/configuration_chatglm.py'
[WARNING|tokenization_auto.py:653] 2023-05-15 08:40:40,074 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[WARNING|tokenization_auto.py:653] 2023-05-15 08:40:40,080 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "main.py", line 431, in <module>
    main()
  File "main.py", line 112, in main
    tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path, trust_remote_code=True)
  File "/zhangfei401/346/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 664, in from_pretrained
    pretrained_model_name_or_path, module_file + ".py", class_name, **kwargs
  File "/zhangfei401/346/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 397, in get_class_from_dynamic_module
    local_files_only=local_files_only,
  File "/zhangfei401/346/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/zhangfei401/346/lib/python3.7/site-packages/transformers/dynamic_module_utils.py", line 140, in check_imports
    "This modeling file requires the following packages that were not found in your environment: "
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`

**Comment by robotsp** [comment]
I had the same issue, dun one solution

**Comment by hexiaojin1314** [comment]
应该是环境问题，我换了个performance版本就不报这个错误了

**Comment by briup1** [comment]
@hexiaojin1314  兄弟 能贡献下你的requirements.txt吗

**Comment by NoHateAnymore** [comment]
transformers==4.28.1
我用requirement.txt的版本会报这个错，用4.28.1修复了

**Comment by roki1031** [comment]
> 应该是环境问题，我换了个performance版本就不报这个错误了

啥performance版本

**Comment by claire199705** [comment]
> 

大佬，更新transformers确实可以了，请教下是什么问题导致的，怎么修复的？

**Comment by claire199705** [comment]
@NoHateAnymore 大佬，更新transformers确实可以了，请教下是什么问题导致的以及怎么修复的？在更新之前做了个实验在每个rank加上延时 也可以解决，是多rank同时读取同一个文件导致的错误吗？

**Comment by Huffman-cotdom** [comment]
> 

请问每个rank加上延迟是怎么操作？

**Comment by Huffman-cotdom** [comment]
> @NoHateAnymore 大佬，更新transformers确实可以了，请教下是什么问题导致的以及怎么修复的？在更新之前做了个实验在每个rank加上延时 也可以解决，是多rank同时读取同一个文件导致的错误吗？

请问怎么在每个rank加上延迟？

**Comment by LYCnight** [comment]
兄弟们，破案了，是transformer版本问题。
我的是27.01版本，清华的（截止到2023.8.17）是30.0
解决方法：
pip install -r requirement.txt

**Comment by LYCnight** [comment]
> > @NoHateAnymore 大佬，更新transformers确实可以了，请教下是什么问题导致的以及怎么修复的？在更新之前做了个实验在每个rank加上延时 也可以解决，是多rank同时读取同一个文件导致的错误吗？
> 
> 请问怎么在每个rank加上延迟？

可以看看我的解决方法
