### ISSUE TITLE
[BUG/Help] AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by Helmsman-Lab** [THUDM/ChatGLM-6B#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-b213e1f4de9c3694/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 9446.63it/s]
Extracting data files:   0%|                                                                                                                               | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/work/chatGlm-6B/ChatGLM-6B/ptuning/main.py", line 431, in <module>
    main()
  File "/home/work/chatGlm-6B/ChatGLM-6B/ptuning/main.py", line 100, in main
    raw_datasets = load_dataset(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/builder.py", line 890, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/builder.py", line 963, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/packaged_modules/json/json.py", line 49, in _split_generators
    data_files = dl_manager.download_and_extract(self.config.data_files)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/download/download_manager.py", line 564, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/download/download_manager.py", line 536, in extract
    extracted_paths = map_nested(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 443, in map_nested
    mapped = [
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 444, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 363, in _single_map_nested
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 363, in <listcomp>
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 346, in _single_map_nested
    return function(data_struct)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 212, in cached_path
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 43, in extract
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 318, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 86, in is_extractable
    return tarfile.is_tarfile(path)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2517, in is_tarfile
    t = open(name)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1761, in xzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1682, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1542, in __init__
    self.firstmember = self.next()
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2377, in next
    raise e
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2350, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1122, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/local/python3/lib/python3.10/lzma.py", line 204, in read
    return self._buffer.read(size)
  File "/usr/local/python3/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/python3/lib/python3.10/_compression.py", line 96, in read
    if self._decompressor.needs_input:
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### Steps To Reproduce

Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-b213e1f4de9c3694/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 9446.63it/s]
Extracting data files:   0%|                                                                                                                               | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/work/chatGlm-6B/ChatGLM-6B/ptuning/main.py", line 431, in <module>
    main()
  File "/home/work/chatGlm-6B/ChatGLM-6B/ptuning/main.py", line 100, in main
    raw_datasets = load_dataset(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/builder.py", line 890, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/builder.py", line 963, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/packaged_modules/json/json.py", line 49, in _split_generators
    data_files = dl_manager.download_and_extract(self.config.data_files)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/download/download_manager.py", line 564, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/download/download_manager.py", line 536, in extract
    extracted_paths = map_nested(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 443, in map_nested
    mapped = [
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 444, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 363, in _single_map_nested
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 363, in <listcomp>
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 346, in _single_map_nested
    return function(data_struct)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 212, in cached_path
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 43, in extract
    extractor_format = self.extractor.infer_extractor_format(input_path)
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 318, in infer_extractor_format
    if extractor.is_extractable(path, magic_number=magic_number):
  File "/usr/local/python3/lib/python3.10/site-packages/datasets/utils/extract.py", line 86, in is_extractable
    return tarfile.is_tarfile(path)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2517, in is_tarfile
    t = open(name)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1761, in xzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1682, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1542, in __init__
    self.firstmember = self.next()
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2377, in next
    raise e
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 2350, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/python3/lib/python3.10/tarfile.py", line 1122, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/local/python3/lib/python3.10/lzma.py", line 204, in read
    return self._buffer.read(size)
  File "/usr/local/python3/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/python3/lib/python3.10/_compression.py", line 96, in read
    if self._decompressor.needs_input:
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### Environment

```markdown
- OS: linux
- Python:3.10.10
- Transformers:4.27.1
- PyTorch:1.12.1+cu113
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by Helmsman-Lab** [comment]
python调整成3.9版本
