### ISSUE TITLE
[BUG/Help] <微调后加载模型报错，求教>

### ISSUE THREAD

**Issue by MrWuzy1994** [THUDM/ChatGLM-6B#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

求教，微调之后按照
`
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /home/xixixi/chatglm-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/xixixi/ChatGLM-6B/cli_demo.py", line 19, in <module>
    model.transformer.prefix_encoder.load_state_dict(prefix_state_dict)
  File "/home/xixixi/miniconda3/envs/chatglm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
	Missing key(s) in state_dict: "embedding.weight".
	Unexpected key(s) in state_dict: "transformer.prefix_encoder.embedding.weight".
`

代码如下
`
import os
import platform
import signal
from transformers import AutoConfig, AutoModel, AutoTokenizer
import readline
import torch

config = AutoConfig.from_pretrained("/home/xixixi/chatglm-6b-int4", trust_remote_code=True, pre_seq_len=128)

tokenizer = AutoTokenizer.from_pretrained("/home/xixixi/chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("/home/xixixi/chatglm-6b-int4",config=config, trust_remote_code=True)
prefix_state_dict = torch.load(os.path.join("/home/xixixi/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-500", "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(prefix_state_dict)

model = model.half().cuda()
model.transformer.prefix_encoder.float()
model = model.eval()

`

尝试用  模型部署  第二种方式，发现不能正常推理

求教

### Expected Behavior

微调以后加载模型失败

### Steps To Reproduce

微调设置步长500

### Environment

```markdown
- OS:
- Python:3.10.6
- Transformers:4.29.1
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by MrWuzy1994** [comment]
model.transformer.prefix_encoder.load_state_dict(prefix_state_dict)

**Comment by MrWuzy1994** [comment]
model.transformer.prefix_encoder.load_state_dict(prefix_state_dict) fix to  new_prefix_state_dict
