### ISSUE TITLE
在输入聊天内容时报错Not a string

### ISSUE THREAD

**Issue by IceWind233** [THUDM/ChatGLM-6B#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在租赁服务上部署该模型，在输入内容时报错

### Steps To Reproduce

在输入中文时 当在输入法输入 “zhongwen·” 带有符号或因某种原因输入时在非意愿情况下产生空格时 报错如下 

```
Traceback (most recent call last):
  File "cli_demo.py", line 24, in <module>
    response, history = model.chat(tokenizer, query, history=history)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/220f772e9a2d7a55701d9b49bf2efc618acc3b56/modeling_chatglm.py", line 1107, in chat
    input_ids = tokenizer([prompt], return_tensors="pt", padding=True)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2523, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2609, in _call_one
    return self.batch_encode_plus(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2800, in batch_encode_plus
    return self._batch_encode_plus(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 733, in _batch_encode_plus
    first_ids = get_input_ids(ids)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 700, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 547, in tokenize
    tokenized_text.extend(self._tokenize(token))
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/220f772e9a2d7a55701d9b49bf2efc618acc3b56/tokenization_chatglm.py", line 255, in _tokenize
    seq = self.sp_tokenizer.tokenize(text)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/220f772e9a2d7a55701d9b49bf2efc618acc3b56/tokenization_chatglm.py", line 154, in tokenize
    tokens = self._get_text_tokenizer(encode_special_tokens=special_tokens).tokenize(text)
  File "/root/miniconda3/lib/python3.8/site-packages/icetk/text_tokenizer.py", line 49, in tokenize
    return self.sp.EncodeAsPieces(text)
  File "/root/miniconda3/lib/python3.8/site-packages/sentencepiece/__init__.py", line 545, in EncodeAsPieces
    return self.Encode(input=input, out_type=str, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/sentencepiece/__init__.py", line 531, in Encode
    return self._EncodeAsPieces(input, enable_sampling, nbest_size,
  File "/root/miniconda3/lib/python3.8/site-packages/sentencepiece/__init__.py", line 316, in _EncodeAsPieces
    return _sentencepiece.SentencePieceProcessor__EncodeAsPieces(self, text, enable_sampling, nbest_size, alpha, add_bos, add_eos, reverse, emit_unk_piece)
TypeError: not a string 
```

### Environment

```markdown
- OS: Ubuntu20.04
- Python: 3.8
- CUDA Support: `True`
```

**Comment by jerrylususu** [comment]
如果用的是 JupyterLab 的 terminal，可能会因为和中文输入法不兼容出现问题。如果提前在其他文本框（如记事本或浏览器地址栏）内将文本输入完成，然后再复制到 terminal，就不会再出现这种问题

**Comment by IceWind233** [comment]
@jerrylususu ok 好的
