### ISSUE TITLE
[Help] 一般的回答有么？不要流式的

### ISSUE THREAD

**Issue by ucas010** [THUDM/ChatGLM-6B#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/THUDM/ChatGLM-6B/blob/main/cli_demo.py#L43
这个位置能不能改一下，chat，我改成chat后报错了。

### Steps To Reproduce

        for response, history in model.stream_chat(tokenizer, query, history=history):
改成：
        for response, history in model.chat(tokenizer, query, history=history):
报错了：python cli_demo.py 
```
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：介绍下北京
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "ChatGLM-6B/bin/cli_demo.py", line 58, in <module>
    main()
  File "/ChatGLM-6B/bin/cli_demo.py", line 43, in main
    for response, history in model.chat(tokenizer, query, history=history):
ValueError: too many values to unpack (expected 2)
```

### Environment

```markdown
- OS:CentOs 7.9
- Python:3.9.16
transformers        4.28.1
lion-pytorch        0.0.7
open-clip-torch     2.20.0
pytorch-ignite      0.4.12
torch               1.12.1+cu116
torchaudio          0.12.1+cu116
torchvision         0.13.1+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

no

**Comment by cillinzhang** [comment]
```
DEV = torch.device('cuda:0')
input_ids = tokenizer(query, return_tensors="pt").input_ids.to(DEV)
generation_config = {
    'max_new_tokens': 200,
    'do_sample': False,
    'num_beams': 8,
    'early_stopping': True,
}
outputs = model.generate(input_ids, **generation_config)
rets = tokenizer.batch_decode(outputs, skip_special_tokens=True)
```
用generate即可，请参考
