### ISSUE TITLE
[Help] 如何像stable diffusion一样只要启动第一次后续就不需要联网

### ISSUE THREAD

**Issue by 4Lijk** [THUDM/ChatGLM-6B#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**第一次打开web_demo.py正常运行后我使用控制面板把网络禁用进入断网状态，但是在这状态下再次打开web_demo.py脚本后出现以下**
C:\Users\open>E:\1\chatglm-6b\web_demo1232.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000029E1492B520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/THUDM/chatglm-6b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029E1492B520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\1\chatglm-6b\web_demo1232.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", cache_dir="E:/1/2", trust_remote_code=True)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 286, in get_cached_module_file
    commit_hash = model_info(pretrained_model_name_or_path, revision=revision, token=use_auth_token).sha
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\hf_api.py", line 1623, in model_info
    r = requests.get(path, headers=headers, timeout=timeout, params=params)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\open\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/THUDM/chatglm-6b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029E1492B520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
**试过这个方法**
![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/890ea194-3a7c-41e1-b338-2932b21aa65c)
**但是它提示找不到config.json这个文件，我在huggingface下载的完整文件**
![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/da491c3f-d2ff-43a2-8e78-ec8620b95356)

### Steps To Reproduce

**正常运行过一遍之后关闭（模型，分词器都下载完毕可正常使用状态）。把网络禁用或拔掉网线后再次运行相同脚本即可复现**

### Environment

```markdown
- OS:win10
- Python:.3.10
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

希望有弄过的大佬发表一下自己解决的方法或是能实现相同效果的方法供以学习

**Comment by codeAndxv** [comment]
尝试设置本地模型路径。就像readme里面的从本地加载模型

**Comment by 4Lijk** [comment]
> 尝试设置本地模型路径。就像readme里面的从本地加载模型

![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/b925be7b-528e-46d7-8a53-430e871a757d)

这里的代码指的是webui.py里的还是图中clone地址的尾部

**Comment by 4Lijk** [comment]
> 尝试设置本地模型路径。就像readme里面的从本地加载模型

我尝试在py脚本里添加，提示一些类似：OSError:[WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\open\\.cache\\huggingface\\modules\\transformers_modules\\E:'这样的错误。我把c盘huggingface默认路径改到e盘了，然后下载了模型又复制模型地址填到webui.py的tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
里，发现提示一些符号问题

**Comment by 4Lijk** [comment]
> 尝试设置本地模型路径。就像readme里面的从本地加载模型

我试一下

**Comment by 4Lijk** [comment]
> 尝试设置本地模型路径。就像readme里面的从本地加载模型

加载量化的模型也能照这个弄吗，还是需要其他方法

**Comment by 4Lijk** [comment]
> 尝试设置本地模型路径。就像readme里面的从本地加载模型

 按照readme里的方法出现下面错误，已将模型文件下载到e盘
![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/4855e370-9a42-4934-9ac1-99d59d00b717)


![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/7f79d89d-5782-47d6-af5a-abd81c76ec51)
    
![image](https://github.com/THUDM/ChatGLM-6B/assets/130196233/51d6a07f-e5e5-4ce1-ab8b-71cb4c35a2bb)
