### ISSUE TITLE
[BUG/Help] <title> WARNING - transformers_modules.chatglm-6b-v1_1.quantization - Failed to load cpm_kernels:No module named 'cpm_kernels'

### ISSUE THREAD

**Issue by HelixPark** [THUDM/ChatGLM-6B#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[INFO|modeling_utils.py:2690] 2023-06-01 15:32:57,469 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
06/01/2023 15:32:57 - WARNING - transformers_modules.chatglm-6b-v1_1.quantization - Failed to load cpm_kernels:No module named 'cpm_kernels'
Traceback (most recent call last):
  File "/home/llm/chatglm/ChatGLM-6B/ptuning/main.py", line 430, in <module>
    main()
  File "/home/llm/chatglm/ChatGLM-6B/ptuning/main.py", line 128, in main
    model = model.quantize(model_args.quantization_bit)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/modeling_chatglm.py", line 1434, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 157, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 76, in compress_int4_weight
    blockDim = (min(round_up(m, 32), 1024), 1, 1)
NameError: name 'round_up' is not defined

### Steps To Reproduce

 WARNING - transformers_modules.chatglm-6b-v1_1.quantization - Failed to load cpm_kernels:No module named 'cpm_kernels'
Traceback (most recent call last):
  File "/home/llm/chatglm/ChatGLM-6B/ptuning/main.py", line 430, in <module>
    main()
  File "/home/llm/chatglm/ChatGLM-6B/ptuning/main.py", line 128, in main
    model = model.quantize(model_args.quantization_bit)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/modeling_chatglm.py", line 1434, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 157, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-v1_1/quantization.py", line 76, in compress_int4_weight
    blockDim = (min(round_up(m, 32), 1024), 1, 1)
NameError: name 'round_up' is not defined
(chatglm) [root@491996 ptuning]# 

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by ZJY96** [comment]
pip install cpm_kernels

**Comment by lionheart-007** [comment]
安装后运行仍然报错：UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
