### ISSUE TITLE
[Help] OSError: Unable to load weights from pytorch checkpoint file for 'THUDM/chatglm-6b-int4/pytorch_model.bin' at 'THUDM/chatglm-6b-int4/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by Ikaros-521** [THUDM/ChatGLM-6B#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
2023-06-12 14:19:17.449429: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 14:19:18.230788: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "/root/miniconda3/envs/chatglm/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ChatGLM-6B/web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).half().cuda()
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2429, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'THUDM/chatglm-6b-int4/pytorch_model.bin' at 'THUDM/chatglm-6b-int4/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

```
![image](https://github.com/THUDM/ChatGLM-6B/assets/40910637/fd140d1c-8f17-4697-9284-61c49dd7d800)

torch降到了1.12.0，依然同样的问题
![image](https://github.com/THUDM/ChatGLM-6B/assets/40910637/c383c0ea-fb35-414b-a252-a5e6ea02afd0)

### Steps To Reproduce

AWS服务器 c5.2xlarge（Deep Learning AMI Habana PyTorch 1.12.0 SynapseAI 1.6.0 (Ubuntu 20.04) 20220928）
搭建miniconda，创建py3.10环境
安装requirement和gradio。
clone模型
`python web_demo.py`

### Environment

```markdown
- OS: AWS服务器 c5.2xlarge（Deep Learning AMI Habana PyTorch 1.12.0 SynapseAI 1.6.0 (Ubuntu 20.04) 20220928）
- Python:3.10
- Transformers:4.27.1
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

**Comment by Ikaros-521** [comment]
设置后`from_tf=True`
```
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
2023-06-12 15:20:02.776035: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 15:20:03.554781: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 4
Using quantization cache
Applying quantization to glm layers
Traceback (most recent call last):
  File "/root/ChatGLM-6B/test.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True, from_tf=True).half().cuda()
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2612, in from_pretrained
    model, loading_info = load_tf2_checkpoint_in_pytorch_model(
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/modeling_tf_pytorch_utils.py", line 407, in load_tf2_checkpoint_in_pytorch_model
    tf_model_class = getattr(transformers, tf_model_class_name)
  File "/root/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1119, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute TFChatGLMForConditionalGeneration

```

**Comment by mqttqz** [comment]
same to me

**Comment by windlu-1** [comment]
我也这个问题，你解决了吗

**Comment by Ikaros-521** [comment]
> 我也这个问题，你解决了吗

并没有

**Comment by Ikaros-521** [comment]
> > > 我也这个问题，你解决了吗
> > 
> > 并没有
> 
> 我是部署在服务器上的，在运行api.py时加载模型只能运加载一个.bin文件，后面就报了和您同样的错误

autodl的服务器有镜像 随便跑☺️

**Comment by Ikaros-521** [comment]
> > 
> 
> 
> 
> > 
> 
> 但我只是想加载一下这个模型，调用一下api，autodl也行嘛

autodl当然可以0.0

**Comment by windlu-1** [comment]
> 



> > > 
> > 
> > 
> > > 
> > 
> > 
> > 但我只是想加载一下这个模型，调用一下api，autodl也行嘛
> 
> autodl当然可以0.0

意思是我不用filezilla上传到autodl了是吗，

**Comment by SamuelZhu12** [comment]
请问有解决办法吗？chatglm2-6b-int4一样的问题

**Comment by Ikaros-521** [comment]
> 请问有解决办法吗？chatglm2-6b-int4一样的问题

很显然 没有0.0

**Comment by Gou-dan-Li** [comment]
给预训练模型删了重下就行了

**Comment by Ikaros-521** [comment]
> 给预训练模型删了重下就行了

感谢 下次有机会试试
