### ISSUE TITLE
[BUG/Help] <title>RuntimeError: Function 'AddmmBackward0' returned nan values in its 2th output.

### ISSUE THREAD

**Issue by PhilrainV** [THUDM/ChatGLM-6B#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我将glm加载到一个之前使用bert的框架中，在step1的output中可以正常输出，但是step2的output就全是nan了。

Traceback (most recent call last):
  File "D:\Project\CSCL\paper_test\Main_structure\src\main.py", line 62, in <module>
    solver.train_and_eval()
  File "D:\Project\CSCL\paper_test\Main_structure\src\solver.py", line 289, in train_and_eval
    train_loss = train(model, optimizer_main, criterion, 1)
  File "D:\Project\CSCL\paper_test\Main_structure\src\solver.py", line 193, in train
    loss.backward()
  File "D:\CODE_env\Anaconda\anaconda3\envs\torch-B\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "D:\CODE_env\Anaconda\anaconda3\envs\torch-B\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'AddmmBackward0' returned nan values in its 2th output.

### Steps To Reproduce

`    def __init__(self, hp):
        super(LanguageEmbeddingLayer, self).__init__()
#之前使用的bert
        # bertconfig = BertConfig.from_pretrained('bert-base-uncased', output_hidden_states=True)
        # self.bertmodel = BertModel.from_pretrained('bert-base-uncased', config=bertconfig)
        self.bertmodel = AutoModel.from_pretrained("glm-6b-int4", trust_remote_code=True).half().cuda()
    def forward(self, sentences, bert_sent, bert_sent_mask):
        bert_output = self.bertmodel(input_ids=bert_sent, attention_mask=bert_sent_mask)
        bert_output = bert_output[0]
        print(bert_output)
        #全是nan
        return bert_output   # return head (sequence representation)`

### Environment

```markdown
- OS:windows10
- Python:3.9
- Transformers:4.27.1
- PyTorch:1.13.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zhangch9** [comment]
方便提供一下能复现这个错误的代码和数据吗？给个简单的例子就可以。
