### ISSUE TITLE
[Help] RuntimeError: CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by sunkechenjing** [THUDM/ChatGLM-6B#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Video card: GEFORCE GTX TITAN X
Video memory: 12G,
Memory: 32G
CPU: coreI5

I Can perform Q&A normally in CPU mode, but the response speed is slow.
Python - c "import torch; print (torch. cuda. is_available()) test passed
But in GPU mode, quantifying int8 for inference and reporting errors are as follows: Please help to identify possible causes.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "M:\chatglm\chatglm-6B\web_demo.py", line 71, in predict
    for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\quantization.py", line 147, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\quantization.py", line 51, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm-6b\quantization.py", line 104, in extract_weight_to_half
    func(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in __call__
    func = self._prepare_func()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\kernels\base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\kernels\base.py", line 24, in get_module
    self._module[curr_device] = cuda.cuModuleLoadData(self._code)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\library\base.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\library\cuda.py", line 233, in cuModuleLoadData
    checkCUStatus(cuda.cuModuleLoadData(ctypes.byref(module), data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\library\cuda.py", line 216, in checkCUStatus
    raise RuntimeError("CUDA Error: %s" % cuGetErrorString(error))
RuntimeError: CUDA Error: no kernel image is available for execution on the device

### Expected Behavior

Using GPU for Q&A to improve running speed

### Steps To Reproduce

cuda  torch
grad
python web_demo

### Environment

```markdown
- OS:windows10
- Python:3.8.7
- Transformers:4.30.2
- PyTorch:1.12.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

 thanks

**Comment by dwq370** [comment]
同问，在推理时执行到model.quantize报错了

**Comment by ShengfanXu** [comment]
> GEFORCE GTX TITAN X

GeForce系列GPU貌似并不直接支持原生的INT4或INT8量化计算，在GeForce RTX 20系往后有第三方软件尝试实现INT4或8量化。所以你这可能是GPU不支持INT4或INT8量化的原因，可以在训练的时候不使用 quantization_bit 参数，这将默认使用 FP16 ，且训练时间和显存要求会明显增加。另外，专业级GPU Tesla P100也不支持INT4或8量化。

**Comment by saubcy** [comment]
> > GEFORCE GTX TITAN X
> 
> GeForce系列GPU貌似并不直接支持原生的INT4或INT8量化计算，在GeForce RTX 20系往后有第三方软件尝试实现INT4或8量化。所以你这可能是GPU不支持INT4或INT8量化的原因，可以在训练的时候不使用 quantization_bit 参数，这将默认使用 FP16 ，且训练时间和显存要求会明显增加。另外，专业级GPU Tesla P100也不支持INT4或8量化。

在Jetson Orin NX上也是一样的报错，请问一下也是类似的原因么，看官方文档似乎说是支持量化
