### ISSUE TITLE
[BUG/Help]变更本地模型目录后运行出现异常-No module named 'transformers_modules.‘

### ISSUE THREAD

**Issue by jasonpro22** [THUDM/ChatGLM-6B#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

原来运行正常，但移动模型目录后运行后出错，则显示：

`Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "R:\Project\OpenSource\ChatGLM-6B_UI\web_demo.py", line 8, in <module>
    tokenizer = AutoTokenizer.from_pretrained("./model1/chatglm-6b", trust_remote_code=True)
  File "C:\Users\Asus_Admin\.conda\envs\conda_pypthon39\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "C:\Users\Asus_Admin\.conda\envs\conda_pypthon39\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\Asus_Admin\.conda\envs\conda_pypthon39\lib\site-packages\transformers\dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\Asus_Admin\.conda\envs\conda_pypthon39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'`

### Expected Behavior

e

### Steps To Reproduce

没有变更目录前运行正常，但更换目录后异常。 
将C:\Users\xxx\.cache\huggingface\hub\models--THUDM--chatglm-6b\snapshots\220f772e9a2d7a55701d9b49bf2efc618acc3b56的模型文件
复制到项目目录下，新建的model目录里。

ChatGLM-6B
          |_______model
    

并在代码中修改目录。

`tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(8).cuda()`

变更为：
`tokenizer = AutoTokenizer.from_pretrained("./model", trust_remote_code=True)
model = AutoModel.from_pretrained("./model", trust_remote_code=True).half().quantize(8).cuda()`

### Environment

```markdown
- OS:windows10
- Python:3.9.16
- Transformers:4.27.1
- PyTorch:1.13.1+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

no

**Comment by Mingxia1** [comment]
装4.26.1的transformers就行了

**Comment by reeingal** [comment]
> 装4.26.1的transformers就行了

Thank you~. You are right.

**Comment by liukaixuan1994** [comment]
我用的就是4.26.1的transformers，一样不行，不过报错显示的是：
[chatglm-6b p tuning V2 error: raise AttributeError({} object has no attribute {}.format( AttributeError: ChatGLMForConditionalGeneration object has no attribute enable_input_require_grads](https://www.google.com.hk/search?newwindow=1&biw=1863&bih=961&q=chatglm-6b+p+tuning+V2+error:+raise+AttributeError(%7B%7D+object+has+no+attribute+%7B%7D.format(%0AAttributeError:+ChatGLMForConditionalGeneration+object+has+no+attribute+enable_input_require_grads&sa=X&ved=2ahUKEwi39fKU7av-AhUxgP0HHYGGCOwQgwN6BAgJEAE)

**Comment by dongxuxucool** [comment]
一样的， 请问怎么解决的这个问题?
