### ISSUE TITLE
从本地加载模型报错；一个是加入sys.path.append()之后 一个是之前

### ISSUE THREAD

**Issue by askxiaozhang** [THUDM/ChatGLM-6B#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

要运行的代码
from transformers import AutoTokenizer,AutoModel
import sys
import os
sys.path.append("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/trainingep1_supervised_finetuningatglm-6b")
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
tokenizer = AutoTokenizer.from_pretrained("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/training/step1_supervised_finetuning/chatglm-6b",trust_remote_code=True)
model = AutoModel.from_pretrained("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/training/step1_supervised_finetuning/chatglm-6b",trust_remote_code=True).half().cuda()
model = model.eval()
response,history = model.chat(tokenizer,"你好",history=[])
print(response)

### Steps To Reproduce

报错1：
Traceback (most recent call last):
  File "/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/trainingep1_supervised_finetuning/main-Copy1.py", line 8, in <module>
    model = AutoModel.from_pretrained("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/training/step1_supervised_finetuning/chatglm-6b",trust_remote_code=True).half().cuda()
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 480, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformersnamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformersnamic_module_utils.py", line 165, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.chatglm-6b.modeling_chatglm' has no attribute 'ChatGLMMode'

报错2：
Traceback (most recent call last):
  File "/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/web_demo.py", line 14, in <module>
    model = AutoModel.from_pretrained("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/training/step1_supervised_finetuning/chatglm-6b", trust_remote_code=True).half().cuda()
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 480, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformersnamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformersnamic_module_utils.py", line 268, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/zhangchang/.conda/envsatdeepb/python3.9/site-packages/transformersnamic_module_utils.py", line 151, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### Environment

```markdown
和官方文档要求的一致；transofomers是最新版本
```

**Comment by zhangch9** [comment]
```python
sys.path.append("/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/trainingep1_supervised_finetuningatglm-6b")
sys.path.append(
os.path.abspath(os.path.join(os.path.dirname(file), os.path.pardir)))
```

sys.path 这两句去掉能运行吗？

**Comment by askxiaozhang** [comment]
> 

问题已经解决了。我是在修改本地模型中各个py文件和json文件中的THUMD的路径，修改为本地路径;然后根据config.json里面的配置，有个auto_map 查看AutoModelForSeq2SeqLM，把model=AutoModel.from_pretrained()改为model=AutoModelForSeq2SeqLM.from_pretrained()
就可以加载模型进行Chat了
