### ISSUE TITLE
[BUG/Help] <title>AttributeError: 'ChatGLMModel' object has no attribute 'chat'

### ISSUE THREAD

**Issue by askxiaozhang** [THUDM/ChatGLM-6B#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在调用本地模型进行部署对话时，报错ChatGLMModel.has no attribute chat，如果路径设为THUMD/，则不会报错

### Steps To Reproduce

Traceback (most recent call last):
  File "/home/zhangchang/DeepSpeed-Chat-ChatGLM-main/main.py", line 23, in <module>
    r,h = model.chat(tokenizer,'hello',history=[])
  File "/home/zhangchang/.conda/envs/chatdeep/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'chat'

### Environment

```markdown
和文档环境一致
```

**Comment by askxiaozhang** [comment]
已解决：修改本地模型中各个py文件和json文件中的THUMD的路径，修改为本地路径
