### ISSUE TITLE
 assert vocab_file is not None

### ISSUE THREAD

**Issue by zhanghui-china** [THUDM/ChatGLM-6B#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

python web_demo.py

### Expected Behavior

success running

### Steps To Reproduce

python web_demo.py
![image](https://github.com/THUDM/ChatGLM-6B/assets/63148804/b81bf30f-4f7f-4f3b-9bb5-acb0e40e2ada)

`(torch1.11) PS D:\ChatGLM-6B> python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("./THUDM/chatglm-6b", trust_remote_code=True)
  File "L:\Anaconda\envs\torch1.11\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 658, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "L:\Anaconda\envs\torch1.11\lib\site-packages\transformers\tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "L:\Anaconda\envs\torch1.11\lib\site-packages\transformers\tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\xishu/.cache\huggingface\modules\transformers_modules\local\tokenization_chatglm.py", line 221, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "C:\Users\xishu/.cache\huggingface\modules\transformers_modules\local\tokenization_chatglm.py", line 58, in __init__
    assert vocab_file is not None
AssertionError`

### Environment

```markdown
- OS:Windows 11
- Python:3.8 conda
- Transformers:4.26.1
- PyTorch:1.11
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by Gaozizhong** [comment]
应该是缺文件了，我缺了ice_text.model，可以去huggingface对一下
