### ISSUE TITLE
[BUG/Help] <title>ptuning 出现这种异常该如何处理

### ISSUE THREAD

**Issue by brianzhangrong** [THUDM/ChatGLM-6B#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "main.py", line 431, in <module>
    main()
  File "main.py", line 249, in main
    train_dataset = train_dataset.map(
  File "/usr/local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/usr/local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/usr/local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "main.py", line 220, in preprocess_function_train
    context_length = input_ids.index(tokenizer.bos_token_id)
ValueError: None is not in list

### Steps To Reproduce

1.bash train.sh

### Environment

```markdown
- OS:centos
- Python:3.8
- Transformers: 4.27.1
- PyTorch:2.1.2
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by HarryFunn** [comment]
你好，我也碰到了ValueError: None is not in list的报错，请问你解决了吗，谢谢！

**Comment by amauryjulien** [comment]
hello, how does this issue go on? I also met this bug.

**Comment by celestial-micha** [comment]
大家可以看一下这两个帖子：
https://github.com/THUDM/ChatGLM2-6B/issues/54
https://huggingface.co/THUDM/chatglm2-6b/discussions/20

我在实践中，也是用chatglm1的代码，然后跑ptuning出了这个问题，不知道根本原因在哪里，希望大家看完这个帖子后如果有新思路，@我一下
