### ISSUE TITLE
python3 cli_demo.py

### ISSUE THREAD

**Issue by yazong** [THUDM/ChatGLM-6B#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

到下述这里进行不下去了，谢谢。

[root@VM-0-7-centos ChatGLM-6B-main]# python3 cli_demo.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/keysyms/__init__.py", line 15, in <module>
    from .keysyms import *
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/keysyms/keysyms.py", line 13, in <module>
    from ctypes import windll
ImportError: cannot import name 'windll' from 'ctypes' (/usr/local/lib/python3.10/ctypes/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/console/__init__.py", line 14, in <module>
    from .console import *
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/console/console.py", line 28, in <module>
    from pyreadline3.keysyms import KeyPress, make_KeyPress
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/keysyms/__init__.py", line 17, in <module>
    raise ImportError(
ImportError: Could not import keysym for local python version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/ChatGLM-6B-main/cli_demo.py", line 5, in <module>
    import readline
  File "/usr/local/lib/python3.10/site-packages/readline.py", line 7, in <module>
    from pyreadline3.rlmain import Readline
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/__init__.py", line 14, in <module>
    from . import (
  File "/usr/local/lib/python3.10/site-packages/pyreadline3/console/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Could not find a console implementation for local python version

### Expected Behavior

同上述内容

### Steps To Reproduce

[root@VM-0-7-centos ChatGLM-6B-main]# ll
total 152
-rw-r--r-- 1 root root  1865 Jun 27 12:05 api.py
-rw-r--r-- 1 root root  2082 Jul  9 00:11 cli_demo.py
-rw-r--r-- 1 root root  1986 Jun 27 12:05 cli_demo_vision.py
drwxr-xr-x 2 root root  4096 Jun 27 12:05 examples
-rw-r--r-- 1 root root   940 Jun 27 12:05 FAQ.md
drwxr-xr-x 2 root root  4096 Jun 27 12:05 improve
-rw-r--r-- 1 root root 11336 Jun 27 12:05 LICENSE
drwxr-xr-x 2 root root  4096 Jun 27 12:05 limitations
-rw-r--r-- 1 root root  4267 Jun 27 12:05 MODEL_LICENSE
-rw-r--r-- 1 root root  4612 Jun 27 12:05 PROJECT.md
drwxr-xr-x 2 root root  4096 Jun 27 12:05 ptuning
-rw-r--r-- 1 root root 24263 Jun 27 12:05 README_en.md
-rw-r--r-- 1 root root 26277 Jun 27 12:05 README.md
-rw-r--r-- 1 root root    96 Jun 27 12:05 requirements.txt
drwxr-xr-x 2 root root  4096 Jun 27 12:05 resources
-rw-r--r-- 1 root root  6402 Jun 27 12:05 UPDATE.md
-rw-r--r-- 1 root root  2030 Jun 27 12:05 utils.py
-rw-r--r-- 1 root root  2191 Jun 27 12:05 web_demo2.py
-rw-r--r-- 1 root root  2010 Jun 27 12:05 web_demo_old.py
-rw-r--r-- 1 root root  3637 Jun 27 12:05 web_demo.py
-rw-r--r-- 1 root root  4633 Jun 27 12:05 web_demo_vision.py

[root@VM-0-7-centos HuggingFace]# ll
total 25174308
-rw-r--r-- 1 root root         773 Jul  7 23:29 config.json
-rw-r--r-- 1 root root        4276 Jul  7 23:29 configuration_chatglm.py
-rw-r--r-- 1 root root 12358633785 Jul  8 02:09 HuggingFace.zip
-rw-r--r-- 1 root root     2706249 Jul  7 23:19 ice_text.model
-rw-r--r-- 1 root root       11336 Jul  7 23:19 LICENSE
-rw-r--r-- 1 root root       57620 Jul  7 23:29 modeling_chatglm.py
-rw-r--r-- 1 root root        2354 Jul  7 23:18 MODEL_LICENSE
-rw-r--r-- 1 root root  1740651802 Jul  7 23:22 pytorch_model-00001-of-00008.bin
-rw-r--r-- 1 root root  1879731432 Jul  7 23:22 pytorch_model-00002-of-00008.bin
-rw-r--r-- 1 root root  1980385902 Jul  7 23:22 pytorch_model-00003-of-00008.bin
-rw-r--r-- 1 root root  1913294120 Jul  7 23:22 pytorch_model-00004-of-00008.bin
-rw-r--r-- 1 root root  1879722289 Jul  7 23:22 pytorch_model-00005-of-00008.bin
-rw-r--r-- 1 root root  1879731496 Jul  7 23:22 pytorch_model-00006-of-00008.bin
-rw-r--r-- 1 root root  1074103621 Jul  7 23:15 pytorch_model-00007-of-00008.bin
-rw-r--r-- 1 root root  1069286123 Jul  7 23:13 pytorch_model-00008-of-00008.bin
-rw-r--r-- 1 root root       33416 Jul  7 23:30 pytorch_model.bin.index.json
-rw-r--r-- 1 root root       15054 Jul  7 23:30 quantization.py
-rw-r--r-- 1 root root        6830 Jul  7 23:29 README.md
-rw-r--r-- 1 root root       13822 Jul  7 23:30 test_modeling_chatglm.py
-rw-r--r-- 1 root root       17047 Jul  7 23:30 tokenization_chatglm.py
-rw-r--r-- 1 root root         441 Jul  7 23:31 tokenizer_config.json

[root@VM-0-7-centos ChatGLM-6B-main]# cat cli_demo.py 
#tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
#model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
#修改
tokenizer = AutoTokenizer.from_pretrained("/data/HuggingFace", trust_remote_code=True)
model = AutoModel.from_pretrained("/data/HuggingFace", trust_remote_code=True).half().cuda()

### Environment

```markdown
[root@VM-0-7-centos ChatGLM-6B-main]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@VM-0-7-centos ChatGLM-6B-main]# uname -a
Linux VM-0-7-centos 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@VM-0-7-centos ChatGLM-6B-main]# python3 -V
Python 3.10.13
[root@VM-0-7-centos ChatGLM-6B-main]# nvidia-smi 
Tue Jul  9 00:17:21 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:08.0 Off |                    0 |
| N/A   42C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[root@VM-0-7-centos ChatGLM-6B-main]# free -mh
              total        used        free      shared  buff/cache   available
Mem:            30G        601M        508M        584K         29G         29G
Swap:            0B          0B          0B
[root@VM-0-7-centos ChatGLM-6B-main]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G   24K   16G   1% /dev/shm
tmpfs            16G  560K   16G   1% /run
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/vda1        99G   45G   51G  47% /
tmpfs           3.1G     0  3.1G   0% /run/user/0
[root@VM-0-7-centos ChatGLM-6B-main]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
Stepping:              5
CPU MHz:               2494.140
BogoMIPS:              4988.28
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              36608K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single rsb_ctxsw fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni

[root@VM-0-7-centos ChatGLM-6B-main]# lspci | grep -i nvidia
00:08.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)
[root@VM-0-7-centos ChatGLM-6B-main]# ldconfig -p | grep libcuda
        libcuda.so.1 (libc6,x86-64) => /lib64/libcuda.so.1
        libcuda.so.1 (libc6) => /lib/libcuda.so.1
        libcuda.so (libc6,x86-64) => /lib64/libcuda.so
        libcuda.so (libc6) => /lib/libcuda.so

[root@VM-0-7-centos ChatGLM-6B-main]# pip3 show torch
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: torch
Version: 1.10.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib64/python3.6/site-packages
Requires: dataclasses, typing-extensions
Required-by: torchaudio, torchvision
```

**Comment by yazong** [comment]
上面这个内容"ImportError: cannot import name 'windll' from 'ctypes' (/usr/local/lib/python3.10/ctypes/init.py)"看到是这个错，咋弄呢？
直接运行python cli_demo.py不合适吧？我这里python是2版本。
[root@VM-0-7-centos ChatGLM-6B-main]# python -V
Python 2.7.5

**Comment by yazong** [comment]
已移步CharGLM3,成功运行跑出效果。
