### ISSUE TITLE
[BUG/Help] Windows下CPU部署chatglm-6b-int4报错“Could not find module 'nvcuda.dll'”

### ISSUE THREAD

**Issue by yanghl12138** [THUDM/ChatGLM-6B#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python3
 model = AutoModel.from_pretrained("H:\project\model\chatglm-6b-int4",trust_remote_code=True).float()
```

```
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yanghl\AppData\Roaming\Python\Python39\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\yanghl\AppData\Roaming\Python\Python39\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\yanghl/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 940, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\yanghl/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\modeling_chatglm.py", line 1262, in quantize
    from .quantization import quantize, QuantizedEmbedding, QuantizedLinear, load_cpu_kernel
  File "C:\Users\yanghl/.cache\huggingface\modules\transformers_modules\chatglm-6b-int4\quantization.py", line 13, in <module>
    from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up
  File "C:\Users\yanghl\AppData\Roaming\Python\Python39\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "C:\Users\yanghl\AppData\Roaming\Python\Python39\site-packages\cpm_kernels\library\__init__.py", line 2, in <module>
    from . import cuda
  File "C:\Users\yanghl\AppData\Roaming\Python\Python39\site-packages\cpm_kernels\library\cuda.py", line 7, in <module>
    cuda = Lib.from_lib("cuda", ctypes.WinDLL("nvcuda.dll"))
  File "D:\Program Files\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### Expected Behavior

正常运行

### Steps To Reproduce

- 已经按照教程和 #6 将模型下载至本地
- 使用本地路径
- 改用.float()

### Environment

```markdown
- OS: Windows 10 21H2
- Python: 3.9.13
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

**Comment by gongjimin** [comment]
针对chatglm-6b-int4项目中的quantization.py我改了两处：
1. 注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”

然后，安装gcc（https://github.com/skeeto/w64devkit/releases）

最后再运行demo就可以了。

**Comment by yanghl12138** [comment]
谢谢，运行成功！

**Comment by zhaokaige** [comment]
基于CPU 、量化模型
修改quantization.py
注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
将“kernels = Kernel(”改成“kernels = CPUKernel(”
 报了如下错误 
 AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

**Comment by zhaokaige** [comment]
cpu_kernels.int4WeightExtractionFloat
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

**Comment by yanghl12138** [comment]
我一开始也遇到的这个问题，后来改用了[gongjimin推荐的gcc编译器](https://github.com/skeeto/w64devkit/releases)，修改环境变量，将家目录下缓存文件的.cache\\huggingface删除，重新运行即可

**Comment by yangpeng0607** [comment]
> cpu_kernels.int4WeightExtractionFloat AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

我也碰到了，除了上面的问题，还发现是demo中的bfloat16()忘了改，改成float()就好了。

**Comment by songxxzp** [comment]
> 感觉针对有GPU和没有GPU的情况，可能还需要有各种判断处理。希望官方能把多种情况的兼容性处理好。

感谢您的提议，我们会尽快改进。

**Comment by JaymzWang** [comment]
> 基于CPU 、量化模型 修改quantization.py 注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up” 将“kernels = Kernel(”改成“kernels = CPUKernel(” 报了如下错误 AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

设置
model = model.quantize(bits=4, kernel_file="/路径/quantization_kernels.so")

**Comment by gongjimin** [comment]
> int4WeightExtractionFloat

没有安装gcc导致的？

**Comment by zhaokaige** [comment]
![1679824377527](https://user-images.githubusercontent.com/28415252/227768078-7cec942a-7c21-4191-a1fd-f018a5460dd3.png)
这个错误是什么原因，有解决的方案吗

**Comment by zhaokaige** [comment]
quantization.py  其中 修改 kernels = CPUKernel()，报如下错误，但该文件其实是存在

![1679828032497](https://user-images.githubusercontent.com/28415252/227770966-15185185-dc89-4792-8994-4e7e48a6ad18.png)

**Comment by zhaokaige** [comment]
**环境：**
Win10,
多核CPU
本地没有安装该文件 nvcuda.dll

**修改内容**
web_demo.py
1.修改model = AutoModel.from_pretrained("model",trust_remote_code=True).float()
quantization.py 
2.注释掉#from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunctn, round_up  避免加载cuda相关代码
3.将kernels = Kernel(......) 替换为 kernels = CPUKernel()

**运行错误**
在我本地如果仅仅修改如上三项内容，启动调用该方法时_dlopen(“自己路径\quantization_kernels_parallels.so")，报错Could not found module quantization_kernels_parallels.so。（调试代码 quantization_kernels_parallels.c 正常生成，并成功通过gcc 编译成so文件）

**测试结果**
但经过测试，直接在 web_demo.py，使用该方法_dlopen(“自己路径\quantization_kernels_parallels.so")是不会报错的，该方法不会报错。这说明并不是该文件找不到，应该运行环境或demo适配的问题

**内核编译逻辑**
quantization.py 编译kernel逻辑是，首先判断本机环境是否是多核CPU,如果是多核CPU则尝试编译quantization_kernels_parallels.c ，如果编译过程中失败则编译这个quantization_kernels.c。因为我本地环境编译过程都是正常。

**暂时的解决方案**
（测试时无意发现）：
web_demo.py 除了上述改动外
第一行添加如下两行代码（打开）
from _ctypes import LoadLibrary as _dlopen
_dlopen(“自己路径\quantization_kernels_parallels.so")
这样就会导致 编译时输出因为该文件已经打开，导致编译出错。按照上述逻辑编译quantization_kernels.c。
备注：可以直接修改quantization.py 110-123之间编译逻辑，直接编译quantization_kernels.c。
启动成功了，运行速度很慢
![image](https://user-images.githubusercontent.com/28415252/227881851-ae308d43-475e-4c43-bd2a-65bd545be279.png)

**期待解决问题**
为什么使用这个quantization_kernels_parallels.so（多核CPU）启动不成功，是否是这个demo有不完善的地方

**Comment by jiangzhihong02** [comment]
![image](https://user-images.githubusercontent.com/108795225/230267372-f8cdac80-7db3-4c23-811b-2d185d5e6714.png)
请问一下卡在这里，应该怎么办

**Comment by zhaokaige** [comment]
你好：
我测试下，这边控制台出现这个信息后，是可以继续运行，并启动成功！，你可以参照我前面我给你详细配置方法，配置下重试下！















在 2023-04-06 11:49:12，"jiangzhihong02" ***@***.***> 写道：


请问一下卡在这里，应该怎么办

**Comment by 1120083505** [comment]
基于CPU 、量化模型
修改quantization.py
注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
将“kernels = Kernel(”改成“kernels = CPUKernel(”
报了如下错误
 NameError: name 'CPUKernel' is not defined

**Comment by 1120083505** [comment]
> 指针对chatglm-6b-int4项目中的quantization.py我改了两处：
> 
> 1. 注解掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> 
> 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> 
> 最后再运行demo就可以了。
报了如下错误
NameError: name 'CPUKernel'没有定义 这种有人遇到吗

**Comment by zhaokaige** [comment]
> > 指针对chatglm-6b-int4项目中的quantization.py我改了两处：
> > 
> > 1. 注解掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> > 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> > 
> > 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> > 最后再运行demo就可以了。
> > 报了如下错误
> > NameError: name 'CPUKernel'没有定义 这种有人遇到吗

这个文件quantization.py中有 CPUKernel对象的定义是没有参数的，请把kernels = Kernel(..）注释掉，替换为kernels =CPUKernel()

**Comment by 1120083505** [comment]
> 
问题已解决 感谢大佬

**Comment by wmo123** [comment]
> 针对chatglm-6b-int4项目中的quantization.py我改了两处：
> 
> 1. 注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> 
> 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> 
> 最后再运行demo就可以了。

可以加上再把已缓存的.cache目录下文件删掉，不然可能还会遇到相似问题~

**Comment by bk007lz** [comment]
> > > 指针对chatglm-6b-int4项目中的quantization.py我改了两处：
> > > 
> > > 1. 注解掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> > > 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> > > 
> > > 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> > > 最后再运行demo就可以了。
> > > 报了如下错误
> > > NameError: name 'CPUKernel'没有定义 这种有人遇到吗
> 
> 这个文件quantization.py中有 CPUKernel对象的定义是没有参数的，请把kernels = Kernel(..）注释掉，替换为kernels =CPUKernel()

    kernels = CPUKernel()
NameError: name 'CPUKernel' is not defined 报这个错如何处理？

**Comment by 1135004584** [comment]
下载一个dll放进去，亲测可以

**Comment by lystrosaurus** [comment]
> 

dll 放到哪个位置呢？

**Comment by taoli-ax** [comment]
> 
安装了gcc，并删除模型缓存重新下载之后，
CPUKernel()依然报错

```
Failed to load cpm_kernels:name 'CPUKernel' is not defined
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile parallel cpu kernel gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels_parallel.c -shared -o C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels_parallel.so failed.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile cpu kernel gcc -O3 -fPIC -std=c99 C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels.c -shared -o C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels.so failed.
Traceback (most recent call last):
  File "D:\LangChainProject\bot\chatBot.py", line 18, in <module>
    response, history = model.chat(tokenizer, "Hallo,Guten Tag", history=[])
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 1027, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\transformers\generation\utils.py", line 1572, in generate
    return self.sample(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\transformers\generation\utils.py", line 2619, in sample
    outputs = self(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 827, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 637, in forward
    layer_ret = layer(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 541, in forward
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 373, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 320, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 223, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\User\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 205, in extract_weight_to_float
    func(
TypeError: 'NoneType' object is not callable
```

**Comment by taoli-ax** [comment]
> > > > 指针对chatglm-6b-int4项目中的quantization.py我改了两处：
> > > > 
> > > > 1. 注解掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> > > > 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> > > > 
> > > > 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> > > > 最后再运行demo就可以了。
> > > > 报了如下错误
> > > > NameError: name 'CPUKernel'没有定义 这种有人遇到吗
> > 
> > 
> > 这个文件quantization.py中有 CPUKernel对象的定义是没有参数的，请把kernels = Kernel(..）注释掉，替换为kernels =CPUKernel()
> 
> ```
> kernels = CPUKernel()
> ```
> 
> NameError: name 'CPUKernel' is not defined 报这个错如何处理？

安装了gcc，并删除模型缓存重新下载之后，
CPUKernel()依然报错

```
Failed to load cpm_kernels:name 'CPUKernel' is not defined
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile parallel cpu kernel gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels_parallel.c -shared -o C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels_parallel.so failed.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
Compile cpu kernel gcc -O3 -fPIC -std=c99 C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels.c -shared -o C:\Users\***\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization_kernels.so failed.
Traceback (most recent call last):
  File "D:\LangChainProject\bot\chatBot.py", line 18, in <module>
    response, history = model.chat(tokenizer, "Hallo,Guten Tag", history=[])
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 1027, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\transformers\generation\utils.py", line 1572, in generate
    return self.sample(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\transformers\generation\utils.py", line 2619, in sample
    outputs = self(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 827, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 637, in forward
    layer_ret = layer(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 541, in forward
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\modeling_chatglm.py", line 373, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "C:\Users\***\Envs\transformers-venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 320, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "C:\Users\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 223, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\User\***/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\eb3e683e8051f93739610afa3de9715b393d5241\quantization.py", line 205, in extract_weight_to_float
    func(
TypeError: 'NoneType' object is not callable
```

**Comment by taoli-ax** [comment]
> 
同问 
`Failed to load cpm_kernels:name 'CPUKernel' is not defined`

**Comment by taoli-ax** [comment]
> > > > 指针对chatglm-6b-int4项目中的quantization.py我改了两处：
> > > > 
> > > > 1. 注解掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
> > > > 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”
> > > > 
> > > > 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> > > > 最后再运行demo就可以了。
> > > > 报了如下错误
> > > > NameError: name 'CPUKernel'没有定义 这种有人遇到吗
> > 
> > 
> > 这个文件quantization.py中有 CPUKernel对象的定义是没有参数的，请把kernels = Kernel(..）注释掉，替换为kernels =CPUKernel()
> 
> ```
> kernels = CPUKernel()
> ```
> 
> NameError: name 'CPUKernel' is not defined 报这个错如何处理？
带伤运行成功，哈哈

虽然报错如下
```
Failed to load cpm_kernels:Could not find module 'nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Hallo, guten Tag! How can I assist you today?
```
但模型随后响应了对话内容 


说明了什么？？

**Comment by Ivan-blade** [comment]
> kernels = CPUKernel(

为什么文件修改了之后执行命令会用原来的内容覆盖修改内容啊，还是会启动失败

**Comment by theskywilldawn** [comment]
感谢，已解决

**Comment by theskywilldawn** [comment]
感谢，已解决

**Comment by hilenti** [comment]
> 针对chatglm-6b-int4项目中的quantization.py我改了两处：
> 
> 1. 注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”注释掉“from cpm_kernels.kernels.base import LazyKernelCModule， KernelFunction， round_up”
> 2. 将“kernels = Kernel(”改成“kernels = CPUKernel(”将“kernels = Kernel（”改成“kernels = CPUKernel（”
> 
> 然后，安装gcc（[https://github.com/skeeto/w64devkit/releases）](https://github.com/skeeto/w64devkit/releases%EF%BC%89)
> 
> 最后再运行demo就可以了。
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization.py", line 34, in <module>
    kernels = CPUKernel(
              ^^^^^^^^^
NameError: name 'CPUKernel' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\chatglm\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\chatglm\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\chatglm\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\chatglm\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\ChatGLM-6B\cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).float()
  File "D:\anaconda3\envs\chatglm\Lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "D:\anaconda3\envs\chatglm\Lib\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\modeling_chatglm.py", line 1061, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\modeling_chatglm.py", line 1424, in quantize
    from .quantization import quantize, QuantizedEmbedding, QuantizedLinear, load_cpu_kernel
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization.py", line 46, in <module>
    logger.warning("Failed to load cpm_kernels:", exception)
Message: 'Failed to load cpm_kernels:'
Arguments: (NameError("name 'CPUKernel' is not defined"),)
No compiled kernel found.
Compiling kernels : C:\Users\hei\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\hei\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization_kernels_parallel.c -shared -o C:\Users\hei\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization_kernels_parallel.so
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\hei\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization_kernels.c -shared -o C:\Users\hei\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization_kernels.so
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "E:\ChatGLM-6B\cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).float()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\chatglm\Lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\chatglm\Lib\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\modeling_chatglm.py", line 1061, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\modeling_chatglm.py", line 1439, in quantize
    self.transformer = quantize(self.transformer, bits, use_quantization_cache=use_quantization_cache, empty_init=empty_init, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hei/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\6c5205c47d0d2f7ea2e44715d279e537cae0911f\quantization.py", line 464, in quantize
    assert kernels is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError
Compile default cpu kernel failed.
Failed to load kernel.
Cannot load cpu or cuda kernel, quantization failed:```
## 环境

-  python 3.11.4
- pip3 install torch torchvision torchaudio
- cpu
- anaconda
