### ISSUE TITLE
[BUG/Help] <title> cli_demo无法运行

### ISSUE THREAD

**Issue by minmin0516** [THUDM/ChatGLM-6B#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/home/wangjt/wangjt/chatGLM/ChatGLM-6B/cli_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()
  File "/home/wangjt/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1b54948bb28de5258b55b893e193c3046a0b0484/modeling_chatglm.py", line 1246, in quantize
    self.transformer = quantize(self.transformer, bits)
  File "/home/wangjt/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1b54948bb28de5258b55b893e193c3046a0b0484/quantization.py", line 147, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/home/wangjt/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1b54948bb28de5258b55b893e193c3046a0b0484/quantization.py", line 130, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/home/wangjt/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1b54948bb28de5258b55b893e193c3046a0b0484/quantization.py", line 71, in compress_int4_weight
    kernels.int4WeightCompression(
  File "/home/wangjt/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/wangjt/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 36, in _prepare_func
    curr_device = cudart.cudaGetDevice()
  File "/home/wangjt/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized

### Steps To Reproduce

python cli_demo.py

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by 910allen** [comment]
没装cuda，只是pytorch有cuda support 还是需要重新装一下cuda。
