### ISSUE TITLE
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by wccccp** [THUDM/ChatGLM-6B#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/gradio/blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/gradio/blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "web_demo.py", line 15, in predict
    for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### Steps To Reproduce

 raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### Environment

```markdown
- OS:
- Python:3.8
- Transformers:4.6.1
- PyTorch:11.7
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by 910allen** [comment]
替换modeling_chatglm.py文件

**Comment by Szysszws** [comment]
请问您说的modeling_chatglm.py文件在呢？

**Comment by Szysszws** [comment]
> 替换modeling_chatglm.py文件

请问您说的modeling_chatglm.py文件在呢？

**Comment by Jieni05** [comment]
> > 替换modeling_chatglm.py文件
> 
> 请问您说的modeling_chatglm.py文件在呢？

你之前下载的模型文件里应该有，替换成新的modeling_chatglm.py即可。

**Comment by wccccp** [comment]
thanks

> 替换modeling_chatglm.py文件

👍

**Comment by Szysszws** [comment]
> thanks
> 
> > 替换modeling_chatglm.py文件
> 
> 👍

能说下怎么替换吗？谢谢

**Comment by dydwgmcnl4241** [comment]
在哪里替换呢？

**Comment by xiao-huichen** [comment]
我也遇到过这个问题，用什么替换进去呢？

**Comment by xiao-huichen** [comment]
新的modeling_chatglm.py文件去哪找呢？

**Comment by chenchen333-dev** [comment]
'ChatGLMForConditionalGeneration' object has no attribute 'float32'
这个问题怎么解决呢？

**Comment by eyesspace** [comment]
> 新的modeling_chatglm.py文件去哪找呢？
知道哪里找吗
