### ISSUE TITLE
[BUG/Help] <title>when I run "tokenizer = AutoTokenizer.from_pretrained("chatglm-6b", trust_remote_code=True)"

### ISSUE THREAD

**Issue by zhqshen** [THUDM/ChatGLM-6B#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Errors:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 619, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 484, in get_tokenizer_config
    result = json.load(reader)
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\ProgramData\Anaconda3\envs\chatglm\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Steps To Reproduce

windows 10 professional
python 3.9.16
Transformers 4.27.1
pytorch 2.0.0
CUDA Support： False

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
加载的路径应该是`THUDM/chatglm-6b`，如果`chatglm-6b`是你本地的路径的话请确保里面有`tokenizer_config.json`
