### ISSUE TITLE
Windows 下加载quantization_kernels_parallel.so出错

### ISSUE THREAD

**Issue by gwaoen** [THUDM/ChatGLM-6B#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

D:\DEV\ChatGLM-6B-main-4\ChatGLM-6B\chatglm4>python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : C:\Users\gwzzt\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c
Compiling gcc -O3 -pthread -fopenmp -std=c99 C:\Users\gwzzt\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.c -shared -o C:\Users\gwzzt\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so
Kernels compiled : C:\Users\gwzzt\.cache\huggingface\modules\transformers_modules\local\quantization_kernels_parallel.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
Traceback (most recent call last):
  File "D:\DEV\ChatGLM-6B-main-4\ChatGLM-6B\chatglm4\cli_demo.py", line 7, in <module>
    model = model.quantize(bits=4, kernel_file="./quantization_kernels_parallel.so")
  File "C:\Users\gwzzt/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1267, in quantize
    load_cpu_kernel(**kwargs)
  File "C:\Users\gwzzt/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 386, in load_cpu_kernel
    cpu_kernels = CPUKernel(**kwargs)
  File "C:\Users\gwzzt/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 137, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

调用代码：

`tokenizer = AutoTokenizer.from_pretrained("./", trust_remote_code=True)
model = AutoModel.from_pretrained("./",trust_remote_code=True).float()
model = model.quantize(bits=4, kernel_file="./quantization_kernels_parallel.so")
model = model.eval()`

### Steps To Reproduce

编译一切正常，无法加载, OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### Environment

```markdown
- OS:win10
- Python:3.11
- Transformers:4.26.1
- PyTorch:1.12.0+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by songxxzp** [comment]
cpu kernel编译之后加载失败，有可能是路径问题（或者杀毒软件），您可以试一下在加载模型后手动重新加载内核：

**Comment by songxxzp** [comment]
cpu kernel编译之后加载失败，有可能是路径问题（或者杀毒软件），您可以试一下在加载模型后手动重新加载cpu kernel：

检查是否安装gcc，openmp
首先手动编译cpu kernel（可以根据情况添加-O2, -O3。在少数设备上-O3可能会导致错误）：
```
gcc -fPIC -std=c99 quantization_kernels.c -shared -o quantization_kernels.so
gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels_parallel.c -shared -o quantization_kernels_parallel.so
```
然后在加载模型后重新加载：
```
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True).float()
model = model.quantize(bits=4, kernel_file="Your Kernel Path")
```
请填写绝对路径。

**Comment by gwaoen** [comment]
编译都没有问题，填写绝对路径提示一样的问题
代码：
tokenizer = AutoTokenizer.from_pretrained("D:/DEV/ChatGLM-6B-main-4/ChatGLM-6B/chatglm4", trust_remote_code=True)
model = AutoModel.from_pretrained("D:/DEV/ChatGLM-6B-main-4/ChatGLM-6B/chatglm4",trust_remote_code=True).float()
model = model.quantize(bits=4, kernel_file="D:/DEV/ChatGLM-6B-main-4/ChatGLM-6B/chatglm4/quantization_kernels_parallel.so")
