### ISSUE TITLE
python web_demo.py ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### ISSUE THREAD

**Issue by wccccp** [THUDM/ChatGLM-6B#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    model = AutoModel.from_pretrained("/mnt1/wcp/chatglm-6b/model/CHATGLM6.2B", trust_remote_code=True).half().cuda()
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### Expected Behavior

本地下载的模型里面含有 configuration_chatglm.py文件 为什么找不到此文件

### Steps To Reproduce

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    model = AutoModel.from_pretrained("/mnt1/wcp/chatglm-6b/model/CHATGLM6.2B", trust_remote_code=True).half().cuda()
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/appuser/miniconda3/envs/wcp/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_chatglm. Run `pip install configuration_chatglm`

### Environment

```markdown
- OS:Ubuntu 20.04

- Python:3.8
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by wkevin** [comment]
I thin 2 points:
1. the from_pretrained(model_path...) function need the model_path in sys.path, transformers lib load configuration_chatglm from sys.path's configuration_chatglm.py.  So, try this:

```python
modelpath = os.path.dirname(os.path.abspath(__file__))+"/chatglm-6b"
sys.path.append(modelpath)

tokenizer = AutoTokenizer.from_pretrained(modelpath, trust_remote_code=True)
model = AutoModel.from_pretrained(modelpath, trust_remote_code=True).half().cuda()
```
3. the model path can not has '.' symble, because transformers import will think about '.' is a python model seperater. So, if you rename the modelpath is hf.chatglm-6b in up code, it will error too.

**Comment by happy-yu1** [comment]
Have you solved this problem yet？

**Comment by chenwenfeng** [comment]
同问
