### ISSUE TITLE
[BUG/Help] <python3 api.py报错>

### ISSUE THREAD

**Issue by xwdreamer** [THUDM/ChatGLM-6B#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行代码：
```
python3 api.py
```
报错如下
```
ERROR:    Error loading ASGI app. Could not import module "API".
```

@duzx16

### Steps To Reproduce

查看了一些文档，发现外面运行uvicorn的内容，好像都是跟文件名一样的。因此修改api.py，将API:app修改为api:app
```
 uvicorn.run('API:app', host='0.0.0.0', port=8000, workers=1)
```
修改
```
 uvicorn.run('api:app', host='0.0.0.0', port=8000, workers=1)
```
再次运行，还是报错
```
python3 api.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/THUDM/chatglm_6b/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-641d491c-6c1e6f5126b082f317eee895)

Repository Not Found for url: https://huggingface.co/THUDM/chatglm_6b/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dellpc/workspace/ai/ChatGLM-6B-main/api.py", line 31, in <module>
    uvicorn.run('api:app', host='0.0.0.0', port=8000, workers=1)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/dellpc/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dellpc/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/dellpc/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dellpc/workspace/ai/ChatGLM-6B-main/api.py", line 34, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm_6b", trust_remote_code=True).half().cuda()
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 896, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/dellpc/anaconda3/lib/python3.9/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: THUDM/chatglm_6b is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.27.1
- PyTorch:
torch                         2.0.0
torchvision                   0.15.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.4
```

**Comment by zerodegress** [comment]
#219 
好像是大小写的问题，我改了就好了

**Comment by xwdreamer** [comment]
> #219 好像是大小写的问题，我改了就好了

我也发现了，是模型名称写了错了。模型名称是chatglm-6b，而不是chatglm_6b
需要将
```
model = AutoModel.from_pretrained("THUDM/chatglm_6b", trust_remote_code=True).half().cuda()
```
修改为
```
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
```

**Comment by ZhangErling** [comment]
第31行【API】->【api】会因为大小写原因找不到API
第34行的下划线【chatglm_6b】->【chatglm-6b】会导致模型加载错误
