### ISSUE TITLE
runtime error when executing model = AutoModel.from_pretrained...

### ISSUE THREAD

**Issue by hiddenblue** [THUDM/ChatGLM-6B#22]
`model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()`

```bash
>>> model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.16s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chase/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/9d1509a1ade49240535535aa020232c8a4b1c114/modeling_chatglm.py", line 1156, in quantize
    self.transformer = quantize(self.transformer, bits)
  File "/home/chase/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/9d1509a1ade49240535535aa020232c8a4b1c114/quantization.py", line 147, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/home/chase/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/9d1509a1ade49240535535aa020232c8a4b1c114/quantization.py", line 130, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/home/chase/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/9d1509a1ade49240535535aa020232c8a4b1c114/quantization.py", line 71, in compress_int4_weight
    kernels.int4WeightCompression(
  File "/home/chase/Documents/miniconda3/envs/GLM/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/chase/Documents/miniconda3/envs/GLM/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 36, in _prepare_func
    curr_device = cudart.cudaGetDevice()
  File "/home/chase/Documents/miniconda3/envs/GLM/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized
```

**platform**
rtx 3070 8g
ubuntu 22.10
python 3.9 in conda virtual environment

**Comment by chentier** [comment]
I used the same 3070 8g and had the same RuntimeError“Library cudart is not initialized”,but I succeeded using the CPU to run,so I guess 8G is not enough to open this project.

**Comment by skirodev** [comment]
Check if you have installed [CUDA](https://developer.nvidia.com/cuda-downloads) and [CuDNN](https://developer.nvidia.com/rdp/cudnn-download).

**Comment by hiddenblue** [comment]
确实是没有装这俩，pip list 不显示cudnn，重启后就好了。我给你们一个建议，生成完整的requirements.txt，所有需要的包，包括cudnn和一堆NVIDIA的依赖，而不是只放现在这个版本里面的这几个依赖。
