### ISSUE TITLE
使用在CPU部署后仍然因nvcuda.dll报错

### ISSUE THREAD

**Issue by SunLightStudio2022** [THUDM/ChatGLM-6B#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我尝试按照README中所述的在CPU上部署
我修改后的代码
```

import os
import platform
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True).float()
model = model.eval()

os_name = platform.system()
clear_command = 'cls' if os_name == 'Windows' else 'clear'


def build_prompt(history):
    prompt = "欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序"
    for query, response in history:
        prompt += f"\n\n用户：{query}"
        prompt += f"\n\nChatGLM-6B：{response}"
    return prompt


def main():
    history = []
    print("欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")
    while True:
        query = input("\n用户：")
        if query == "stop":
            break
        if query == "clear":
            history = []
            os.system(clear_command)
            print("欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")
            continue
        count = 0
        for response, history in model.stream_chat(tokenizer, query, history=history):
            count += 1
            if count % 8 == 0:
                os.system(clear_command)
                print(build_prompt(history), flush=True)
        os.system(clear_command)
        print(build_prompt(history), flush=True)


if __name__ == "__main__":
    main()

```
请问我在操作时有什么错误？谢谢

### Expected Behavior

我遇到的错误
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "client.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True).float()
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\auto\auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\dynamic_module_utils.py", line 274, in get_cached_module_file
    get_cached_module_file(
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\dynamic_module_utils.py", line 129, in check_imports
    importlib.import_module(imp)
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\library\__init__.py", line 2, in <module>
    from . import cuda
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\site-packages\cpm_kernels\library\cuda.py", line 7, in <module>
    cuda = Lib.from_lib("cuda", ctypes.WinDLL("nvcuda.dll"))
  File "C:\Users\weiwei\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### Steps To Reproduce

依次执行了
pip install -r requirements.txt
py client.py（我将修改后的文件保存于此）

### Environment

```markdown
- OS:Windows 7 x64
- Python:3.9 x64
- Transformers:使用未修改的requirements.txt安装
- PyTorch:使用未修改的requirements.txt安装
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False 我想按照README中的“在CPU部署”运行
```

**Comment by duzx16** [comment]
先把模型clone到本地`git clone https://huggingface.co/THUDM/chatglm-6b`
然后把`from_pretrained`的路径改成本地的路径即可
会出现这个问题是因为transformers在加载远程代码的时候会先import代码中出现的所有library，即使实际不会用到，而cpm_kernels无法在没有GPU的环境下正常import

**Comment by YangZhiHu-Hub** [comment]
> 先把模型克隆到本地 然后把的路径改成本地的路径即可 会出现这个问题是因为transformers在加载远程代码的时候会先import代码中出现的所有library，即使实际不会用到，而cpm_kernels无法在没有GPU的环境下正常导入`git clone https://huggingface.co/THUDM/chatglm-6b``from_pretrained`

您好，我通过清华大学云盘把模型下载到了本地，这个模型文件要放到哪个路径下？需不需要子文件夹这些？

**Comment by YangZhiHu-Hub** [comment]
> > 先把模型克隆到本地 然后把的路径改成本地的路径即可 会出现这个问题是因为transformers在加载远程代码的时候会先import代码中出现的所有library，即使实际不会用到，而cpm_kernels无法在没有GPU的环境下正常导入`` git clone https://huggingface.co/THUDM/chatglm-6b``from_pretrained ``
> 
> 您好，我通过清华大学云盘把模型下载到了本地，这个模型文件要放到哪个路径下？需不需要子文件夹这些？

8个bin镜像文件需不需要解压？
