### ISSUE TITLE
[BUG/Help] 最新版的MacBook Pro Apple M2 跑不了

### ISSUE THREAD

**Issue by sudazzk** [THUDM/ChatGLM-6B#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py:662: UserWarning: The operator 'aten::repeat_interleave.self_int' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1670525849783/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Traceback (most recent call last):
  File "/Users/zkzhu/zzk/code/temp/chatglm.py", line 11, in <module>
    response, history = model.chat(tokenizer, "你好", history=[])
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zkzhu/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1126, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 2457, in sample
    next_token_scores = logits_warper(input_ids, next_token_scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 297, in __call__
    indices_to_remove = scores < torch.topk(scores, top_k)[0][..., -1, None]
RuntimeError: Currently topk on mps works only for k<=16

### Steps To Reproduce

from transformers import AutoTokenizer, AutoModel

chatglm_path = '/Users/zkzhu/Downloads/temp_data/BERT/chatglm-6b'
tokenizer = AutoTokenizer.from_pretrained(chatglm_path, trust_remote_code=True)
# model = AutoModel.from_pretrained(chatglm_path, trust_remote_code=True).half().cuda()
model = AutoModel.from_pretrained(chatglm_path, trust_remote_code=True).half().to('mps')  # M2 跑不起来
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
# 你好👋!我是人工智能助手 ChatGLM-6B,很高兴见到你,欢迎问我任何问题。
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)

### Environment

```markdown
- OS: macOS Ventura 13.2.1
- Python: 3.9.15
- Transformers: 4.26.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

**Comment by duzx16** [comment]
可以尝试在chat的调用里加入参数`top_k=0`来禁用topk采样

**Comment by sudazzk** [comment]
Traceback (most recent call last):
  File "/Users/zkzhu/zzk/95128/code/temp/chatglm.py", line 15, in <module>
    response, history = model.chat(tokenizer, "你好", history=[], top_k=0)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zkzhu/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1126, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 2457, in sample
    next_token_scores = logits_warper(input_ids, next_token_scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 259, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)
NotImplementedError: The operator 'aten::sort.values_stable' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

引入了新的问题，换cuda了

**Comment by sudazzk** [comment]
File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/utils.py", line 2457, in sample
    next_token_scores = logits_warper(input_ids, next_token_scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 92, in __call__
    scores = processor(input_ids, scores)
  File "/Users/zkzhu/miniconda3/envs/torch/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 259, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)
NotImplementedError: The operator 'aten::sort.values_stable' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

引入了新的问题，Mac上很多operator没实现，我改用cuda吧

**Comment by duzx16** [comment]
我测试的时候用的是M1 Pro +  Pytorch 2.1.0.dev20230323，可能M2的实现有问题吧

**Comment by duzx16** [comment]
> > 我测试的时候用的是M1 Pro + Pytorch 2.1.0.dev20230323，可能M2的实现有问题吧
> 
> 请教一下，mac可否为Intel？ 必须为Silicon么？

Intel的话可以只用CPU
