### ISSUE TITLE
[Help] 如何pytorch模型转为onnx模型失败

### ISSUE THREAD

**Issue by FdyCN** [THUDM/ChatGLM-6B#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

直接使用transformers[onnx]转换pytorch模型失败，执行方式是参考transformer user guide如下：
![image](https://user-images.githubusercontent.com/80800417/228252309-e56696cb-4970-4ce4-8042-c80bca4dcef5.png)

报错:
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/onnx/__main__.py", line 240, in <module>
    main()
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/onnx/__main__.py", line 232, in main
    export_with_transformers(args)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/onnx/__main__.py", line 75, in export_with_transformers
    model = FeaturesManager.get_model_from_feature(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/onnx/features.py", line 698, in get_model_from_feature
    framework = FeaturesManager.determine_framework(model, framework)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/onnx/features.py", line 660, in determine_framework
    raise FileNotFoundError(
FileNotFoundError: Cannot determine framework from given checkpoint location. There should be a pytorch_model.bin for PyTorch or tf_model.h5 for TensorFlow.
```

看起来应该是ChatGLMConfig配置无法被transformer识别的问题，但是不知道如何操作，看了transformer的user guide也不太懂：
https://huggingface.co/docs/transformers/serialization

希望各位大佬能够答疑解惑，多谢多谢！

### Steps To Reproduce

none

### Environment

```markdown
- OS:
- Python:3.10.9
- Transformers:4.26.1
- PyTorch:1.12.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by boriszhang78** [comment]
用torch.onnx导出可以

**Comment by lfcxlfcx** [comment]
> 用torch.onnx导出可以
大佬知道这个模型具体怎么导出onnx并调用吗？我看pytorch的调用过程不是简单的forward，这个怎么兼容进去呢？

**Comment by lfcxlfcx** [comment]
> 用torch.onnx导出可以

大佬知道这个模型具体怎么导出onnx并调用吗？我看pytorch的调用过程不是简单的forward，这个怎么兼容进去呢？

**Comment by K024** [comment]
整了一份 [ONNX 参考](https://huggingface.co/K024/ChatGLM-6b-onnx-u8s8)

**Comment by lfcxlfcx** [comment]
> 整了一份 [ONNX 参考](https://huggingface.co/K024/ChatGLM-6b-onnx-u8s8)

@K024 大佬牛逼！！！可以顺便给一下onnx的导出和量化过程吗？感激

**Comment by K024** [comment]
@lfcxlfcx readme 里也有写，在[这里](https://github.com/K024/chatglm-q/blob/f4749b5d58fe470ba9887dadc9f02bf2186d5df4/examples/onnx_export.py)

**Comment by lfcxlfcx** [comment]
> @lfcxlfcx readme 里也有写，在[这里](https://github.com/K024/chatglm-q/blob/f4749b5d58fe470ba9887dadc9f02bf2186d5df4/examples/onnx_export.py)

@K024 嗯嗯，刚刚没看到，抱歉，多谢大佬
