### ISSUE TITLE
[BUG/Help] M2 Pro芯片  google.protobuf.message.DecodeError: Wrong wire type in tag.

### ISSUE THREAD

**Issue by wanggz** [THUDM/ChatGLM-6B#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在安装完环境变量后，执行web_demo.py报如下错误：
(chatglm) ***@***MacBook-Pro ChatGLM-6B % python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "web_demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/***/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 215, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file)
  File "/Users/***/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 35, in __init__
    self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)
  File "/Users/***/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 67, in _build_text_tokenizer
    tokenizer = TextTokenizer(self.vocab_file)
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/icetk/text_tokenizer.py", line 26, in __init__
    self.proto.ParseFromString(proto_str)
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/google/protobuf/message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 1192, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "/Users/***/opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/google/protobuf/internal/decoder.py", line 993, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

### Steps To Reproduce

1、git clone https://github.com/THUDM/ChatGLM-6B.git
2、   
git clone https://huggingface.co/THUDM/chatglm-6b-int4
git clone https://huggingface.co/THUDM/chatglm-6b
3、conda create -n chatglm python==3.8
4、pip install -r requirements.txt
5、安装mac的要求修改 web_demo.py 和 modeling_chatglm.py
6、python web_demo.py

### Environment

```markdown
- OS: mac 13.2.1
- Python: 3.8
- Transformers: 4.26.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
1. 可以看一下你的protobuf版本吗？
2. `ice_text.model`文件的sha256值为`99871e0c85db81ad7af1028854fd091cd5778c8414ae9d94bbbc10d02c831c21`，可以检查一下下载是否正确

**Comment by wanggz** [comment]
已经解决了，因为模型下载不正常。重新下载后调试正常。

**Comment by YoYoBao** [comment]
一样的问题：我的protobuf：
Name: protobuf
Version: 3.20.0
Summary: Protocol Buffers

ice_text.model：
 shasum -a 256 ice_text.model 
5e6cca9dcbdafa284002b17d4c423813ddd504187f95b28f85f0a9f573f06656  ice_text.model

看起来模型不对，正确的模型要在哪里下?

**Comment by cqumagege** [comment]
> 已经解决了，因为模型下载不正常。重新下载后调试正常。

请问如何下载正确模型，我也是这个报错一直解决不了，谢谢
