### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`

### ISSUE THREAD

**Issue by dotsonliu** [THUDM/ChatGLM-6B#29]
how to resolve

**Comment by dotsonliu** [comment]
i have install icetk

**Comment by mqormq** [comment]
i also have this problem

**Comment by duzx16** [comment]
Are you running it on Windows? On Windows it requires `protobuf>=3.19.5,<3.20.1` to use `icetk`. Can you check the version of `protobuf` on your environment?

**Comment by duzx16** [comment]
Are you running it on Windows? On Windows it requires `protobuf>=3.19.5,<3.20.1` to use `icetk`. Can you check the version of `protobuf` on your environment?

**Comment by a101269** [comment]
linux 也有这个问题

**Comment by duzx16** [comment]
> linux 也有这个问题
@a101269  
1. Could you run `import icetk` in python?
2. Could you check the version of `protobuf` in your environment?

**Comment by a101269** [comment]
> 

protobuf-3.20.0;
import icetk 出错
>>> import icetk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/__init__.py", line 1, in <module>
    from .ice_tokenizer import IceTokenizer
  File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/ice_tokenizer.py", line 11, in <module>
    from torchvision import transforms
  File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/__init__.py", line 16, in <module>
    from .maxvit import *
  File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/maxvit.py", line 3, in <module>
    from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (/home/liudq/anaconda3/lib/python3.7/typing.py)

**Comment by skirodev** [comment]
This problem usually occurs because you manually installed dependencies. When you install dependencies manually, you may encounter conflicts between different versions. For example, some dependencies may require specific versions of other dependencies to work properly. However, when you install dependencies directly from the requirements.txt file, pip will automatically handle the dependencies and install the correct versions, thus preventing such conflicts. 

Therefore, you need to execute the following command to reinstall the dependencies.
```
pip install -r requirements.txt
```

**Comment by a101269** [comment]
> > 
> 
> protobuf-3.20.0; import icetk 出错
> 
> > > > import icetk
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/**init**.py", line 1, in 
> > > > from .ice_tokenizer import IceTokenizer
> > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/ice_tokenizer.py", line 11, in 
> > > > from torchvision import transforms
> > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/**init**.py", line 5, in 
> > > > from torchvision import datasets, io, models, ops, transforms, utils
> > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/**init**.py", line 16, in 
> > > > from .maxvit import *
> > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/maxvit.py", line 3, in 
> > > > from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
> > > > ImportError: cannot import name 'OrderedDict' from 'typing' (/home/liudq/anaconda3/lib/python3.7/typing.py)

已解决，是python版本问题，python3.7.0版本有点低，更新到3.9可以了

**Comment by ray-008** [comment]
我是Ubuntu22.04系统，安装 liblzma-dev 之后就重新安装Python就可以了，我是docker跑的，下面是我的Dockerfile

```
FROM nvidia/cuda:11.7.1-devel-ubuntu22.04

# 更新系统包
RUN apt-get update && apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev liblzma-dev libbz2-dev curl wget

# 安装Python
WORKDIR /root
RUN wget https://www.python.org/ftp/python/3.10.6/Python-3.10.6.tgz && \
  tar -zvxf Python-3.10.6.tgz && cd Python-3.10.6 && \
  ./configure --enable-optimizations && make -j 4 && make install
```

**Comment by luieswww** [comment]
紧急求助啊，我也是这样的，ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`。

requirements都安装了，protobuf>=3.19.5,<3.20.1
transformers==4.27.1
icetk
cpm_kernels
torch>=1.10
gradio

**Comment by luieswww** [comment]
windows 10系统

**Comment by luieswww** [comment]
> > > 
> > 
> > 
> > protobuf-3.20.0; import icetk 出错
> > > > > import icetk
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/**init**.py", line 1, in
> > > > > from .ice_tokenizer import IceTokenizer
> > > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/icetk/ice_tokenizer.py", line 11, in
> > > > > from torchvision import transforms
> > > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/**init**.py", line 5, in
> > > > > from torchvision import datasets, io, models, ops, transforms, utils
> > > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/**init**.py", line 16, in
> > > > > from .maxvit import *
> > > > > File "/home/liudq/anaconda3/lib/python3.7/site-packages/torchvision/models/maxvit.py", line 3, in
> > > > > from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
> > > > > ImportError: cannot import name 'OrderedDict' from 'typing' (/home/liudq/anaconda3/lib/python3.7/typing.py)
> 
> 已解决，是python版本问题，python3.7.0版本有点低，更新到3.9可以了

我的是3.10，还是有这个问题。。。昨天还好好的，今天就有了这个问题。头疼。
