### ISSUE TITLE
[BUG/Help] ptuning 报错：'ChatGLMModel' object has no attribute 'prefix_encoder'

### ISSUE THREAD

**Issue by nuo-o** [THUDM/ChatGLM-6B#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

执行 ptuning 的过程中，使用默认的脚本参数执行 train.sh 的时候，在 main.py 的line 119 行model.transformer.prefix_encoder.float() 报错：AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Steps To Reproduce

cd ptuning
bash train.sh

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.26.1
- Torch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by xuguozhi** [comment]
看来要更新代码了 https://huggingface.co/THUDM/chatglm-6b

**Comment by WhisperChi** [comment]
拉取最新模型

**Comment by shtdbb** [comment]
我也是，更新最新文件就好了。
但是出现了新的问题
```Traceback (most recent call last):
  File "main.py", line 389, in <module>
    main()
  File "main.py", line 328, in main
    model.enable_input_require_grads()
  File "/usr/local/Anaconda3/envs/FT1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'```

**Comment by WhisperChi** [comment]
看起来是hugging face最新上传的代码有点问题
已经提了个issue #294

**Comment by xuguozhi** [comment]
> 看起来是hugging face最新上传的代码有点问题 已经提了个issue #294

我倒是可以运行，V100

**Comment by WhisperChi** [comment]
按照建议，升级了下transformer到4.27.4，已经可以运行。
关闭了该issue #294

**Comment by duzx16** [comment]
需要安装4.27版本的transformers，并且pull最新的模型实现代码，已经更新了README。

**Comment by yanqiangmiffy** [comment]
> 需要安装4.27版本的transformers，并且pull最新的模型实现代码。已经更新了README。

请问这个怎么操作呢

就是直接拉取最新的代码就可以了吗，需要将模型实现代码替换之前的transformers的里面的代码吗，比如[modeling_chatglm.py](https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py)

**Comment by lunar333** [comment]
> 需要安装4.27版本的transformers，并且pull最新的模型实现代码。已经更新了README。

你好，我也遇到了这个问题，git pull过了，transfoemer版本4.27.4，还是有这个报错，求指点
(glm) zhonghuihang@kdf-B660-AORUS-MASTER-DDR4:~/ChatGLM-6B/ptuning$ git pull
已经是最新的。

Explicitly passing a revision is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a revision is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Loading prefix_encoder weight from /home/zhonghuihang/ChatGLM-6B/ptuning/output/adgen-chatglm-6b-pt-128-2e-2/checkpoint-3000
Explicitly passing a revision is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00, 1.36it/s]
Traceback (most recent call last):
File "/home/zhonghuihang/ChatGLM-6B/ptuning/web_demo.py", line 166, in 
main()
File "/home/zhonghuihang/ChatGLM-6B/ptuning/web_demo.py", line 147, in main
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
File "/home/zhonghuihang/miniconda3/envs/glm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in getattr
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by dongwuuu** [comment]
1、使用GPU运行加载自己微调后的模型是可以正常运行的
2、问题一般出现在使用CPU加载微调后的模型，会产生报错AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
3、解决方案，原代码使用CPU时，会使用LoaderClass.from_pretrained(checkpoint, **params).to(self.llm_device, dtype=float)对模型进行加载，但是这个加载的配置中，没有指明pre_seq_len参数，一般都会是null。所以在加载模型的时候，建议这样加载model = LoaderClass.from_pretrained(checkpoint, config=self.model_config,  trust_remote_code=True).to(self.llm_device, dtype=float)，其中self.model_config中应该包含pre_seq_len参数，该参数需要和微调时候的参数保持一致。

**Comment by 2015sunqian** [comment]
使用GPU，from_pretrained,配置了config，使用还报错，为啥啊？
 File "/home/xuhaiyang/sunqian04/ChatGLM2_pt/ChatGLM2-6B-main/ptuning/main.py", line 131, in main
    model.transformer.prefix_encoder.float()
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1115902 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1115901) of binary: /home/xuhaiyang/miniconda3/envs/sulei03/bin/python
Traceback (most recent call last):
  File "/home/xuhaiyang/miniconda3/envs/sulei03/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xuhaiyang/miniconda3/envs/sulei03/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by Hzzhang-nlp** [comment]
![image](https://github.com/THUDM/ChatGLM-6B/assets/39661319/eeb455c6-4c1f-4ce7-a401-235bbc7632a5)

**Comment by jlwang1980** [comment]
需要指定pre_seq_len
