### ISSUE TITLE
[BUG/Help]  bash start.sh后报错  AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

### ISSUE THREAD

**Issue by XuyaoWang** [THUDM/ChatGLM-6B#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

代码是官方repo里的代码，模型也是从hugging face里更新过的。更新时间为2023/3/31 16：00
修改的地方只有将start.sh里的--model_name_or_path参数改为模型所在文件夹
```
(model_ChatGLM-6B-ptuning) dell@dell-PowerEdge-T550:~/intern/wxy/ChatGLM-6B/ptuning$ bash train.sh 
03/31/2023 16:51:46 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 2distributed training: False, 16-bits training: False
03/31/2023 16:51:46 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=2,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.01,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=passive,
log_level_replica=passive,
log_on_each_node=True,
logging_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev/runs/Mar31_16-51-46_dell-PowerEdge-T550,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/adgen-chatglm-6b-pt-8-1e-2-dev,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=output/adgen-chatglm-6b-pt-8-1e-2-dev,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
03/31/2023 16:51:47 - WARNING - datasets.builder - Found cached dataset json (/home/dell/.cache/huggingface/datasets/json/default-28afb23206891c73/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 183.70it/s]
[INFO|configuration_utils.py:658] 2023-03-31 16:51:47,538 >> loading configuration file /home/dell/models/ChatGLM-6B/chatglm-6b/config.json
[WARNING|configuration_auto.py:861] 2023-03-31 16:51:47,538 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:658] 2023-03-31 16:51:47,544 >> loading configuration file /home/dell/models/ChatGLM-6B/chatglm-6b/config.json
[INFO|configuration_utils.py:712] 2023-03-31 16:51:47,546 >> Model config ChatGLMConfig {
  "_name_or_path": "/home/dell/models/ChatGLM-6B/chatglm-6b",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 20003,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.26.1",
  "use_cache": true,
  "vocab_size": 150528
}

[WARNING|tokenization_auto.py:631] 2023-03-31 16:51:47,547 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|tokenization_utils_base.py:1800] 2023-03-31 16:51:47,665 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1800] 2023-03-31 16:51:47,665 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1800] 2023-03-31 16:51:47,665 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1800] 2023-03-31 16:51:47,665 >> loading file tokenizer_config.json
[WARNING|auto_factory.py:449] 2023-03-31 16:51:48,773 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|modeling_utils.py:2272] 2023-03-31 16:51:48,796 >> loading weights file /home/dell/models/ChatGLM-6B/chatglm-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:543] 2023-03-31 16:51:48,797 >> Generate config GenerationConfig {
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "pad_token_id": 20003,
  "transformers_version": "4.26.1"
}

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:10<00:00,  1.26s/it]
[INFO|modeling_utils.py:2857] 2023-03-31 16:51:59,007 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:2859] 2023-03-31 16:51:59,007 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /home/dell/models/ChatGLM-6B/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2522] 2023-03-31 16:51:59,053 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
/home/dell/miniconda3/envs/model_ChatGLM-6B-ptuning/lib/python3.8/site-packages/dill/_dill.py:1705: PicklingWarning: Cannot locate reference to <class 'google.protobuf.pyext._message.CMessage'>.
  warnings.warn('Cannot locate reference to %r.' % (obj,), PicklingWarning)
/home/dell/miniconda3/envs/model_ChatGLM-6B-ptuning/lib/python3.8/site-packages/dill/_dill.py:1707: PicklingWarning: Cannot pickle <class 'google.protobuf.pyext._message.CMessage'>: google.protobuf.pyext._message.CMessage has recursive self-references that trigger a RecursionError.
  warnings.warn('Cannot pickle %r: %s.%s has recursive self-references that trigger a RecursionError.' % (obj, obj.__module__, obj_name), PicklingWarning)
03/31/2023 16:53:46 - WARNING - datasets.fingerprint - Parameter 'function'=<function main.<locals>.preprocess_function_train at 0x7f999d27ab80> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
input_ids [20005, 85421, 20061, 87329, 20032, 118339, 20061, 92043, 20032, 85347, 20061, 90872, 20032, 89768, 20061, 88944, 20032, 87329, 84103, 20061, 116914, 150001, 150004, 20005, 107052, 116914, 101471, 84562, 85759, 84493, 84988, 20006, 85840, 85388, 94531, 83825, 95786, 84009, 83823, 85626, 83882, 84619, 85388, 20006, 84480, 85604, 105646, 130945, 20010, 84089, 85966, 107052, 87329, 85544, 20006, 91964, 90533, 84417, 83862, 109978, 83991, 83823, 97284, 108473, 84219, 83848, 132012, 20006, 91231, 85099, 91252, 86800, 105768, 84566, 84338, 120323, 95469, 83823, 137317, 84218, 84257, 84051, 94197, 20006, 83893, 150005, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003]
inputs 类型#裤*版型#宽松*风格#性感*图案#线条*裤型#阔腿裤 宽松的阔腿裤这两年真的吸粉不少,明星时尚达人的心头爱。毕竟好穿时尚,谁都能穿出腿长2米的效果宽松的裤腿,当然是遮肉小能手啊。上身随性自然不拘束,面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点,还
label_ids [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 150004, 20005, 107052, 116914, 101471, 84562, 85759, 84493, 84988, 20006, 85840, 85388, 94531, 83825, 95786, 84009, 83823, 85626, 83882, 84619, 85388, 20006, 84480, 85604, 105646, 130945, 20010, 84089, 85966, 107052, 87329, 85544, 20006, 91964, 90533, 84417, 83862, 109978, 83991, 83823, 97284, 108473, 84219, 83848, 132012, 20006, 91231, 85099, 91252, 86800, 105768, 84566, 84338, 120323, 95469, 83823, 137317, 84218, 84257, 84051, 94197, 20006, 83893, 150005, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003, 20003]
labels 宽松的阔腿裤这两年真的吸粉不少,明星时尚达人的心头爱。毕竟好穿时尚,谁都能穿出腿长2米的效果宽松的裤腿,当然是遮肉小能手啊。上身随性自然不拘束,面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点,还
[INFO|trainer.py:511] 2023-03-31 16:54:29,647 >> max_steps is given, it will override any value given in num_train_epochs
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    main()
  File "main.py", line 328, in main
    model.enable_input_require_grads()
  File "/home/dell/miniconda3/envs/model_ChatGLM-6B-ptuning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'
```

### Steps To Reproduce

1. 将start.sh中的--model_name_or_path参数改为本地模型所在地址
2. bash train.sh

### Environment

```markdown
- OS:Linux dell-PowerEdge-T550 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Python:Python 3.8.16
- Transformers:transformers              4.26.1
- PyTorch:torch                     2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by XuyaoWang** [comment]
是我没注意到transformer库需要升级
