### ISSUE TITLE
[BUG/Help] <title>transformers==4.27.1 not work in Windows 11

### ISSUE THREAD

**Issue by wqh17101** [THUDM/ChatGLM-6B#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run demo and get
```
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "G:\ChatGLM-6B\demo.py", line 12, in <module>
    tokenizer = AutoTokenizer.from_pretrained("../chatglm-6b-int4", trust_remote_code=True)
  File "C:\Users\wqh\anaconda3\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "C:\Users\wqh\anaconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\wqh\anaconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\wqh\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'

进程已结束,退出代码1

```

### Expected Behavior

work well.

### Steps To Reproduce

run demo

### Environment

```markdown
- OS:win11
- Python:3.8
- Transformers:4.27.1
- PyTorch:2.0
- CUDA Support True
```

### Anything else?

transformers==4.26.1 works well

**Comment by linchart** [comment]
same environments with you , update the latest[chatglm-6b](https://huggingface.co/THUDM/chatglm-6b) .py files problem solved.

**Comment by wqh17101** [comment]
> same environments with you , update the latest[chatglm-6b](https://huggingface.co/THUDM/chatglm-6b) .py files problem solved.

I cloned this repo yesterday evening, as there are no tags in the repo, could you give the commit id of yours which fixed this problem？ @linchart

**Comment by pootow** [comment]
@wqh17101 try this:
change this line:
```
tokenizer = AutoTokenizer.from_pretrained("../chatglm-6b-int4", trust_remote_code=True)
```
to
```
tokenizer = AutoTokenizer.from_pretrained("..\\chatglm-6b-int4", trust_remote_code=True)
```

**Comment by JiajunDou** [comment]
same error , I had changed to 
```
tokenizer = AutoTokenizer.from_pretrained("./THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("./THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
```
or
```
tokenizer = AutoTokenizer.from_pretrained(".\\THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained(".\\THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
```
always getting 
```
ModuleNotFoundError: No module named 'transformers_modules.'
```
or 
```
ModuleNotFoundError: No module named 'transformers_modules.THUDM/chatglm-6b'
```
Under Windows 11

@pootow

**Comment by duzx16** [comment]
@JiajunDou  Use absolute path instead of relative path for the model.

**Comment by robert-weiqian** [comment]
> latest[chatglm-6b](https://huggingface.co/THUDM/chatglm-6b) .py

how you update it ? and where is file ?

**Comment by wqh17101** [comment]
> Use absolute path instead of relative path for the model.

It worked!

**Comment by robert-weiqian** [comment]
thankful!



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/02/2023 21:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [THUDM/ChatGLM-6B] [BUG/Help] <title>transformers==4.27.1 not work in Windows 11 (Issue #310) |

Use absolute path instead of relative path for the model.

It worked!

**Comment by pootow** [comment]
> model = AutoModel.from_pretrained(".\\THUDM/chatglm-6b", trust_remote_code=True).half().cuda()

you should change path to `.\\THUDM\\chatglm-6b` not `.\\THUDM/chatglm-6b`

**Comment by zhaozhiming** [comment]
> > model = AutoModel.from_pretrained(".\THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
> 
> you should change path to `.\\THUDM\\chatglm-6b` not `.\\THUDM/chatglm-6b`

not working. same error:  ModuleNotFoundError: No module named 'transformers_modules.THUDM/chatglm-6b'

**Comment by PenutChen** [comment]
Just to remind someone who encounters a similar issue, there is a pitfall when including a dot symbol in your model path, e.g., `Model/CodeGen2.5` won't work, etc.

**Comment by userdrew1** [comment]
You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by surya-narayanan** [comment]
Still encountering this problem on linux, no dots in path, when I am using `load_from_checkpoint`

`model.load_from_checkpoint(os.path.normpath('/home/ubuntu/Vornoi/QA/asd.ckpt'), ignore_mismatched_sizes=True)`
