### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`

### ISSUE THREAD

**Issue by luieswww** [THUDM/ChatGLM-6B#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

protobuf>=3.19.5,<3.20.1
transformers==4.27.1
icetk
cpm_kernels
torch>=1.10
gradio
这些都已经安装了

### Steps To Reproduce

1.clone this project 
2.run web_demo.py
3.error happens

### Environment

```markdown
- OS:window10
- Python:3.10
- Transformers:4.27
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

### Anything else?

no

**Comment by makefantasy** [comment]
我也遇到了这个问题，centOS8.2，python-3.8.16，pip-23.0.1

**Comment by duzx16** [comment]
Can you try to run `import icetk` in your python environment?

**Comment by makefantasy** [comment]
(chat_env) [root@VM-0-13-centos ChatGLM-6B-main]# pip install icetk
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Requirement already satisfied: icetk in ./chat_env/lib/python3.8/site-packages (0.0.4)
Requirement already satisfied: sentencepiece in ./chat_env/lib/python3.8/site-packages (from icetk) (0.1.97)
Requirement already satisfied: tqdm in ./chat_env/lib/python3.8/site-packages (from icetk) (4.65.0)
Requirement already satisfied: filelock in ./chat_env/lib/python3.8/site-packages (from icetk) (3.10.7)
Requirement already satisfied: torchvision in ./chat_env/lib/python3.8/site-packages (from icetk) (0.15.1)
Requirement already satisfied: requests in ./chat_env/lib/python3.8/site-packages (from icetk) (2.28.2)
Requirement already satisfied: certifi>=2017.4.17 in ./chat_env/lib/python3.8/site-packages (from requests->icetk) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./chat_env/lib/python3.8/site-packages (from requests->icetk) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in ./chat_env/lib/python3.8/site-packages (from requests->icetk) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./chat_env/lib/python3.8/site-packages (from requests->icetk) (3.1.0)
Requirement already satisfied: torch==2.0.0 in ./chat_env/lib/python3.8/site-packages (from torchvision->icetk) (2.0.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./chat_env/lib/python3.8/site-packages (from torchvision->icetk) (9.4.0)
Requirement already satisfied: numpy in ./chat_env/lib/python3.8/site-packages (from torchvision->icetk) (1.24.2)
Requirement already satisfied: networkx in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (3.0)
Requirement already satisfied: typing-extensions in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (4.5.0)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.7.4.91)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (10.2.10.91)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.7.99)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.7.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.4.0.1)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.10.3.66)
Requirement already satisfied: jinja2 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (3.1.2)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.7.101)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (10.9.0.58)
Requirement already satisfied: triton==2.0.0 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (2.0.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (8.5.0.96)
Requirement already satisfied: sympy in ./chat_env/lib/python3.8/site-packages (from torch==2.0.0->torchvision->icetk) (1.11.1)
Requirement already satisfied: setuptools in ./chat_env/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.0->torchvision->icetk) (56.0.0)
Requirement already satisfied: wheel in ./chat_env/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.0->torchvision->icetk) (0.40.0)
Requirement already satisfied: cmake in ./chat_env/lib/python3.8/site-packages (from triton==2.0.0->torch==2.0.0->torchvision->icetk) (3.26.0)
Requirement already satisfied: lit in ./chat_env/lib/python3.8/site-packages (from triton==2.0.0->torch==2.0.0->torchvision->icetk) (16.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./chat_env/lib/python3.8/site-packages (from jinja2->torch==2.0.0->torchvision->icetk) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in ./chat_env/lib/python3.8/site-packages (from sympy->torch==2.0.0->torchvision->icetk) (1.3.0)
(chat_env) [root@VM-0-13-centos ChatGLM-6B-main]# python cli_demo.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "cli_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "/usr/local/download/ChatGLM-6B-main/chat_env/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "/usr/local/download/ChatGLM-6B-main/chat_env/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/usr/local/download/ChatGLM-6B-main/chat_env/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/usr/local/download/ChatGLM-6B-main/chat_env/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 139, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk`

**Comment by xcg340122** [comment]
我刚才解决了这个问题
环境复现，安装的python版本是3.7.0，尝试从requirements.txt安装所有依赖项后，错误依然存在，然后我import icetk，提示OrderedDict类型错误，然后我定位到错误的文件路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\torchvision\models\maxvit.py，大概就是这个maxvit.py导致的。
将`from typing import Any, Callable, List, OrderedDict，Optional, Sequence, Tuple`的`删除`，下面新增一行`from typing_extensions import OrderedDict`，如果没有安装过`typing_extensions `，就使用pip install一下就好了，然后重新尝试import icetk，错误消失了，正常加载模型

**Comment by Husamx** [comment]
I fixed this by first installing torchvision from conda not pip  
```
conda install torchvision -c pytorch
```
then installed cpm_kernels with pip

**Comment by silenceGuo** [comment]
我刚才解决了这个问题
环境复现，安装的python版本是3.7.0 centos，尝试从requirements.txt安装所有依赖项后，错误依然存在，然后我import icetk，提示
File "/usr/local/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

yum install xz-devel

yum install python-backports-lzma

pip install backports.lzma
![image](https://user-images.githubusercontent.com/28891624/230279979-03955b67-b016-4b2d-946c-bfffe9f24c36.png)

然后重新尝试import icetk，错误消失了，正常加载模型

**Comment by Helmsman-Lab** [comment]
[root@claim-gpt ptuning]# yum install python-backports-lzma
Last metadata expiration check: 2:00:16 ago on Mon 15 May 2023 12:58:55 PM CST.
No match for argument: python-backports-lzma
Error: Unable to find a match: python-backports-lzma
[root@claim-gpt ptuning]# yum install backports.lzma
Last metadata expiration check: 2:00:41 ago on Mon 15 May 2023 12:58:55 PM CST.
No match for argument: backports.lzma
Error: Unable to find a match: backports.lzma

**Comment by YSA-github** [comment]
icetk你装的是什么版本，我这边最高只有0.0.7，它只能兼容protobuf==3.18.1，但它要求protobuf>=3.19.5,<3.20.1，该怎么办

**Comment by silenceGuo** [comment]
python 3.7&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月9日(星期六) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM-6B] ImportError: This modeling file requires the following packages that were not found in your environment: icetk. Run `pip install icetk` (Issue #323)





 
icetk你装的是什么版本，我这边最高只有0.0.7，它只能兼容protobuf==3.18.1，但它要求protobuf&gt;=3.19.5,<3.20.1，该怎么办
