### ISSUE TITLE
[BUG/Help] Huggingface调用模型后报“expected mask dtype to be Bool but got Long”

### ISSUE THREAD

**Issue by wywzxxz** [THUDM/ChatGLM-6B#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2023年4月1日之前正常使用
2023年4月1日晚开始出现此问题，后一度正常，2日中午又发现此问题。
```
Traceback (most recent call last):
  File "/home/wywzxxz/workspace/eftNN_v2/model/chatglm/demo.py", line 9, in <module>
    response, history = model.chat(tokenizer, input(), history=history)
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 1249, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2443, in sample
    outputs = self(
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 1154, in forward
    transformer_outputs = self.transformer(
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 973, in forward
    layer_ret = layer(
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 614, in forward
    attention_outputs = self.attention(
  File "/home/wywzxxz/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 468, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/home/wywzxxz/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/08bc85104db4e8da2c215a29c469218953056251/modeling_chatglm.py", line 308, in attention_fn
    attention_scores.masked_fill_(attention_mask, -10000.0)
RuntimeError: expected mask dtype to be Bool but got Long
```

### Steps To Reproduce

执行model.chat即会出现此问题。
```
from transformers import AutoTokenizer, AutoModel
modelname = "THUDM/chatglm-6b"
tokenizer = AutoTokenizer.from_pretrained(modelname, trust_remote_code=True)
model = AutoModel.from_pretrained(modelname, trust_remote_code=True).half().to("cuda:0")
model = model.eval()
history = []
while True:
    print(">",end="")
    response, history = model.chat(tokenizer, input(), history=history)
    print(response)
```

### Environment

```markdown
- OS: Ubuntu
- Python:Python 3.9.16
- Transformers: 4.26.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by leomeow33** [comment]
一样的问题。

**Comment by piupiuup** [comment]
一样的问题

**Comment by zrqohbug** [comment]
https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L670

**Comment by lucas8485** [comment]
一样的问题

**Comment by duzx16** [comment]
已经修复了。请更新`modeling_chatglm.py`。之前只测试了`stream_chat`没有测试`chat`

**Comment by cppww** [comment]
> 已经修复了。请更新`modeling_chatglm.py`。之前只测试了`stream_chat`没有测试`chat`

还是会有这个错
