### ISSUE TITLE
[Help] <请问这是一个Bug吗？>

### ISSUE THREAD

**Issue by sjkjsandy** [THUDM/ChatGLM-6B#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[INFO|modeling_utils.py:3040] 2023-04-02 23:10:30,618 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at THUDM/chatglm-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2690] 2023-04-02 23:10:34,758 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "C:\Users\l\.conda\envs\slowfast\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Steps To Reproduce

[INFO|modeling_utils.py:3040] 2023-04-02 23:10:30,618 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at THUDM/chatglm-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2690] 2023-04-02 23:10:34,758 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "C:\Users\l\.conda\envs\slowfast\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Environment

```markdown
- OS:windows 10
- Python:3.8
- Transformers:4.27.1
- PyTorch: 1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
你是没有设置`--pre_seq_len`吗

**Comment by RileyShe** [comment]
> 你是没有设置`--pre_seq_len`吗

请问这个参数 是啥意思，干嘛的呀？

**Comment by sjkjsandy** [comment]
是忘记设置 --pre_seq_len 了，可以了，谢谢！
