### ISSUE TITLE
[BUG/Help] <title>'ChatGLMModel' object has no attribute 'prefix_encoder'

### ISSUE THREAD

**Issue by zhangzai666** [THUDM/ChatGLM-6B#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用sh train.sh 时候报错
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
是模型文件更新了吗

### Expected Behavior

使用sh train.sh 时候报错
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
是模型文件更新了吗

### Steps To Reproduce

使用sh train.sh 时候报错
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
是模型文件更新了吗

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
使用sh train.sh 时候报错
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
是模型文件更新了吗
```

### Anything else?

使用sh train.sh 时候报错
Traceback (most recent call last):
  File "main.py", line 391, in <module>
    main()
  File "main.py", line 119, in main
    model.transformer.prefix_encoder.float()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'
是模型文件更新了吗

**Comment by shuxiaobo** [comment]
同问

**Comment by shuxiaobo** [comment]
transformers==4.27.1依旧不work

**Comment by netwolf712** [comment]
我之前用的是之前下载好的模型文件，碰到了同样的问题。
后来把模型路径改回了默认的THUDM/chatglm-6b就正常了。

当前正在训练中，尚不清楚是否模型文件更新导致。

等有时间把本地模型更新了再试试看。

**Comment by zhangzai666** [comment]
> 

好的，感谢您的回答。您更新完了希望同步一下，我这边服务器上跑连不上外网，更新模型文件比较麻烦。
感谢！！！

**Comment by dbbwind** [comment]
我也遇到这个问题，这需要更新 https://huggingface.co/THUDM/chatglm-6b/tree/main 里面的几个py文件
![image](https://user-images.githubusercontent.com/11774267/229465476-ea083c12-6f5b-49a7-9cb8-d0f3a895907a.png)
因为这几个文件是前几天才更新的
现在已经跑通了

**Comment by zhangzai666** [comment]
> 我也遇到这个问题，这需要更新 https://huggingface.co/THUDM/chatglm-6b/tree/main 里面的几个py文件 ![image](https://user-images.githubusercontent.com/11774267/229465476-ea083c12-6f5b-49a7-9cb8-d0f3a895907a.png) 因为这几个文件是前几天才更新的 现在已经跑通了

我换了您说那几个py文件，结果又报了新的错误。AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

**Comment by duzx16** [comment]
> > 我也遇到这个问题，这需要更新 https://huggingface.co/THUDM/chatglm-6b/tree/main 里面的几个py文件 ![image](https://user-images.githubusercontent.com/11774267/229465476-ea083c12-6f5b-49a7-9cb8-d0f3a895907a.png) 因为这几个文件是前几天才更新的 现在已经跑通了
> 
> 我换了您说那几个py文件，结果又报了新的错误。AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'enable_input_require_grads'

请安装transformers 4.27.1

**Comment by Ratelsun** [comment]
我的transformers是4.27.1，模型也是最新的, 怎么解决呢？

**Comment by Ratelsun** [comment]
问题已经解决：
是模型的问题，一定要更新transformers 4.27.1 +  模型bin 文件OK， 
核查模型bin文件，核查模型bin文件，核查模型bin文件，重要的事情说三遍。

**Comment by TuDaCheng** [comment]
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) 这行 预测时需要模型config中含有 pre_seq_len， 模型才会定义prefix_encoder

**Comment by gree2** [comment]
> AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

you saved my day~

**Comment by gree2** [comment]
> model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) 这行 预测时需要模型config中含有 pre_seq_len， 模型才会定义prefix_encoder

you saved my day~
