### ISSUE TITLE
[BUG/Help] ValueError: 150000 is not in list

### ISSUE THREAD

**Issue by EnHuiPug** [THUDM/ChatGLM-6B#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

  0%|          | 19/30000 [31:30<828:54:23, 99.53s/it]
  0%|          | 20/30000 [33:09<828:37:17, 99.50s/it]
  0%|          | 21/30000 [34:48<828:09:42, 99.45s/it]Traceback (most recent call last):
  File "/root/projects/ChatGLM-6B/ptuning/main.py", line 393, in <module>
    main()
  File "/root/projects/ChatGLM-6B/ptuning/main.py", line 332, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/transformers/trainer.py", line 2645, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/transformers/trainer.py", line 2677, in compute_loss
    outputs = model(**inputs)
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 1160, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/torch10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 928, in forward
    mask_positions = [seq.tolist().index(mask_token) for seq in input_ids]
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 928, in <listcomp>
    mask_positions = [seq.tolist().index(mask_token) for seq in input_ids]
ValueError: 150000 is not in list

### Steps To Reproduce

PRE_SEQ_LEN=8
LR=1e-2

CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file ../data/train.json \
    --validation_file ../data/dev.json \
    --prompt_column instruction \
    --response_column output \
    --overwrite_cache \
    --model_name_or_path ~/projects/zero_nlp/simple_thu_chatglm6b/thuglm/ \
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_train_batch_size 100 \
    --per_device_eval_batch_size 100 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 30000 \
    --logging_steps 100 \
    --save_steps 100 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    # --quantization_bit 4

### Environment

```markdown
- OS: centos8
- Python: 3.9
- Transformers: 4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by tripleli-2022** [comment]
同问，请问题主解决了嘛？

**Comment by EnHuiPug** [comment]
> 
“[WARNING|tokenization_utils_base.py:3561] 2023-04-06 11:14:28,794 >> Token indices sequence length is longer than the specified maximum sequence length for this model (4687 > 2048). Running this sequence through the model will result in indexing errors
”
没有解决，正在尝试把数据中长度过长的删除

**Comment by EnHuiPug** [comment]
> > 
> 
> “[WARNING|tokenization_utils_base.py:3561] 2023-04-06 11:14:28,794 >> Token indices sequence length is longer than the specified maximum sequence length for this model (4687 > 2048). Running this sequence through the model will result in indexing errors ” 没有解决，正在尝试把数据中长度过长的删除

依旧没有解决。

**Comment by tripleli-2022** [comment]
我知道原因了，咱们的训练数据里应该是有包含[MASK]的数据，把包含这个字符的数据剔除应该就可以了。
这个字符在训练时会被映射为150000。但程序用的是150001作为mask标志，包含150000就让它混淆了，处理batch的时候就会报错。

**Comment by Sueyangit** [comment]
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好
Traceback (most recent call last):
  File "D:\ChatGLM\ChatGLM-6B-main\cli_demo.py", line 59, in <module>
    main()
  File "D:\ChatGLM\ChatGLM-6B-main\cli_demo.py", line 44, in main
    for response, history in model.stream_chat(tokenizer, query, history=history):
  File "D:\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\18091/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 1281, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "D:\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\18091/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 1356, in stream_generate
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "C:\Users\18091/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 1091, in prepare_inputs_for_generation
    mask_positions = [seq.index(mask_token) for seq in seqs]
  File "C:\Users\18091/.cache\huggingface\modules\transformers_modules\model\modeling_chatglm.py", line 1091, in <listcomp>
    mask_positions = [seq.index(mask_token) for seq in seqs]
ValueError: 150001 is not in list
遇到了同样的问题，请问解决了吗

**Comment by duzx16** [comment]
如果是 @tripleli-2022 说的原因的话已经修复了，更新一下`modeling_chatglm.py`就可以。

**Comment by LvYyLong** [comment]
ValueError: 150000 is not in list
更新了 modeling_chatglm.py 150000 和 150001 都不在list中

**Comment by duzx16** [comment]
> ValueError: 150000 is not in list 更新了 modeling_chatglm.py 150000 和 150001 都不在list中

还需要更新一下 `ice_text.model`。最好是把整个huggingface repo重新pull一遍

**Comment by janenie** [comment]
我这边昨天把ice_text.model, modeling_chatglm.py都更新了也是遇到了这个问题

**Comment by nieallen** [comment]
> 我这边昨天把ice_text.model, modeling_chatglm.py都更新了也是遇到了这个问题

我今天也遇到了这个问题，昨天还没有

**Comment by GordonDongZHAO** [comment]
今天遇到同样问题

**Comment by duzx16** [comment]
@GordonDongZHAO @nieallen @janenie 最新的`ice_text.model`的sha256是5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e，你们能确认一下是否正确吗

**Comment by Sueyangit** [comment]
把昨天https://huggingface.co/THUDM/chatglm-6b/tree/main
最新的模型文件以及py文件都更新了，问题已经解决。

**Comment by EnHuiPug** [comment]
有两种情况，一种情况如
- https://github.com/THUDM/ChatGLM-6B/issues/329
- https://github.com/THUDM/ChatGLM-6B/issues/357
等问题类似，都是本地的权重和代码文件没有更新导致的，解决方案是去官方huggingface去重新下载或者在代码里使用官方地址
第二种情况是数据中包含了[MASK]，bloom的数据就有，示例如下：
{'instruction': '将给定文本中的所有人名替换为“[MASK]”。\n文本：约翰是一位优秀的工程师，他在谷歌公司工作。', 'input': '', 'output': '"[MASK]是一位优秀的工程师，他在谷歌公司工作。"'}
{'instruction': '给定一篇文章，将其中所有的人名替换为“[MASK]”。\n文章文本: “李明和张三同事很关心公司最近的发展情况。”\n', 'input': '', 'output': '"[MASK]和 [MASK] 同事很关心公司最近的发展情况。"'}
该情况删除或修改包含[MASK]的数据即可。

**Comment by scjiaer** [comment]
> 5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e

新机器，直接从头安装依赖拉取最新代码
- ice_text.model的sha256=5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e，经校验没问题
- transformers==4.27.1

昨天下午还能跑，自昨晚main分支有更新后就不能跑，输入也没有包含[MASK]字样。
THUDM/chatglm-6b-int4-qe和THUDM/chatglm-6b-int4均失败，THUDM/chatglm-6b因OOM未测试。
辛苦帮忙看一下@EnHuiPug @duzx16

**Comment by anynomousaccount** [comment]
您好，有一个困惑是，为什么**huggingface里的THUDM/chatglm-6b的仓库和github里的仓库不一致**呢，
比如modeling_chatglm.py和ice_text.model，在huggiface里但不在github这个仓库里？

**Comment by EnHuiPug** [comment]
huggingface会更加新一点？两边可能没同步更新吧

anynomousaccount ***@***.***> 于2025年7月18日周五 09:30写道：

**Comment by anynomousaccount** [comment]
嗯好的，谢谢！感觉有点不方便，有时候问问题或者解决发现是从huggingface那边或者两边弄，但是习惯在github这边弄了
