### ISSUE TITLE
调用api.py启动的服务NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by fxb392** [THUDM/ChatGLM-6B#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

启动的时候加载了模型，但是调用接口的时候报错：NameError: name 'model' is not defined

### Steps To Reproduce

启动api.py后 postman调用
参数：{"prompt": "你好","history":[]}

### Environment

```markdown
- OS:Ubuntu 
- Python:3.8
- Transformers:4.26.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :false
```

**Comment by EnHuiPug** [comment]
贴代码，贴错误log

**Comment by fxb392** [comment]
![Uploading image.png…]()

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/ChatGLM-6B-main/dev_api.py", line 30, in create_item
    print(model)
NameError: name 'model' is not defined
@EnHuiPug

**Comment by EnHuiPug** [comment]
图片看不到

**Comment by hiber-niu** [comment]
https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343

**Comment by HelixPark** [comment]
> 看着是api.py文件写的有问题？这种方式启动，workers不能大于1。https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343
请问大佬，那怎么启动可以让workers大于1？

**Comment by heiheiheibj** [comment]
同问，workers如何大于1
