### ISSUE TITLE
[Help] <title> Oracle Linux 7.9 运行int4模型出错，AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

### ISSUE THREAD

**Issue by purezhanghan** [THUDM/ChatGLM-6B#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/x/home/chatglm_env/lib/python3.7/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
/x/home/chatglm_env/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c -shared -o /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so
sh: gcc: command not found
Compile failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels.c -shared -o /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels.so
Kernels compiled : /x/home/.cache/huggingface/modules/transformers_modules/local/quantization_kernels.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
Traceback (most recent call last):
  File "chatglm-int4-demo.py", line 8, in <module>
    response, history = model.chat(tokenizer, '你好', history=[])
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1137, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/x/home/chatglm_env/lib/python3.7/site-packages/transformers/generation/utils.py", line 1447, in generate
    **model_kwargs,
  File "/x/home/chatglm_env/lib/python3.7/site-packages/transformers/generation/utils.py", line 2447, in sample
    output_hidden_states=output_hidden_states,
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1051, in forward
    return_dict=return_dict,
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 887, in forward
    output_attentions=output_attentions
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 588, in forward
    output_attentions=output_attentions
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 406, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/x/home/chatglm_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 334, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width, self.quantization_cache)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 74, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "/x/home/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 256, in extract_weight_to_float
    func = cpu_kernels.int4WeightExtractionFloat
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

### Steps To Reproduce

from transformers import AutoTokenizer, AutoModel

model_path = '/x/home/chatglm-6b-int4'

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).float()

response, history = model.chat(tokenizer, '你好', history=[])

### Environment

```markdown
- OS: Oracle 7.9
- Python: 3.7.13
- Transformers: 2.6.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : no cuda, use cpu
```

**Comment by duzx16** [comment]
Did you install cpm_kernels?

**Comment by songxxzp** [comment]
感谢您的反馈。该错误由CPU Kernels编译加载失败导致。由于bug，第一次编译失败后，重新编译时编译指令并未被执行。您可以重新下载最新修复后的代码再次尝试。
 
另外根据`sh: gcc: command not found`，您可以检查一下是否已安装gcc和openmp。

**Comment by purezhanghan** [comment]
谢谢回复，重新安装gcc后可以运行了

**Comment by BrettLL** [comment]
> 

修复后的代码是指
对模型里面chatglm-6b-int4/quantization_kernels_parallel.c的修改么？

**Comment by duzx16** [comment]
> > 
> 
> 修复后的代码是指 对模型里面chatglm-6b-int4/quantization_kernels_parallel.c的修改么？

quantization.py
