### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by natureLanguageQing** [THUDM/ChatGLM-6B#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

基于最新代码最新模型ptuing训练自己的数据集

### Expected Behavior

Traceback (most recent call last):
  File "main.py", line 462, in <module>
    main()
  File "main.py", line 401, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2655, in training_step
    self.scaler.scale(loss).backward()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/9324de70a93207c9a310cf99d5d6261791489691/quantization.py", line 63, in backward
    grad_weight = grad_output.t().mm(inp)
RuntimeError: expected scalar type Half but found Float

### Steps To Reproduce

1 pytorch 1.13.1
2 linux ubuntu
3 ptuing
4 error

### Environment

```markdown
- OS:ubuntu
- Python:3.8
- Transformers:4.27.1
- PyTorch:1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
你对训练脚本有做什么修改吗
