### ISSUE TITLE
RuntimeError: Library cudart is not initialized

### ISSUE THREAD

**Issue by wizd** [THUDM/ChatGLM-6B#46]
quantize to int 4 and got error:

<pre>
D:\chatglm6b\ChatGLM-6B>python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.57it/s]
Traceback (most recent call last):
  File "D:\chatglm6b\ChatGLM-6B\web_demo.py", line 5, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda()
  File "C:\Users\wizard/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1156, in quantize
    self.transformer = quantize(self.transformer, bits)
  File "C:\Users\wizard/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 147, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "C:\Users\wizard/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 130, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "C:\Users\wizard/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 71, in compress_int4_weight
    kernels.int4WeightCompression(
  File "C:\Users\wizard\AppData\Local\Programs\Python\Python310\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in __call__
    func = self._prepare_func()
  File "C:\Users\wizard\AppData\Local\Programs\Python\Python310\lib\site-packages\cpm_kernels\kernels\base.py", line 36, in _prepare_func
    curr_device = cudart.cudaGetDevice()
  File "C:\Users\wizard\AppData\Local\Programs\Python\Python310\lib\site-packages\cpm_kernels\library\base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized </pre>

**Comment by wizd** [comment]
Install cuda on windows

**Comment by ankokucao** [comment]
> 

CUDA Toolkit 11.7 is this right?

**Comment by 3BPM** [comment]
> > 
> 
> CUDA Toolkit 11.7 is this right?

+1

**Comment by huohuaqi** [comment]
I run this in the AMD-ROCM based pytorch, and get the same error. I hope the chatGLM can use in AMD GPU

**Comment by YHD233** [comment]
ROCm只能用默认的半精度模型，用不了量化后的，打开都要13g显存了，要RX6800及以上的显卡了
