### ISSUE TITLE
[BUG/Help] TypeError: forward() got an unexpected keyword argument 'return_tensors'

### ISSUE THREAD

**Issue by 1aienthusiast** [THUDM/ChatGLM-6B#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying out any prompt and pressing submit nothing happens.

### Expected Behavior

When pressing the submit button you get an answer from the language model.

### Steps To Reproduce

1. Running inside a conda environment
2. Python3.9
3. pip install -r requirements.txt
4. python web_demo.py
5. type something in the prompt box
6. press the submit button
7. nothing happens
8. error logs:
```
(chatglm) username@localhost:~/AI/ChatGLM-6B$ python web_demo.py
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.c -shared -o /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Kernels compiled : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Load kernel : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 6
Using quantization cache
Applying quantization to glm layers
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.c -shared -o /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Kernels compiled : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Load kernel : /home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 6
Using quantization cache
Applying quantization to glm layers
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/home/username/AI/ChatGLM-6B/web_demo.py", line 61, in predict
    for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/username/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4/a7272d4c9364d026ed77840863900ccfe8703a1b/modeling_chatglm.py", line 1279, in stream_chat
    inputs = tokenizer([prompt], return_tensors="pt")
  File "/home/username/miniconda3/envs/chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'return_tensors'


```

### Environment

```markdown
- OS: Debian Testing
- Python: Python 3.9.16
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support: True
```

**Comment by duzx16** [comment]
你的tokenizer初始化的时候是不是用成AutoModel了

**Comment by 1aienthusiast** [comment]
i think i did (i used deepl.com i dont speak Chinese), my web_demo.py:
```
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html

tokenizer = AutoModel.from_pretrained("THUDM/chatglm-6b-int4-qe", trust_remote_code=True).half().cuda()
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4-qe", trust_remote_code=True).half().cuda()
model = model.eval()

"""Override Chatbot.postprocess"""


def postprocess(self, y):
    if y is None:
        return []
    for i, (message, response) in enumerate(y):
        y[i] = (
            None if message is None else mdtex2html.convert((message)),
            None if response is None else mdtex2html.convert(response),
        )
    return y


gr.Chatbot.postprocess = postprocess


def parse_text(text):
    """copy from https://github.com/GaiZhenbiao/ChuanhuChatGPT/"""
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split('`')
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f'<br></code></pre>'
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", "\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>"+line
    text = "".join(lines)
    return text


def predict(input, chatbot, max_length, top_p, temperature, history):
    chatbot.append((parse_text(input), ""))
    for response, history in model.stream_chat(tokenizer, input, history, max_length=max_length, top_p=top_p,
                                               temperature=temperature):
        chatbot[-1] = (parse_text(input), parse_text(response))       

        yield chatbot, history


def reset_user_input():
    return gr.update(value='')


def reset_state():
    return [], []


with gr.Blocks() as demo:
    gr.HTML("""<h1 align="center">ChatGLM</h1>""")

    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
                    container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
        with gr.Column(scale=1):
            emptyBtn = gr.Button("Clear History")
            max_length = gr.Slider(0, 4096, value=2048, step=1.0, label="Maximum length", interactive=True)
            top_p = gr.Slider(0, 1, value=0.7, step=0.01, label="Top P", interactive=True)
            temperature = gr.Slider(0, 1, value=0.95, step=0.01, label="Temperature", interactive=True)

    history = gr.State([])

    submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history], [chatbot, history],
                    show_progress=True)
    submitBtn.click(reset_user_input, [], [user_input])

    emptyBtn.click(reset_state, outputs=[chatbot, history], show_progress=True)

demo.queue().launch(share=False, inbrowser=True)

```

**Comment by 1aienthusiast** [comment]
solved it by changing 
`tokenizer = AutoModel.from_pretrained("THUDM/chatglm-6b-int4-qe", trust_remote_code=True).half().cuda()`
to
`tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)`
