### ISSUE TITLE
[BUG/Help] 部署wenda时RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

### ISSUE THREAD

**Issue by wangfh5** [THUDM/ChatGLM-6B#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在部署![闻达](https://github.com/l15y/wenda)时, 多次出现的![问题](https://github.com/l15y/wenda/issues/52), 开发者说是ChatGLM的代码, 但我ChatGLM-6B的本地部署是可以运行的. 

### Steps To Reproduce

1. 准备了一个空虚拟环境, 选用传统索引方式, 安装依赖`requirements-sy.txt`; 
2. 运行`run_data_processing.sh`, 无问题;  
3. 运行`run_GLM6B.sh`, 提示没有安装`torch`, 于是安装;  
4. 运行`run_GLM6B.sh`, 报错`RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]`

完整的报错输出如下. 这个错误我一直遇到, 不管是用传统索引还是用语义分割. 
```
glm模型地址 model/chatglm-6b
rwkv模型地址 model/RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth
rwkv模型参数 cuda fp16
日志记录 True
知识库类型 s
LLM模型类型 glm6b
chunk_size 400
chunk_count 3
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/jieba/analyse/tfidf.py:47: ResourceWarning: unclosed file <_io.BufferedReader name='/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/jieba/analyse/idf.txt'>
  content = open(new_idf_path, 'rb').read().decode('utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
知识库加载完成
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wangfh5/AIGC_projects/wenda/wenda.py", line 117, in load_model
    LLM.load_model()
  File "/home/wangfh5/AIGC_projects/wenda/plugins/llm_glm6b.py", line 25, in load_model
    tokenizer = AutoTokenizer.from_pretrained(settings.glm_path, local_files_only=True, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 205, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 61, in __init__
    self.text_tokenizer = TextTokenizer(vocab_file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/.cache/huggingface/modules/transformers_modules/local/tokenization_chatglm.py", line 22, in __init__
    self.sp.Load(model_path)
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
```

### Environment

```markdown
- OS: WSL2 Ubuntu 22.04
- Python: 3.11
- Transformers: 4.26.1
- PyTorch: 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
是否是你的 `ice_text.model`文件没有正确下载，正确的sha256是 `5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e`

**Comment by wangfh5** [comment]
请问如何查看sha256?

**Comment by duzx16** [comment]
> 请问如何查看sha256?

`shasum -a 256 ice_text.model`

**Comment by wangfh5** [comment]
是的, 输出的并不是你说的正确的sha256, 输出的是`ecf23f9174820a8eb325effec7c730edf825acd3e0ea4743ff21bdac8546f08b`.  
我在 ![huggingface](https://huggingface.co/THUDM/chatglm-6b/blob/main/ice_text.model) 上重新下载了`ice_text.model`文件并覆盖了原来的, 输出了正确的sha256. 

至于为什么会下载错误, 应该是我在`git clone`之前没有检查`git lfs install`. 在安装好`git-lfs`之后, 我再次git clone, 就正确下载了`ice_text.model`文件.

**Comment by andreageh** [comment]
> 是否是你的 `ice_text.model`文件没有正确下载，正确的sha256是 `5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e`

![image](https://user-images.githubusercontent.com/129982932/231511912-56aa3a60-1397-4aa7-a5da-e0ea24d2bdf2.png)
您好，看起来我的文件应该没有下错。但是依旧有着同样的问题。方便的时候可以帮忙瞅一眼吗？

**Comment by augiot** [comment]
> 是否是你的 `ice_text.model`文件没有正确下载，正确的sha256是 `5e974d9a69c242ce014c88c2b26089270f6198f3c0b700a887666cd3e816f17e`

可以解决问题

**Comment by cbrcfq** [comment]
谢谢，确实要注意，ice_txt.model的大小2643KB，直接下载下来只是一个sha文本文件，不是一回事。又是一个坑。

**Comment by 22zhangqian** [comment]
请问一下，我的sha256是正确的，但是微调运行train.sh依然报错，RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]   是怎么回事啊
