### ISSUE TITLE
手动下载的模型放到哪个位置？

### ISSUE THREAD

**Issue by helloxz** [THUDM/ChatGLM-6B#50]
看到有这一行说明：

> 如果你从Hugging Face Hub上下载checkpoint的速度较慢，也可以从[这里](https://cloud.tsinghua.edu.cn/d/fb9f16d6dc8f482596c2/)手动下载。

我手动下载了模型，应该放到本地哪个文件夹呢？

**Comment by yaleimeng** [comment]
随便放在哪里都行。。
在加载的时候设置好本地路径即可。

**Comment by helloxz** [comment]
不得行呢，这样会报错：

```
>>> mypath="D:/apps/ChatGLM-6B/model"
>>> from transformers import AutoTokenizer, AutoModel
>>> tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python37\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 614, in from_pretrained
    pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
  File "D:\Program Files\Python37\lib\site-packages\transformers\models\auto\configuration_auto.py", line 852, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\configuration_utils.py", line 632, in _get_config_dict
    _commit_hash=commit_hash,
  File "D:\Program Files\Python37\lib\site-packages\transformers\utils\hub.py", line 381, in cached_file
    f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
OSError: D:/apps/ChatGLM-6B/model does not appear to have a file named config.json. Checkout 'https://huggingface.co/D:/apps/ChatGLM-6B/model/None' for available files.
```

是我姿势没对吗？

**Comment by ykallan** [comment]
同样遇到了这个问题

**Comment by Ling-YangHui** [comment]
I have downloaded all files from huggingface.
However, when I execute 
```python
mypath = "G:/chatGLM-6B/model"
tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
```
it returns:
```
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\<My Username>\\.cache\\huggingface\\modules\\transformers_modules\\G:'
```
It seems that some errors occur in my cache setting

**Comment by feixyz10** [comment]
Path name on Windows should be specially treated (just Google this).  Pathlib package or replacing  "/" with "\\" might  be possible to solve your problem.

**Comment by yaleimeng** [comment]
看报错应该是路径识别有点异常。程序觉得传递的路径有问题（Windows格式），Linux下是/开头而且不会有冒号。
因为程序基本上都是针对Linux系统写的，而Windows系统路径不一样，默认编码也不是utf-8，会有很多坑。
试试按照报错的路径去放置，实在不行建议双系统或者开个Windows的Linux虚拟机去跑（似乎虚拟机能用GPU了吧）。

**Comment by ykallan** [comment]
问题应该已解决，目前我的解决方案是，首先用AutoModel，把模型名称填入进去，然后等待模型下载好后，把模型从~/.cache/xxx 路径下，复制到项目目录，然后修改脚本，这样是可以启动的，直接通过云盘下载的模型，缺少一些文件，不能直接启动 @yaleimeng @feixyz10 @helloxz @Ling-YangHui

**Comment by yaleimeng** [comment]
哦。。我们从huggingface下载的。所以没遇到

**Comment by Liu-Steve** [comment]
云盘只有大文件，只要去huggingface下把小文件下齐就好了，我亲测可行

**Comment by marszhao** [comment]
%USERPROFILE%\.cache\huggingface\hub\models--THUDM--chatglm-6b\snapshots下有一个或多个名字像git版本号的目录，放最新的那个下面就可以了

**Comment by nikshe** [comment]
> 不得行呢，这样会报错：
> 
> ```
> >>> mypath="D:/apps/ChatGLM-6B/model"
> >>> from transformers import AutoTokenizer, AutoModel
> >>> tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Program Files\Python37\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 614, in from_pretrained
>     pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
>   File "D:\Program Files\Python37\lib\site-packages\transformers\models\auto\configuration_auto.py", line 852, in from_pretrained
>     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "D:\Program Files\Python37\lib\site-packages\transformers\configuration_utils.py", line 565, in get_config_dict
>     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "D:\Program Files\Python37\lib\site-packages\transformers\configuration_utils.py", line 632, in _get_config_dict
>     _commit_hash=commit_hash,
>   File "D:\Program Files\Python37\lib\site-packages\transformers\utils\hub.py", line 381, in cached_file
>     f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
> OSError: D:/apps/ChatGLM-6B/model does not appear to have a file named config.json. Checkout 'https://huggingface.co/D:/apps/ChatGLM-6B/model/None' for available files.
> ```
> 
> 是我姿势没对吗？

问题解决了吗？

**Comment by jerrylususu** [comment]
@nikshe 是否文件没有下齐全？除了8个权重文件，hugging face 目录下所有的小文件都要放在模型目录里。看这个报错是模型目录里没有 `config.json` 文件

**Comment by ttsking** [comment]
这8个bin文件要用cat把他们连起来吗，我显示找不到模型文件，但连起来又说读取失败：

root@2227e6c2b8b1:/work/chatglm-6b/ChatGLM-6B# python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "cli_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(8).cuda()
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2164, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory THUDM/chatglm-6b.
root@2227e6c2b8b1:/work/chatglm-6b/ChatGLM-6B#

**Comment by ttsking** [comment]
我的解决了，原来是缺少 pytorch_model.bin.index.json

**Comment by nikohpng** [comment]
我这边必须填写window的绝对路径

**Comment by luieswww** [comment]
> 我的解决了，原来是缺少 pytorch_model.bin.index.json

能分享一下本地运行模型文件的代码吗

**Comment by DelaiahZ** [comment]
我的模型文件是齐全的，路径也是正确的，但是也报错。最后我把keras卸载了，就没有问题了。好神奇啊！

**Comment by bash99** [comment]
我这边在wsl里面，都需要改成绝对路径，两行都要改。

**Comment by tiejiang8** [comment]
> I have downloaded all files from huggingface. However, when I execute
> 
> ```python
> mypath = "G:/chatGLM-6B/model"
> tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
> ```
> 
> it returns:
> 
> ```
> OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\<My Username>\\.cache\\huggingface\\modules\\transformers_modules\\G:'
> ```
> 
> It seems that some errors occur in my cache setting

mypath = "G:\\chatGLM-6B\\model" 这样试试

**Comment by xuji755** [comment]
我的报错信息：
root@DESKTOP-FMBI0K0:/data/ChatGLM-6b# python3 demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1813, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 205, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 55, in __init__
    assert vocab_file is not None
AssertionError

我的代码：
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
mypath="/data/chatglm-6b-int4"
tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
model = AutoModel.from_pretrained(mypath, trust_remote_code=True).half().cuda()
model = model.eval()

我使用的是wsl,下载的模型放在/data/chatglm-6b-int4下

**Comment by drunken-boat** [comment]
This change works in cli_demo.py:
```
local_path = "/home/somepath/somepath/ChatGLM-6B/huggingface_chatglm-6m"
tokenizer = AutoTokenizer.from_pretrained(local_path, trust_remote_code=True)
model = AutoModel.from_pretrained(local_path, trust_remote_code=True).quantize(4).half().cuda()
```

Firstly I downloaded these .bin files from THU cloud and other files in chatglm-6b folder from huggingface, and an OSError showed when running cli_demo.py. 
Then I used "git clone https://huggingface.co/THUDM/chatglm-6b", and it works.

**Comment by xiaoxinxin666666** [comment]
> 我的报错信息： root@DESKTOP-FMBI0K0:/data/ChatGLM-6b# python3 demo.py Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Traceback (most recent call last): File "demo.py", line 5, in tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True) File "/usr/local/lib/python3.7/dist-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1813, in from_pretrained **kwargs, File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 205, in **init** self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens) File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 55, in **init** assert vocab_file is not None AssertionError
> 
> 我的代码： from transformers import AutoModel, AutoTokenizer import gradio as gr import mdtex2html mypath="/data/chatglm-6b-int4" tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True) model = AutoModel.from_pretrained(mypath, trust_remote_code=True).half().cuda() model = model.eval()
> 
> 我使用的是wsl,下载的模型放在/data/chatglm-6b-int4下

我也是一样的情况，给了地址，他还是走缓存

**Comment by duzx16** [comment]
Please follow the instructions at https://github.com/THUDM/ChatGLM-6B#%E4%BB%8E%E6%9C%AC%E5%9C%B0%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B

**Comment by linonetwo** [comment]
```
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("e:\\model\\LanguageModel\\ChatGLM\\chatglm-6b", trust_remote_code=True).half().cuda()
```

这样可以

**Comment by HEXtoDEC** [comment]
在demo.py import之后增加/修改
```python

import os
model_path = os.path.join(".", "models")
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
model = model.eval()
```

然后把从hugfacing上git clone好的文件放到models目录下。这个linux和windows都可以用。

**Comment by 12lxr** [comment]
请问我用的自己训好的模型hf格式，用web_demo跑一直没有反应，没有输出。请问怎么解决呢
![2781686214546_ pic](https://github.com/THUDM/ChatGLM-6B/assets/90822794/84ebde1c-017a-4430-9852-a36005e8b194)

**Comment by daihuangyu** [comment]
模型参数没用缓存，但为什么模型本身加载的py还用的缓存啊，咋解决

**Comment by Louis24** [comment]
> I have downloaded all files from huggingface. However, when I execute
> 
> ```python
> mypath = "G:/chatGLM-6B/model"
> tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
> ```
> 
> it returns:
> 
> ```
> OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\<My Username>\\.cache\\huggingface\\modules\\transformers_modules\\G:'
> ```
> 
> It seems that some errors occur in my cache setting

哈哈哈我今天遇到一样的情况 ， 为什么最后会加个盘符啊？？

**Comment by XuWink** [comment]
![image](https://github.com/THUDM/ChatGLM-6B/assets/66192911/500ef3ca-8800-408a-8d80-498500416910)
我遇到了相同的错误

**Comment by 16sa8d4** [comment]
linux环境上我将下载后的文件夹移动到项目中就可以了
