### ISSUE TITLE
[Help] <title>

### ISSUE THREAD

**Issue by zhangxiaoyuan1988** [THUDM/ChatGLM-6B#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [02:18<00:00, 17.25s/it]
[INFO|modeling_utils.py:3032] 2023-04-11 01:53:13,884 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3040] 2023-04-11 01:53:13,884 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /data/chatglm6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2690] 2023-04-11 01:53:13,938 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
Traceback (most recent call last):
  File "/data/chatglm/ChatGLM-6B/ptuning/main.py", line 413, in <module>
    main()
  File "/data/chatglm/ChatGLM-6B/ptuning/main.py", line 117, in main
    model = model.quantize(model_args.quantization_bit)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm6b/modeling_chatglm.py", line 1260, in quantize
    self.transformer = quantize(self.transformer, bits)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm6b/quantization.py", line 149, in quantize
    weight_tensor=layer.attention.query_key_value.weight.to(torch.cuda.current_device()),
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 552, in current_device
    _lazy_init()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### Steps To Reproduce

pytorch/pytorch                                                        1.13.1-cuda11.6-cudnn8-runtime    
利用pytorch镜像构建容器，在容器内执行sh train.sh  

### Environment

```markdown
NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:04:00.0 Off |                  N/A |
| 38%   39C    P0    57W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN RTX           Off  | 00000000:06:00.0 Off |                  N/A |
| 38%   44C    P0    63W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN RTX           Off  | 00000000:07:00.0 Off |                  N/A |
| 43%   36C    P0    61W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN RTX           Off  | 00000000:0B:00.0 Off |                  N/A |
| 49%   34C    P0    60W / 280W |      0MiB / 24220MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN RTX           Off  | 00000000:0C:00.0 Off |                  N/A |
| 40%   37C    P0    57W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN RTX           Off  | 00000000:0F:00.0 Off |                  N/A |
| 22%   35C    P0    23W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
zhangxiaoyuan@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by duzx16** [comment]
应该是容器的问题。你可以运行 `python -c "import torch; print(torch.cuda.is_available())"` 看能否返回 `True`

**Comment by zhangxiaoyuan1988** [comment]
是false，在容器里是false，在外面是true

**Comment by duzx16** [comment]
> 是false，在容器里是false，在外面是true

那就是环境配置的问题了。跟本仓库无关。
