### ISSUE TITLE
[BUG/Help] ds_train_finetune.sh 多卡训练ModuleNotFoundError:No module named 'transformers_modules.THUDM.chatglm-6b.aa51e62ddc9c9f334858b0af44cf59b05c70148a.configuration_chatglm'

### ISSUE THREAD

**Issue by OceannTwT** [THUDM/ChatGLM-6B#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

单卡finetune training无该问题，多卡出现以下报错 求求帮忙看看是啥情况

### Steps To Reproduce

报错信息：
[2023-04-11 05:57:11,223] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-11 05:57:11,290] [INFO] [runner.py:550:main] cmd = /miniconda/envs/py381/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=31229 --enable_each_rank_log=None main.py --deepspeed deepspeed.json --do_train --train_file AdvertiseGen/train.json --test_file AdvertiseGen/dev.json --prompt_column content --response_column summary --overwrite_cache --model_name_or_path THUDM/chatglm-6b --output_dir ./output/adgen-chatglm-6b-ft-1e-4 --overwrite_output_dir --max_source_length 64 --max_target_length 64 --per_device_train_batch_size 4 --per_device_eval_batch_size 1 --gradient_accumulation_steps 1 --predict_with_generate --max_steps 5000 --logging_steps 10 --save_steps 1000 --learning_rate 1e-4 --fp16
[2023-04-11 05:57:13,931] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-04-11 05:57:13,931] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-04-11 05:57:13,931] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-04-11 05:57:13,931] [INFO] [launch.py:162:main] dist_world_size=2
[2023-04-11 05:57:13,931] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-04-11 05:57:23,422] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
04/11/2023 05:57:24 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
04/11/2023 05:57:24 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=deepspeed.json,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./output/adgen-chatglm-6b-ft-1e-4/runs/Apr11_05-57-23_bolt-ve2y9umam7-gqakast9v7,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=5000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=./output/adgen-chatglm-6b-ft-1e-4,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=4,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=./output/adgen-chatglm-6b-ft-1e-4,
save_on_each_node=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
04/11/2023 05:57:24 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: True
04/11/2023 05:57:25 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-9761ca8977790e5a/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e)
  0%|                                                                                                                                              | 0/2 [00:00<?, ?it/s]04/11/2023 05:57:25 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-9761ca8977790e5a/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 462.54it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 461.52it/s]
[WARNING|configuration_auto.py:905] 2023-04-11 05:57:25,201 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
[INFO|configuration_utils.py:668] 2023-04-11 05:57:25,202 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/aa51e62ddc9c9f334858b0af44cf59b05c70148a/config.json
[WARNING|configuration_auto.py:905] 2023-04-11 05:57:25,202 >> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 108, in main
    config = AutoConfig.from_pretrained(model_args.model_name_or_path, trust_remote_code=True)
  File "/miniconda/envs/py381/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 911, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "/miniconda/envs/py381/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/miniconda/envs/py381/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/miniconda/envs/py381/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'transformers_modules.THUDM.chatglm-6b.aa51e62ddc9c9f334858b0af44cf59b05c70148a.configuration_chatglm'**
[WARNING|tokenization_auto.py:652] 2023-04-11 05:57:25,803 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[WARNING|auto_factory.py:456] 2023-04-11 05:57:27,124 >> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[2023-04-11 05:57:28,014] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 924755
[2023-04-11 05:57:28,015] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 924756
[2023-04-11 05:57:28,151] [ERROR] [launch.py:324:sigkill_handler] ['/miniconda/envs/py381/bin/python', '-u', 'main.py', '--local_rank=1', '--deepspeed', 'deepspeed.json', '--do_train', '--train_file', 'AdvertiseGen/train.json', '--test_file', 'AdvertiseGen/dev.json', '--prompt_column', 'content', '--response_column', 'summary', '--overwrite_cache', '--model_name_or_path', 'THUDM/chatglm-6b', '--output_dir', './output/adgen-chatglm-6b-ft-1e-4', '--overwrite_output_dir', '--max_source_length', '64', '--max_target_length', '64', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '1', '--gradient_accumulation_steps', '1', '--predict_with_generate', '--max_steps', '5000', '--logging_steps', '10', '--save_steps', '1000', '--learning_rate', '1e-4', '--fp16'] exits with return code = 1

### Environment

```markdown
- OS:Linux
- Python:3.8
- Transformers:4.27.1
- PyTorch:2.0.0+default
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by OceannTwT** [comment]
> 

感觉是他的代码有进程冲突问题

**Comment by OceannTwT** [comment]
> 我的也是这样的问题，重新编译了好多次deepseed还是在这报错，请问你解决了吗？

只能多次尝试了

**Comment by hrdxwandg** [comment]
同样的问题。单卡没问题，多卡报这个错。我是从本地加载模型的？但是会读到.cache里面的

**Comment by hrdxwandg** [comment]
原因找到了，是huggingface transformers的bug。
https://github.com/huggingface/transformers/issues/22506
用main分支重新安装下包就行

**Comment by OceannTwT** [comment]
> 原因找到了，是huggingface transformers的bug。
> [huggingface/transformers#22506](https://github.com/huggingface/transformers/issues/22506)
> 用main分支重新安装下包就行

好的 感谢感谢 我之后有机会试试

**Comment by 980202006** [comment]
有时候多加载几次就行了，有时候需要你先单卡加载，基本上每次都是chatglm更新后出现这个问题
