### ISSUE TITLE
[BUG/Help] <title>IndexError: index out of range in self

### ISSUE THREAD

**Issue by threeRepresents** [THUDM/ChatGLM-6B#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main()
  File "main.py", line 368, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/ossfs/workspace/THUDM/ptuning/trainer.py", line 1604, in train
    return inner_training_loop(
  File "THUDM/ptuning/trainer.py", line 1873, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "THUDM/ptuning/trainer.py", line 2604, in training_step
    loss = self.compute_loss(model, inputs)
  File "THUDM/ptuning/trainer.py", line 2635, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1158, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 905, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

### Expected Behavior

请问下是不是cpu跑不起来啊

### Steps To Reproduce

sh train.sh后报错

### Environment

```markdown
- OS:Linux
- Python:3.8.16
- Transformers:transformers==4.27.1
- PyTorch:torch==2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False
```

**Comment by duzx16** [comment]
请确保你使用的 [tokenizer_config.json](https://huggingface.co/THUDM/chatglm-6b/blob/main/tokenizer_config.json) 是最新的

**Comment by xiahuadong1981** [comment]
有可能是你数据集合太少了，检查你的dataset数量。
