### ISSUE TITLE
[BUG/Help] win10 系统 ，cpu模式 无法使用 chatglm-6b-int4 【已解决】

### ISSUE THREAD

**Issue by mingyue0094** [THUDM/ChatGLM-6B#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

载入模型chatglm-6b-int4
```
#这个cpu 模式用不了。win10
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True).float()
```
用以上（chatglm-6b-int4）模型 cpu **运行 网页版本**
python web_demo.py
有2个主要异常。
**异常1**
- 运行后控制台就显示这个异常，然后自动打开问答的网页
```
No compiled kernel found.
Compiling kernels : C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.c -shared -o C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.so
```
**异常2**
- 这个是在打开问答的web网页 ，输入问题之后。点击 Generate 按钮后 控制台窗口显示的异常
- 控制台出现这个异常，并且web页面没有反应。即没回复。
```
  File "G:\2023\4\chatGlB-6b\ChatGLM-6B-main\ChatGLM-6B-main\.env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization.py", line 76, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization.py", line 260, in extract_weight_to_float
    func = cpu_kernels.int4WeightExtractionFloat
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'
```

**但是在用 完整版,就可以正常的使用。**
```
# 这个模型 正常可以用
# 需要大概 32GB 内存     cpu
model = AutoModel.from_pretrained("THUDM/chatglm-6b").float() 
```

### Steps To Reproduce

```
# setps 1
python -m venv .env
.env\Scripts\activate.bat
pip install -r requirements.txt

#setps 2
# 使用原模型 cpu模式
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
#model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float() #32G 内存cpu

# setps 3
# 这个正常使用，用的是  chatglm-6b 
python web_demo.py 

# setps 4
# 这个用不了。 用的是chatglm-6b-int4
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).float() #6G 内存cpu
python web_demo.py


```

### Environment

```markdown
- OS:win10
- Python: Python 3.10.5
- Transformers:transformers       4.27.1
- PyTorch:torch              2.0.0
- CUDA Support :False

- torchvision        0.15.1
```

### Anything else?

系统只有4G显存，所以，gpu版本的，不可以运行。实际体验了下，确实不可以运行。

**Comment by duzx16** [comment]
应该是量化的kernel编译没有成功，你可以看一下 `C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.so`这个文件是否存在
或者提供一下完整的log，目前的log看不到是kernel加载的时候哪里出错了

**Comment by codeAndxv** [comment]
> 应该是量化的kernel编译没有成功，你可以看一下 `C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.so`这个文件是否存在 或者提供一下完整的log，目前的log看不到是kernel加载的时候哪里出错了

相同的错误
 Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
No compiled kernel found.
Compiling kernels : C:\Users\dududu\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\dududu\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.c -shared -o C:\Users\dududu\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.so
Kernels compiled : C:\Users\dududu\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization_kernels_parallel.so
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "D:\project\github.com\THUDM\ChatGLM-6B\test.py", line 5, in <module>
    response, history = model.chat(tokenizer, "你好", history=[])
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\modeling_chatglm.py", line 1253, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\transformers\generation\utils.py", line 1452, in generate
    return self.sample(
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\transformers\generation\utils.py", line 2468, in sample
    outputs = self(
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\modeling_chatglm.py", line 1158, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\modeling_chatglm.py", line 971, in forward
    layer_ret = layer(
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\modeling_chatglm.py", line 612, in forward
    attention_outputs = self.attention(
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\modeling_chatglm.py", line 437, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization.py", line 338, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width, self.quantization_cache)
  File "C:\Users\dududu\.conda\envs\ChatGLM_6B\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization.py", line 76, in forward
    weight = extract_weight_to_float(quant_w, scale_w, weight_bit_width, quantization_cache=quantization_cache)
  File "C:\Users\dududu/.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\9163f7e6d9b2e5b4f66d9be8d0288473a8ccd027\quantization.py", line 260, in extract_weight_to_float
    func = cpu_kernels.int4WeightExtractionFloat
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionFloat'

**Comment by DesistDaydream** [comment]
在使用 chatglm-6b-int4 时，有没有办法可以不用 CPU 而只用 GPU？避免使用 gcc 相关依赖

**Comment by duzx16** [comment]
> 在使用 chatglm-6b-int4 时，有没有办法可以不用 CPU 而只用 GPU？避免使用 gcc 相关依赖

用 `.half().cuda()` 把模型放到 GPU 上就行了

**Comment by DesistDaydream** [comment]
> > 在使用 chatglm-6b-int4 时，有没有办法可以不用 CPU 而只用 GPU？避免使用 gcc 相关依赖
> 
> 用 `.half().cuda()` 把模型放到 GPU 上就行了

确实这么做的，只不过每次都会尝试调用 gcc 编译

![image](https://user-images.githubusercontent.com/39847025/233846731-5180db77-b745-44d4-a402-907436cc22b5.png)

**Comment by worm128** [comment]
AMD显卡如何调用
