### ISSUE TITLE
[BUG/Help] 使用zero3 offload进行全量参数微调报错

### ISSUE THREAD

**Issue by ZeyuTeng96** [THUDM/ChatGLM-6B#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

报错如下：
finished initializing model with 0.53B parameters
Traceback (most recent call last):
  File "main.py", line 406, in <module>
    main()
  File "main.py", line 112, in main
    model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, trust_remote_code=True)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 467, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 355, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/aa51e62ddc9c9f334858b0af44cf59b05c70148a/modeling_chatglm.py", line 1017, in __init__
    self.transformer = ChatGLMModel(config)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 355, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/aa51e62ddc9c9f334858b0af44cf59b05c70148a/modeling_chatglm.py", line 804, in __init__
    dtype=self.params_dtype
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/utils/init.py", line 51, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 363, in wrapper
    self._post_init_method(module)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 760, in _post_init_method
    param.partition()
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 894, in partition
    self._partition(param_list, has_been_updated=has_been_updated)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1038, in _partition
    self._partition_param(param, has_been_updated=has_been_updated)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1128, in _partition_param
    param.ds_tensor.copy_(src_tensor)
NotImplementedError: Cannot copy out of meta tensor; no data!

### Steps To Reproduce

deepspeed配置如下：
{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "gradient_accumulation_steps": "auto",
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
   }
}

ds_train_finetune.sh如下：
LR=1e-4

CUDA_VISIBLE_DEVICES=0 python main.py \
    --deepspeed deepspeed.json \
    --do_train \
    --do_eval \
    --train_file ./data/res/train_data.json \
    --test_file ./data/res/val_data.json \
    --prompt_column prompt \
    --response_column response \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm-6b \
    --output_dir ./output \
    --overwrite_output_dir \
    --max_source_length 640 \
    --max_target_length 384 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 190 \
    --logging_steps 1 \
    --save_steps 8 \
    --eval_steps 8 \
    --evaluation_strategy steps \
    --save_strategy steps \
    --learning_rate $LR \
    --fp16

### Environment

```markdown
deepspeed: 0.8.2
```

**Comment by duzx16** [comment]
因为现在模型创建的时候只考虑了 transfomrers 的创建方式，默认都是 meta tensor，等加载chekcpoint的时候再创建。需要加一个参数来设置这里的行为

**Comment by ZeyuTeng96** [comment]
> 

请问后续官方会增加相应的参数嘛？我感觉这个报错的原因是我的GPU显存被其他的模型占用，导致glm模型好像上不到GPU上，再导致offload的时候no data报错

**Comment by ZeyuTeng96** [comment]
> Now you can pass `empty_init=False` to `AutoModel.from_pretrained` to disable the meta tensors. Remember to update your local `modeling_chatglm.py`.

大佬，我不太理解您说的update local modeling_chatglm.py是什么意思？能否详细说明一下哪里的modeling_chatglm的哪一行需要update

**Comment by duzx16** [comment]
> > Now you can pass `empty_init=False` to `AutoModel.from_pretrained` to disable the meta tensors. Remember to update your local `modeling_chatglm.py`.
> 
> 大佬，我不太理解您说的update local modeling_chatglm.py是什么意思？能否详细说明一下哪里的modeling_chatglm的哪一行需要update

如果你不是从本地加载模型的话可以无视

**Comment by Fcc-Roy** [comment]
> > > > Now you can pass `empty_init=False` to `AutoModel.from_pretrained` to disable the meta tensors. Remember to update your local `modeling_chatglm.py`.
> > > 
> > > 
> > > 大佬，我不太理解您说的update local modeling_chatglm.py是什么意思？能否详细说明一下哪里的modeling_chatglm的哪一行需要update
> > 
> > 
> > 如果你不是从本地加载模型的话可以无视
> 
> 谢谢大佬，想请问下其中的原理是，您们在hugging face 还是 transformers的git上提交了带新empty_init参数的modeling_chatglm.py，然后我安装的是4.28.0.dev0的transformers所以会自动更新嘛？还是说我用的是AutoModel.from_pretrained,这个函数会检查MD5，然后发现和现在hugging face的模型不一致，所以更新呢？

我理解是如果你在from_pretrained里面用了trust_remote_code = True参数，则会从huggingface上拉取最新的modeling_chatglm.py文件，所以你不需要手动做什么操作。如果你的模型是自己从本地加载的，那么你需要手动更新下你本地的这个文件，操作也很简单，就是手动下载下，然后覆盖掉你原来的。

**Comment by lmx760581375** [comment]
在使用 DeepSpeed 进行分布式训练时，DeepSpeed 会将模型分割成多个分块并分配给不同的 GPU 进行训练。在这个过程中，DeepSpeed 会使用 PyTorch 的 `DistributedDataParallel` 包装器来实现分布式训练，而 `DistributedDataParallel` 需要对模型进行初始化。
当您使用 `AutoModel.from_pretrained()` 方法加载预训练模型时，模型权重会被存储在 PyTorch 的 `nn.Parameter` 对象中。在没有指定 `empty_init=False` 参数时，`nn.Parameter` 对象的值将被初始化为全零的张量。但是，由于 `nn.Parameter` 对象不是真正的张量，而是具有元数据的张量包装器，因此无法将这些对象直接复制到 DeepSpeed 使用的元数据张量中。
在指定 `empty_init=False` 参数后，`nn.Parameter` 对象将被初始化为包含预训练权重的张量，这使得 DeepSpeed 能够正常地将权重复制到元数据张量中，从而避免了 `NotImplementedError: Cannot copy out of meta tensor; no data!` 错误的出现。
综上所述，您遇到的问题是因为在使用 DeepSpeed 进行分布式训练时，模型权重的初始化方式与普通的训练方式不同，因此需要通过指定 `empty_init=False` 参数来解决。

NotImplementedError: Cannot copy out of meta tensor; no data! 这个错误通常是由于Deepspeed在使用自定义权重初始化时出现问题，而这些初始化可能需要从先前的训练中加载权重。如果在使用Deepspeed进行分布式训练时出现此错误，则需要在初始化模型时指定`empty_init=False`，以便在加载权重之前，权重矩阵不会被初始化为空。
AutoModel.from_pretrained是Hugging Face Transformers库中的一个方法，用于从预训练模型中加载权重。在Deepspeed分布式训练中，模型的初始化和权重加载可能需要特殊处理，因此需要使用`empty_init=False`参数来指定在加载权重之前不要将权重矩阵初始化为空。
在其他模型中，可能不需要这个参数是因为它们的初始化和权重加载不需要特殊处理，或者因为它们的代码已经进行了相应的修改以适应Deepspeed的分布式训练流程。

**Comment by yang1997yi** [comment]
大佬请问跑起来了吗？我增加了empty_init=False 参数后，又报错AssertionError: Either train_batch_size or train mictro_batch_size_per_gpu needs to be provided，请问您有遇到吗？我的deepseepd=0.9.0

**Comment by lmx760581375** [comment]
@yang1997yi 跑起来了，你的报错显示你的配置少了参数，加一下再试试

**Comment by yang1997yi** [comment]
> 

感谢，确实是参数写错了。大佬您的zero3配置可以分享下吗，我又遇到了deepspeed.runtime.zero.utils.ZeRORuntimeException: You are using ZeRO-Offload with a client provided optimizer (class 'transformers.optimization.AdamW'>) which in most cases will yield poor perf
ormance. Please either use deepspeed.ops.adam.DeepSpeedCPUAdam or set an or in your ds-config (https://www.deepspeed.ai/docs/config-json/#optimizer-rs). If you really want to use a custom optimi
zer w. ZeRO-Offload and understand the performance impacts you can also set <"zero_force_ds_cpu_optimizer": false> in your configuration file.

**Comment by 336655asd** [comment]
2*V100-32G成功跑起来了，我建议的步骤是：
1. 拉取最新的chatglm代码和模型，最新的transformers，最新的deepspeed，分别安装好。我的transformers版本为4.28.1，deepspeed版本为0.9.0
2. main.py文件，修改模型读取参数，model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, empty_init=False, trust_remote_code=True)
3. ds_train_finetune.sh，删除quantization_bit参数，per_device_train_batch_size、max_source_length、max_target_length调低
4. 修改deepspeed.json文件，我的配置如下：
```
{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
},
"optimizer": {
  "type": "AdamW",
  "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
  }
},
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
  },
  "offload_param": {
      "device": "cpu",
      "pin_memory": true
  },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "reduce_scatter": true,
    "contiguous_gradients" : true,
    "overlap_comm": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  }
}
```

**Comment by vikki7777** [comment]
@lmx760581375 看到你说“DeepSpeed 会将模型分割成多个分块并分配给不同的 GPU 进行训练”，我有个问题想请教一下：
我是单机多卡，4张V100 16G
我用一张GPU训练的时候，显存占用了15G，我用4张GPU训练的时候，每张显存占用还是15G；
Deepspeed做模型拆分的话，4张GPU训练的时候，显存占用为什么和一张GPU的一样啊？不应该是15/4吗？

**Comment by Ren-Ma** [comment]
> 

这个回答语气有点像ChatGPT的回答，说囫囵话~

**Comment by Ren-Ma** [comment]
> 在使用 DeepSpeed 进行分布式训练时，DeepSpeed 会将模型分割成多个分块并分配给不同的 GPU 进行训练。在这个过程中，DeepSpeed 会使用 PyTorch 的 `DistributedDataParallel` 包装器来实现分布式训练，而 `DistributedDataParallel` 需要对模型进行初始化。 当您使用 `AutoModel.from_pretrained()` 方法加载预训练模型时，模型权重会被存储在 PyTorch 的 `nn.Parameter` 对象中。在没有指定 `empty_init=False` 参数时，`nn.Parameter` 对象的值将被初始化为全零的张量。但是，由于 `nn.Parameter` 对象不是真正的张量，而是具有元数据的张量包装器，因此无法将这些对象直接复制到 DeepSpeed 使用的元数据张量中。 在指定 `empty_init=False` 参数后，`nn.Parameter` 对象将被初始化为包含预训练权重的张量，这使得 DeepSpeed 能够正常地将权重复制到元数据张量中，从而避免了 `NotImplementedError: Cannot copy out of meta tensor; no data!` 错误的出现。 综上所述，您遇到的问题是因为在使用 DeepSpeed 进行分布式训练时，模型权重的初始化方式与普通的训练方式不同，因此需要通过指定 `empty_init=False` 参数来解决。
> 
> NotImplementedError: Cannot copy out of meta tensor; no data! 这个错误通常是由于Deepspeed在使用自定义权重初始化时出现问题，而这些初始化可能需要从先前的训练中加载权重。如果在使用Deepspeed进行分布式训练时出现此错误，则需要在初始化模型时指定`empty_init=False`，以便在加载权重之前，权重矩阵不会被初始化为空。 AutoModel.from_pretrained是Hugging Face Transformers库中的一个方法，用于从预训练模型中加载权重。在Deepspeed分布式训练中，模型的初始化和权重加载可能需要特殊处理，因此需要使用`empty_init=False`参数来指定在加载权重之前不要将权重矩阵初始化为空。 在其他模型中，可能不需要这个参数是因为它们的初始化和权重加载不需要特殊处理，或者因为它们的代码已经进行了相应的修改以适应Deepspeed的分布式训练流程。

这个回答语气有点像ChatGPT的回答，说囫囵话~ haha

**Comment by hongyix** [comment]
> 

请问一下，你的内存用了多少呢？

**Comment by xiongxiaochu** [comment]
> 2*V100-32G成功跑起来了，我建议的步骤是：
> 
> 1. 拉取最新的chatglm代码和模型，最新的transformers，最新的deepspeed，分别安装好。我的transformers版本为4.28.1，deepspeed版本为0.9.0
> 2. main.py文件，修改模型读取参数，model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, empty_init=False, trust_remote_code=True)
> 3. ds_train_finetune.sh，删除quantization_bit参数，per_device_train_batch_size、max_source_length、max_target_length调低
> 4. 修改deepspeed.json文件，我的配置如下：
> 
> ```
> {
>   "train_micro_batch_size_per_gpu": "auto",
>   "zero_allow_untested_optimizer": true,
>   "fp16": {
>     "enabled": "auto",
>     "loss_scale": 0,
>     "initial_scale_power": 16,
>     "loss_scale_window": 1000,
>     "hysteresis": 2,
>     "min_loss_scale": 1
>   },
>   "bf16": {
>     "enabled": "auto"
> },
> "optimizer": {
>   "type": "AdamW",
>   "params": {
>       "lr": "auto",
>       "betas": "auto",
>       "eps": "auto",
>       "weight_decay": "auto"
>   }
> },
>   "zero_optimization": {
>     "stage": 3,
>     "offload_optimizer": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>   "offload_param": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>     "allgather_partitions": true,
>     "allgather_bucket_size": 5e8,
>     "reduce_scatter": true,
>     "contiguous_gradients" : true,
>     "overlap_comm": true,
>     "sub_group_size": 1e9,
>     "reduce_bucket_size": "auto",
>     "stage3_prefetch_bucket_size": "auto",
>     "stage3_param_persistence_threshold": "auto",
>     "stage3_max_live_parameters": 1e9,
>     "stage3_max_reuse_distance": 1e9,
>     "stage3_gather_16bit_weights_on_model_save": true
>   }
> }
> ```

请问下大佬，cpu内存占用了多少呀？我们尝试了3*24G的GPU，60G的cpu内存直接爆掉了

**Comment by aprilehannibal** [comment]
> 

@336655asd 没看到AutoModel.from_pretrained有empty_init=False这样的参数设置，使用这种方案报错了，请问这里需要魔改代码吗？

**Comment by Ren-Ma** [comment]
> > 
> 
> @336655asd 没看到AutoModel.from_pretrained有empty_init=False这样的参数设置，使用这种方案报错了，请问这里需要魔改代码吗？

下载chatglm最新的modeling_chatglm.py文件。

**Comment by chenyangjun45** [comment]
> 2*V100-32G成功跑起来了，我建议的步骤是：
> 
> 1. 拉取最新的chatglm代码和模型，最新的transformers，最新的deepspeed，分别安装好。我的transformers版本为4.28.1，deepspeed版本为0.9.0
> 2. main.py文件，修改模型读取参数，model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, empty_init=False, trust_remote_code=True)
> 3. ds_train_finetune.sh，删除quantization_bit参数，per_device_train_batch_size、max_source_length、max_target_length调低
> 4. 修改deepspeed.json文件，我的配置如下：
> 
> ```
> {
>   "train_micro_batch_size_per_gpu": "auto",
>   "zero_allow_untested_optimizer": true,
>   "fp16": {
>     "enabled": "auto",
>     "loss_scale": 0,
>     "initial_scale_power": 16,
>     "loss_scale_window": 1000,
>     "hysteresis": 2,
>     "min_loss_scale": 1
>   },
>   "bf16": {
>     "enabled": "auto"
> },
> "optimizer": {
>   "type": "AdamW",
>   "params": {
>       "lr": "auto",
>       "betas": "auto",
>       "eps": "auto",
>       "weight_decay": "auto"
>   }
> },
>   "zero_optimization": {
>     "stage": 3,
>     "offload_optimizer": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>   "offload_param": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>     "allgather_partitions": true,
>     "allgather_bucket_size": 5e8,
>     "reduce_scatter": true,
>     "contiguous_gradients" : true,
>     "overlap_comm": true,
>     "sub_group_size": 1e9,
>     "reduce_bucket_size": "auto",
>     "stage3_prefetch_bucket_size": "auto",
>     "stage3_param_persistence_threshold": "auto",
>     "stage3_max_live_parameters": 1e9,
>     "stage3_max_reuse_distance": 1e9,
>     "stage3_gather_16bit_weights_on_model_save": true
>   }
> }
> ```

我想问一下，配了CPU  offload后，CPU的内存占用有多少啊，我这边也是用的V100，但是启动以后就卡住了，怀疑是内存不够，我这边每台服务器内存是32G，GPU是32G的V100

**Comment by wusi1590** [comment]
zero3全参数微调启动之后看起来好好的，突然就断掉了，有人遇到这种情况么？
Adam Optimizer #0 is created with AVX512 arithmetic capability.
Config: alpha=0.000100, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2023-07-26 10:30:40,270] [INFO] [logging.py:96:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2023-07-26 10:30:40,280] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2023-07-26 10:30:40,280] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2023-07-26 10:30:40,280] [INFO] [logging.py:96:log_dist] [Rank 0] Creating fp16 ZeRO stage 3 optimizer, MiCS is enabled False, Hierarchical params gather False
[2023-07-26 10:30:40,280] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 3 optimizer
Loading extension module cpu_adam...
Time to load cpu_adam op: 2.700096368789673 seconds
Using /home/ma-user/.cache/torch_extensions/py37_cu117 as PyTorch extensions root...
[2023-07-26 10:30:40,411] [INFO] [utils.py:785:see_memory_usage] Stage 3 initialize beginning
[2023-07-26 10:30:40,412] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.99 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:40,412] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 38.33 GB, percent = 7.6%
[2023-07-26 10:30:40,414] [INFO] [stage3.py:113:__init__] Reduce bucket size 16777216
[2023-07-26 10:30:40,414] [INFO] [stage3.py:114:__init__] Prefetch bucket size 15099494
Using /home/ma-user/.cache/torch_extensions/py37_cu117 as PyTorch extensions root...
Emitting ninja build file /home/ma-user/.cache/torch_extensions/py37_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.2742156982421875 seconds
Loading extension module utils...
Time to load utils op: 0.30308079719543457 seconds
[2023-07-26 10:30:40,812] [INFO] [utils.py:785:see_memory_usage] DeepSpeedZeRoOffload initialize [begin]
[2023-07-26 10:30:40,812] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:40,813] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 38.32 GB, percent = 7.6%
Parameter Offload: Total persistent parameters: 362496 in 85 params
[2023-07-26 10:30:40,916] [INFO] [utils.py:785:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
[2023-07-26 10:30:40,916] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:40,917] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 38.33 GB, percent = 7.6%
[2023-07-26 10:30:40,992] [INFO] [utils.py:785:see_memory_usage] Before creating fp16 partitions
[2023-07-26 10:30:40,995] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:40,995] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 38.33 GB, percent = 7.6%
[2023-07-26 10:30:46,578] [INFO] [utils.py:785:see_memory_usage] After creating fp16 partitions: 3
[2023-07-26 10:30:46,579] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:46,580] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 55.19 GB, percent = 11.0%
[2023-07-26 10:30:46,785] [INFO] [utils.py:785:see_memory_usage] Before creating fp32 partitions
[2023-07-26 10:30:46,786] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:46,787] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 59.39 GB, percent = 11.8%
[2023-07-26 10:30:54,182] [INFO] [utils.py:785:see_memory_usage] After creating fp32 partitions
[2023-07-26 10:30:54,189] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:54,190] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 77.86 GB, percent = 15.5%
[2023-07-26 10:30:55,747] [INFO] [utils.py:785:see_memory_usage] Before initializing optimizer states
[2023-07-26 10:30:56,163] [INFO] [utils.py:789:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 1.49 GB         Max_CA 1 GB 
[2023-07-26 10:30:56,168] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 83.68 GB, percent = 16.6%
[2023-07-26 10:31:05,773] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 41201
[2023-07-26 10:31:10,259] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 41202
[2023-07-26 10:31:10,259] [ERROR] [launch.py:434:sigkill_handler] ['/home/ma-user/anaconda3/envs/python-3.7.10/bin/python3.7', '-u', 'main.py', '--local_rank=1', '--deepspeed', 'deepspeed.json', '--do_train', '--train_file', '/home/ma-user/work/data/ISDP_QA.json', '--test_file', '/home/ma-user/work/data/ISDP_QA.json', '--prompt_column', 'query', '--response_column', 'answer', '--overwrite_cache', '--model_name_or_path', '/home/ma-user/work/model/chatglm-6b2', '--output_dir', 'output-ISDP/allfinetune-1e-4', '--overwrite_output_dir', '--max_source_length', '64', '--max_target_length', '256', '--per_device_train_batch_size', '2', '--per_device_eval_batch_size', '1', '--gradient_accumulation_steps', '1', '--predict_with_generate', '--max_steps', '500', '--logging_steps', '10', '--save_steps', '1000', '--learning_rate', '1e-4', '--fp16'] exits with return code = -9

**Comment by ustcuna** [comment]
> "offload_optimizer": {
>       "device": "cpu",
>       "pin_memory": true
>   },
>   "offload_param": {
>       "device": "cpu",
>       "pin_memory": true
>   },

您好！遇到同样问题了，请问下您这问题解了吗

**Comment by newtonysls** [comment]
使用了empty init之后 zero stage 3 直接让模型的state dict全为0了 急急急！！！！！
