### ISSUE TITLE
[BUG/Help] 无法使用下载的模型

### ISSUE THREAD

**Issue by xuji755** [THUDM/ChatGLM-6B#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

从网上下载的模型无法使用

### Steps To Reproduce

我的报错信息：
root@DESKTOP-FMBI0K0:/data/ChatGLM-6b# python3 demo.py
Explicitly passing a revision is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
File "demo.py", line 5, in
tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained
return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1813, in from_pretrained
**kwargs,
File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained
tokenizer = cls(*init_inputs, **init_kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 205, in init
self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/tokenization_chatglm.py", line 55, in init
assert vocab_file is not None
AssertionError

我的代码：
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
mypath="/data/chatglm-6b-int4"
tokenizer = AutoTokenizer.from_pretrained(mypath, trust_remote_code=True)
model = AutoModel.from_pretrained(mypath, trust_remote_code=True).half().cuda()
model = model.eval()

我使用的是wsl,下载的模型放在/data/chatglm-6b-int4下

### Environment

```markdown
- OS: Debian（WSL 2.0)
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by xuji755** [comment]
已经解决，缺文件。

**Comment by poo0054** [comment]
兄弟,缺什么文件
