### ISSUE TITLE
[BUG/Help] 报错：CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by linkxzhou** [THUDM/ChatGLM-6B#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/data/github/ChatGLM-6B/web_demo.py", line 11, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
  File "/usr/local/python3.9/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/usr/local/python3.9/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/usr/local/python3.9/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 299, in get_cached_module_file
    get_cached_module_file(
  File "/usr/local/python3.9/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/usr/local/python3.9/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    importlib.import_module(imp)
  File "/usr/local/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/__init__.py", line 2, in <module>
    from .kernels import *
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/kernels/__init__.py", line 1, in <module>
    from .embedding import embedding_forward, embedding_backward_stage1, embedding_backward_stage2, embedding_step
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/kernels/embedding.py", line 1, in <module>
    from .base import Kernel, DevicePointer, CUDAStream, round_up
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 5, in <module>
    from ..device import Device
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/device/__init__.py", line 126, in <module>
    _Device(i) for i in range(cudart.cudaGetDeviceCount())
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/library/cudart.py", line 351, in cudaGetDeviceCount
    checkCUDAStatus(cuda.cudaGetDeviceCount(ctypes.byref(count)))
  File "/usr/local/python3.9/lib/python3.9/site-packages/cpm_kernels/library/cudart.py", line 327, in checkCUDAStatus
    raise RuntimeError("CUDA Runtime Error: %s" % cudaGetErrorString(error))
RuntimeError: CUDA Runtime Error: CUDA driver version is insufficient for CUDA runtime version

### Steps To Reproduce

python web_demo.py

### Environment

```markdown
- OS: Centos7.0
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
该问题跟本仓库无关。是GPU的驱动版本过低，跟CUDA版本不匹配。解决方法可以自行搜索一下
