### ISSUE TITLE
[BUG/Help] dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by xu78guo6** [THUDM/ChatGLM-6B#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我准备在一台CPU服务器上运行ChatGLM的网页版和CLI版，但遇到以下问题
Traceback (most recent call last):
  File "/home/users/xuguoyao/ChatGLM-6B/cli_demo.py", line 7, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 915, in from_pretrained
    return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 553, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 696, in from_dict
    config = cls(**config_dict)
  File "/home/users/xuguoyao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/aa51e62ddc9c9f334858b0af44cf59b05c70148a/configuration_chatglm.py", line 98, in __init__
    super().__init__(
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/transformers/configuration_utils.py", line 336, in __init__
    import torch
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/torch/__init__.py", line 187, in _load_global_deps
    raise err
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/users/xuguoyao/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen: cannot load any more object with static TLS

### Steps To Reproduce

git clone 后直接运行cli_demo.py或web_demo.py

### Environment

```markdown
- OS: Red Hat 4.8.5-44
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False
- GCC: 4.8.5
```

### Anything else?

不知道这是不是和GCC版本有关，不知道有没有测过最低支持的gcc版本呢

**Comment by yanyuechuixue** [comment]
遇到了同样的问题，环境为 linux （conda + python 3.10.9）.
测试了 import torch 没有任何报错：
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False

**Comment by yanyuechuixue** [comment]
> 应该是你的环境中 torch 安装的问题，跟本仓库无关。你可以试一下执行 `import torch`，应该也是这个报错。


遇到了同样的问题，环境为 linux （conda + python 3.10.9）.
测试了 import torch 没有任何报错：

- CUDA Support (python -c "import torch; print(torch.cuda.is_available())") :False
