### ISSUE TITLE
使用cpu时报错

### ISSUE THREAD

**Issue by ColorfulDick** [THUDM/ChatGLM-6B#57]
问题描述：在gpu上运行是成功的，将 model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().quantize(4).cuda() 这行换成  model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float() 后，执行推理时报错

报错信息：Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "/home/zhongtong/.local/lib/python3.9/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/zhongtong/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data/zhongtong/chatglm/ChatGLM-6B/web_demo.py", line 14, in predict
    response, history = model.chat(tokenizer, input, history)
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1093, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1117, in generate
    output_ids = super().generate(**kwargs)
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhongtong/.local/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/transformers/generation/utils.py", line 2443, in sample
    outputs = self(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1018, in forward
    transformer_outputs = self.transformer(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 863, in forward
    layer_ret = layer(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 562, in forward
    attention_outputs = self.attention(
  File "/home/zhongtong/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 416, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/home/zhongtong/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 282, in attention_fn
    context_layer = torch.bmm(attention_probs, value_layer.transpose(0, 1))
RuntimeError: expected scalar type Float but found Half

**Comment by duzx16** [comment]
Are you using the latest model implementation from [Hugging Face Hub](https://huggingface.co/THUDM/chatglm-6b)? We already fixed the problem.

**Comment by ColorfulDick** [comment]
> Are you using the latest model implementation from [Hugging Face Hub](https://huggingface.co/THUDM/chatglm-6b)? We already fixed the problem.
Thanks you for reply，i try to use new model that upload today

**Comment by XuesenYang** [comment]
.half()改成 .float()
