### ISSUE TITLE
[Help] numpy 版本不匹配 求问这个项目中numpy的版本

### ISSUE THREAD

**Issue by liketocood345** [THUDM/ChatGLM-6B#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(pytorch) D:\ChatGLM>web_demo.py
Traceback (most recent call last):
  File "D:\ChatGLM\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "D:\ChatGLM\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "D:\ChatGLM\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ChatGLM\web_demo.py", line 1, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "D:\ChatGLM\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\ChatGLM\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\ChatGLM\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "D:\ChatGLM\transformers\utils\generic.py", line 27, in <module>
    import numpy as np
  File "D:\ChatGLM\numpy\__init__.py", line 141, in <module>
    from . import core
  File "D:\ChatGLM\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "D:\deeplearning\python.exe"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

### Steps To Reproduce

pytorch学习入门的无知脑瓜+项目散在c盘d盘

### Environment

```markdown
- OS:win10
- Python:3.8.16
- Transformers:4.27.1
- PyTorch:
- CUDA Support non（因为是amd的GPU所以选择CPU计算）
```

**Comment by duzx16** [comment]
跟这个项目没关系。是你 numpy 安装有问题，连 `import numpy` 都会报错。可以根据它给的网址 https://numpy.org/devdocs/user/troubleshooting-importerror.html 检查一下，或者用搜索引擎搜索一下报错
