### ISSUE TITLE
[BUG/Help] <UnboundLocalError: local variable 'context_length' referenced before assignment>

### ISSUE THREAD

**Issue by heccxixi** [THUDM/ChatGLM-6B#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用lora对模型进行训练会出现

### Steps To Reproduce

 

trainer = transformers.Trainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=eval_data,

        args=transformers.TrainingArguments(
            per_device_train_batch_size=micro_batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            warmup_steps=100,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            fp16=True,
            logging_steps=10,
            optim="adamw_torch",
            evaluation_strategy="steps",
            save_strategy="steps",
            eval_steps=200,
            save_steps=200,
            output_dir=output_dir,
            save_total_limit=3,
            load_best_model_at_end=True,
            ddp_find_unused_parameters=False if ddp else None,
            group_by_length=group_by_length,
            report_to="wandb" if use_wandb else None,
            run_name=wandb_run_name if use_wandb else None,
        ),
        data_collator=transformers.DataCollatorForTokenClassification(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        ),
    )
    model.config.use_cache = False

### Environment

```markdown
- OS:linux
- Python:3.10.9
- Transformers:4.28.0.dev0
- PyTorch:2.0.0
- CUDA Support
```

**Comment by duzx16** [comment]
你能提供一下完整的报错信息吗？具体是在代码的哪一行报错的

**Comment by heccxixi** [comment]
Traceback (most recent call last):
  File "/home/hexinyu/pytorch/action_item2.py", line 344, in <module>
    fire.Fire(train)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hexinyu/pytorch/action_item2.py", line 326, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1899, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/data/data_collator.py", line 310, in torch_call
    batch = self.tokenizer.pad(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3022, in pad
    outputs = self._pad(
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/tokenization_chatglm.py", line 409, in _pad
    position_ids[context_length:] = mask_position
UnboundLocalError: local variable 'context_length' referenced before assignment

**Comment by duzx16** [comment]
> Traceback (most recent call last): File "/home/hexinyu/pytorch/action_item2.py", line 344, in fire.Fire(train) File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 141, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire component, remaining_args = _CallAndUpdateTrace( File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "/home/hexinyu/pytorch/action_item2.py", line 326, in train trainer.train(resume_from_checkpoint=resume_from_checkpoint) File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train return inner_training_loop( File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1899, in _inner_training_loop for step, inputs in enumerate(epoch_iterator): File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in **next** data = self._next_data() File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch return self.collate_fn(data) File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/data/data_collator.py", line 45, in **call** return self.torch_call(features) File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/data/data_collator.py", line 310, in torch_call batch = self.tokenizer.pad( File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3022, in pad outputs = self._pad( File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/tokenization_chatglm.py", line 409, in _pad position_ids[context_length:] = mask_position UnboundLocalError: local variable 'context_length' referenced before assignment

已经修复了。不过注意非官方实现的微调不保证正确性。

**Comment by heccxixi** [comment]
好的感谢
