### ISSUE TITLE
[BUG/Help] api.py reports ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by ivanshipanda** [THUDM/ChatGLM-6B#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████| 8/8 [00:04<00:00,  1.70it/s]
INFO:     Started server process [15728]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     180.162.85.95:0 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\code\PycharmProjects\ChatGLM-6B\api.py", line 24, in create_item
    json_post_raw = await request.json()
  File "D:\code\PycharmProjects\chatgpt\venv\lib\site-packages\starlette\requests.py", line 244, in json
    self._json = json.loads(body)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0

### Steps To Reproduce

run 'python api.py'

### Environment

```markdown
- OS: win11
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
应该是你 post 请求的格式有问题？

**Comment by ivanshipanda** [comment]
@duzx16 对的。修好了谢谢，就是请求格式有问题。
api调用需要使用Transformers: 4.27.1，然后把模型路径改成绝对路径。

**Comment by Halflifefa** [comment]
真是transformers版本的问题,我从4.26.1升级到4.28.1就解决了,感谢
