### ISSUE TITLE
How to fix error like this: torch.cuda.OutOfMemoryError: CUDA out of memory ?

### ISSUE THREAD

**Issue by zhangchunlin** [THUDM/ChatGLM-6B#63]
OS: ubuntu 20.04
The error message said we need to change value of max_split_size_mb, but I search source code and cannot find any file contains max_split_size_mb, would you please provide some guidance about how to fix?
```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:16<00:00,  2.09s/it]
Traceback (most recent call last):
  File "/home/zhangclb/sandbox/ai_llm/ChatGLM-6B/cli_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/zhangclb/.local/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 1.83 GiB total capacity; 1.27 GiB already allocated; 57.19 MiB free; 1.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by skirodev** [comment]
At least 6GB of VRAM is required, or you can try modifying the code to use CPU inference.
```
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
```
