### ISSUE TITLE
RuntimeError: Unknown platform: darwin

### ISSUE THREAD

**Issue by yangboz** [THUDM/ChatGLM-6B#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/Users/yangboz/test_thudm_chatglm.py", line 3, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 299, in get_cached_module_file
    get_cached_module_file(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    importlib.import_module(imp)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

### Expected Behavior

make it works.

### Steps To Reproduce

ref :https://huggingface.co/THUDM/chatglm-6b

### Environment

```markdown
- OS: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
- Python: 3.9
- Transformers: 4.27.1
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

### Anything else?

any plan to support MPS?

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM-6B#mac-%E4%B8%8A%E7%9A%84-gpu-%E5%8A%A0%E9%80%9F
已经支持了，但是因为 `transformers` 的原因，需要从本地加载模型
