### ISSUE TITLE
报错 RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

### ISSUE THREAD

**Issue by gg22mm** [THUDM/ChatGLM-6B#649]
把代码放到文件中运行不成功！

1、运行：
   export CUDA_VISIBLE_DEVICES=0,1 && python desc_wll.py  

2、后报错：
     RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

desc_wll.py  内容如下：

// 多卡部署
from utils import load_model_on_gpus
from transformers import AutoTokenizer
import os
os.environ['CUDA_VISIBLE_DEVICES'] ='0,1'

model = load_model_on_gpus("./THUDM/chatglm-6b", num_gpus=2)

//解析
model = model.eval()
tokenizer = AutoTokenizer.from_pretrained("./THUDM/chatglm-6b", trust_remote_code=True)
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

运行：export CUDA_VISIBLE_DEVICES=0,1 && python desc_wll.py  后报错：RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

----------详细报错信息如下----------------

(mygpt) [root@localhost chatGlmBase]# python desc_wll.py 
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:53<00:00,  6.68s/it]
/home/data/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484657607/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "desc_wll.py", line 7, in <module>
    model = load_model_on_gpus("./THUDM/chatglm-6b", num_gpus=2)
  File "/home/data/pytoch/chatGlmBase/utils.py", line 51, in load_model_on_gpus
    model = load_checkpoint_and_dispatch(
  File "/home/data/miniconda3/envs/mygpt/lib/python3.8/site-packages/accelerate/big_modeling.py", line 479, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/home/data/miniconda3/envs/mygpt/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 946, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "/home/data/miniconda3/envs/mygpt/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
  File "/home/data/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

### Environment

```markdown
(mygpt) [root@localhost chatGlmBase]# python
	Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
	[GCC 11.2.0] :: Anaconda, Inc. on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import torch as t
	>>> print( t.cuda.is_available() )
	True
	>>> tensor=t.Tensor(3,4)
	>>> tensor.cuda(0)
	tensor([[0., 0., 0., 0.],
			[0., 0., 0., 0.],
			[0., 0., 0., 0.]], device='cuda:0')
	>>> print(t.version.cuda)
	10.2
	>>> print(t.cuda.device_count())
	2
```

**Comment by gg22mm** [comment]
不知道为什么有时候返回的确是false如：

 >>> print( t.cuda.is_available() )
False 

再运行几次都是True了.   好不奇怪
