### ISSUE TITLE
[BUG/Help] <RuntimeError: The expanded size of the tensor (88) must match the existing size (87) at non-singleton dimension 3.  Target sizes: [32, 32, 88, 88].  Tensor sizes: [32, 1, 87, 87]>

### ISSUE THREAD

**Issue by heccxixi** [THUDM/ChatGLM-6B#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/home/hexinyu/pytorch/action_item2.py", line 345, in <module>
    fire.Fire(train)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hexinyu/pytorch/action_item2.py", line 327, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 2699, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 2731, in compute_loss
    outputs = model(**inputs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/peft/peft_model.py", line 530, in forward
    return self.base_model(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 1191, in forward
    transformer_outputs = self.transformer(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 986, in forward
    layer_ret = torch.utils.checkpoint.checkpoint(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hexinyu/miniconda3/envs/nlp/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 474, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/home/hexinyu/.cache/huggingface/modules/transformers_modules/thu_chatglm/modeling_chatglm.py", line 306, in attention_fn
    attention_scores.masked_fill_(attention_mask, -10000.0)
RuntimeError: The expanded size of the tensor (88) must match the existing size (87) at non-singleton dimension 3.  Target sizes: [32, 32, 88, 88].  Tensor sizes: [32, 1, 87, 87]

### Steps To Reproduce

使用官方lora代码训练模型
已经不太知道是哪里的问题了。
更新了全部文件

### Environment

```markdown
- OS:linux
- Python:3.10.9
- Transformers:latest
- PyTorch:latest
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :support
```

**Comment by Zhang-l-i-n** [comment]
请问问题解决了吗？我也遇到了一样的问题

**Comment by heccxixi** [comment]
不算解决了，换了一个代码跑，你可以参考一下https://github.com/mymusise/ChatGLM-Tuning的代码，我用这个跑成功了
