### ISSUE TITLE
[BUG/Help] <title>AttributeError: module transformers has no attribute TFChatGLMForConditionalGeneration

### ISSUE THREAD

**Issue by lelechallc** [THUDM/ChatGLM-6B#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

更改web_demo.py为：
tokenizer = AutoTokenizer.from_pretrained("chatglm-6b_pre", trust_remote_code=True,from_tf=True)
model = AutoModel.from_pretrained("chatglm-6b_pre", trust_remote_code=True,from_tf=True).half().cuda()

运行web_demo.py时候出现Traceback (most recent call last):
  File "/home/jovyan/web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("chatglm-6b_pre", trust_remote_code=True,from_tf=True).half().cuda()
  File "/home/linluocheng086/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "/home/linluocheng086/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2612, in from_pretrained
    model, loading_info = load_tf2_checkpoint_in_pytorch_model(
  File "/home/linluocheng086/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/modeling_tf_pytorch_utils.py", line 407, in load_tf2_checkpoint_in_pytorch_model
    tf_model_class = getattr(transformers, tf_model_class_name)
  File "/home/linluocheng086/miniconda3/envs/chatglm/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1119, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute TFChatGLMForConditionalGeneration
的问题。如何解决？？

### Steps To Reproduce

无

### Environment

```markdown
- OS:linux
- Python:3.9.16
- Transformers:  4.27.1    
- PyTorch: 2.0.0  
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

no

**Comment by duzx16** [comment]
你确定 `chatglm-6b_pre` 里面的文件是完整的吗，对比 https://huggingface.co/THUDM/chatglm-6b
