### ISSUE TITLE
[BUG/Help] <title>web_demo运行时出现vocab_file找不到

### ISSUE THREAD

**Issue by DaBinGOGOGO** [THUDM/ChatGLM-6B#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("chatglm-6b", trust_remote_code=True)
  File "/home/hbb/venv_gpt/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 680, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/hbb/venv_gpt/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1813, in from_pretrained
    **kwargs,
  File "/home/hbb/venv_gpt/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1961, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 209, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 55, in __init__
    assert vocab_file is not None
AssertionError

### Steps To Reproduce

运行web_demo.py

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.7
- Transformers:4.27.1
- PyTorch:1.10
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :10.2
```

**Comment by duzx16** [comment]
你检查一下 `chatglm-6b` 文件夹下面是否有 `ice_text.model` 文件，以及 sha256值是否和 https://huggingface.co/THUDM/chatglm-6b/blob/main/ice_text.model 一致

**Comment by DaBinGOGOGO** [comment]
感谢，确实是少文件了
