### ISSUE TITLE
[BUG/Help] <arm cpu 报错 RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)>

### ISSUE THREAD

**Issue by dongdongqiang2018** [THUDM/ChatGLM-6B#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`root@bms-5e55:/home/dg/cpu_test/ChatGLM-6B# python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.94s/it]
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好
Traceback (most recent call last):
  File "cli_demo.py", line 57, in <module>
    main()
  File "cli_demo.py", line 42, in main
    for response, history in model.stream_chat(tokenizer, query, history=history):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/35ca52301fbedee885b0838da5d15b7b47faa37c/modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/35ca52301fbedee885b0838da5d15b7b47faa37c/modeling_chatglm.py", line 1404, in stream_generate
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)
`

### Steps To Reproduce

在以下环境执行cpu 运行的时候报错
- OS:ubuntu 18.04
- Python: 3.7.5
- Transformers:Transformers
- PyTorch:1.11
- CPU：aarch64

修改 model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()之后
执行 python cli_demo.py

报错如下
`root@bms-5e55:/home/dg/cpu_test/ChatGLM-6B# python cli_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.94s/it]
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好
Traceback (most recent call last):
  File "cli_demo.py", line 57, in <module>
    main()
  File "cli_demo.py", line 42, in main
    for response, history in model.stream_chat(tokenizer, query, history=history):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/35ca52301fbedee885b0838da5d15b7b47faa37c/modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/35ca52301fbedee885b0838da5d15b7b47faa37c/modeling_chatglm.py", line 1404, in stream_generate
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)`

### Environment

```markdown
- OS:ubuntu 18.04
- Python: 3.7.5
- Transformers:Transformers
- PyTorch:1.11
- CPU：aarch64
# - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
没用过 arm cpu。报错的这一行的前一句是 `probs = nn.functional.softmax(next_token_scores, dim=-1)`，过了 `softmax` 按理说是不可能出现probs 小于0的情况。可能是 arm 下的  pytorch 有 bug，可以更新一下 pytorch 版本试试。
