### ISSUE TITLE
[BUG/Help] <title> 每个batch的长度不一致

### ISSUE THREAD

**Issue by luolanfeixue** [THUDM/ChatGLM-6B#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

evaluate的时候，报这个错

在preprocess_function_eval中打印了input长度，发现每个batch长度不一致。

### Steps To Reproduce

Traceback (most recent call last):
  File "main.py", line 446, in <module>
    main()
  File "main.py", line 411, in main
    predict_results = trainer.predict(predict_dataset, metric_key_prefix="predict", max_length=1024, do_sample=True, top_p=0.7, temperature=0.95)
  File "/root/chatbeta/code/ptuning/trainer_seq2seq.py", line 136, in predict
    return super().predict(test_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/root/chatbeta/code/ptuning/trainer.py", line 3013, in predict
    output = eval_loop(
  File "/root/chatbeta/code/ptuning/trainer.py", line 3108, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/data/data_collator.py", line 586, in __call__
    features = self.tokenizer.pad(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3027, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 210, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 733, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
  8%|█████████████████▉

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

解决方法： 我将

    data_collator = DataCollatorForSeq2Seq(
        tokenizer,
        model=model,
        label_pad_token_id=label_pad_token_id,
        pad_to_multiple_of=None,
        padding=False
    )
改为

    data_collator = DataCollatorForSeq2Seq(
        tokenizer,
        model=model,
        label_pad_token_id=label_pad_token_id,
        pad_to_multiple_of=None,
        padding=True
    )

已经解决了问题，但是这个问题的原因是什么？

**Comment by duzx16** [comment]
`preprocess_function_eval` 这个函数在调用 tokenizer 的时候已经设置了 `padding=True`，返回的输入已经是定长的了。目前还没有其他人反映过这个问题

**Comment by luolanfeixue** [comment]
> `preprocess_function_eval` 这个函数在调用 tokenizer 的时候已经设置了 `padding=True`，返回的输入已经是定长的了。目前还没有其他人反映过这个问题



找到根本原因了，是因为我数据里target中存在null。

**Comment by T-Atlas** [comment]
> > `preprocess_function_eval` 这个函数在调用 tokenizer 的时候已经设置了 `padding=True`，返回的输入已经是定长的了。目前还没有其他人反映过这个问题
> 
> 找到根本原因了，是因为我数据里target中存在null。

我也有一样的问题，我也检查一下训练数据，能否使用某些方法跳过null的数据
