### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE, anybody knows why ?

### ISSUE THREAD

**Issue by zhangfaen** [THUDM/ChatGLM-6B#73]
My environment:
Python 3.10
torch.__version__: 1.13.1+cu117
GPU: V100

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 8/8 [00:07<00:00,  1.02it/s]
欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好
Traceback (most recent call last):
  File "/home/zfe/dev/ChatGLM-6B/cli_demo.py", line 24, in <module>
    response, history = model.chat(tokenizer, query, history=history)
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 1109, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 1133, in generate
    output_ids = super().generate(**kwargs)
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2443, in sample
    outputs = self(
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 1029, in forward
    transformer_outputs = self.transformer(
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 874, in forward
    layer_ret = layer(
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 573, in forward
    attention_outputs = self.attention(
  File "/home/zfe/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 427, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/home/zfe/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/0101afdfa7f279e082623ee57d7ad6f84e1e82dc/modeling_chatglm.py", line 250, in attention_fn
    matmul_result = torch.baddbmm(
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by zhangfaen** [comment]
Fixed

Reason: torch.version: 1.13.1+cu117  is not compatible with system CUDA version.
How to fix: 
1. pip uninstall torch torchvision
2. pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
