### ISSUE TITLE
[BUG/Help] 运行train.sh时，报错提示touch版本，但实际版本是够的

### ISSUE THREAD

**Issue by gaofeiseu** [THUDM/ChatGLM-6B#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ptuning，bash train.sh ，直接就报错了：
Traceback (most recent call last):
  File "/home/user/data/ChatGLM-6B/ChatGLM-6B/ptuning/main.py", line 44, in <module>
    from trainer_seq2seq import Seq2SeqTrainer
  File "/home/user/data/ChatGLM-6B/ChatGLM-6B/ptuning/trainer_seq2seq.py", line 22, in <module>
    from trainer import Trainer
  File "/home/user/data/ChatGLM-6B/ChatGLM-6B/ptuning/trainer.py", line 77, in <module>
    from transformers.pytorch_utils import ALL_LAYERNORM_LAYERS, is_torch_greater_or_equal_than_1_10, is_torch_less_than_1_11
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_10' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)

### Steps To Reproduce

见Current Behavior

### Environment

```markdown
- OS:
- Python:Python 3.10.6
- Transformers:
- PyTorch:1.12.1+cu116
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by gaofeiseu** [comment]
补充下：Transformers的版本：4.21.3

**Comment by gaofeiseu** [comment]
可以了。。。。。。是我自己环境的问题，我重新安装了requirment.txt中的所有依赖， 就RUN起来了
