### ISSUE TITLE
chatGML-6B 启动api.py,调用问答接口报：ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by shihzenq** [THUDM/ChatGLM-6B#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/ChatGLM-6B/ChatGLM-6B/api.py", line 33, in create_item
    response, history = model.chat(tokenizer,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 1285, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/quantization.py", line 147, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/quantization.py", line 51, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "/home/gkd/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/quantization.py", line 94, in extract_weight_to_half
    assert False, "Unsupported bit-width"
AssertionError: Unsupported bit-width

### Steps To Reproduce

1、我根据官方文档，按步骤搭建
2、python3 api.py ：
 INFO:     Started server process [125612]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
3、请求接口：curl -X POST "http://127.0.0.1:8000"      -H 'Content-Type: application/json'      -d '{"prompt": "你好", "history": []}'
4、报错

### Environment

```markdown
- OS: Ubuntu 21.04
- Python:3.10.6
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by K-945** [comment]
我也是这个，显示500 Internal Server Error，请问最后解决了吗

**Comment by cnmaple** [comment]
问题是 transformers 的最新版本兼容问题，新版需要将 tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
 model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda() 中的路径THUDM/chatglm-6b修改为绝对路径。

English：
 
 The problem is the compatibility issue with the latest version of transformers. The new version requires modifying the path THUDM/chatglm-6b in tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) and model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda() to an absolute path.

**Comment by Typooner** [comment]
我也有这个问题，不过如果我的prompt是英文的话就不会报错，应该怎么修改才能兼容中文呢
