### ISSUE TITLE
[BUG/Help] <title>运行 python web_demo.py 时报错

### ISSUE THREAD

**Issue by tonglingwen** [THUDM/ChatGLM-6B#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "web_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 286, in get_cached_module_file
    commit_hash = model_info(pretrained_model_name_or_path, revision=revision, token=use_auth_token).sha
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1623, in model_info
    r = requests.get(path, headers=headers, timeout=timeout, params=params)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/nvidia/anaconda3/envs/yolo/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### Expected Behavior

none

### Steps To Reproduce

none

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

none

**Comment by MiXianif** [comment]
+1蹲个结果

**Comment by MiXianif** [comment]
路径问题：tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
路径加载出现错误导致

**Comment by muximuxi** [comment]
同样的错误，请问解决了吗？

**Comment by muximuxi** [comment]
> 同样的错误，请问解决了吗？

在web_demo.py中，加入time.sleep(0.01),就可以了

**Comment by pjj123456** [comment]
我也出现了这个问题有没有好的解决办法请问
