### ISSUE TITLE
[BUG/Help] <title>  ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by poo0054** [THUDM/ChatGLM-6B#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

从本地加载模型

model_path = "D:\project\gpt\chatglm-6b"

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
model = model.eval()

### Steps To Reproduce

Traceback (most recent call last):
  File "D:\project\gpt\chatglm-6b\cli_demo.py", line 11, in <module>
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "C:\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\poo00/.cache\huggingface\modules\transformers_modules\chatglm-6b\modeling_chatglm.py", line 28, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "C:\Python310\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Python310\lib\site-packages\accelerate\accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Python310\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Python310\lib\site-packages\accelerate\utils\__init__.py", line 145, in <module>
    from .torch_xla import install_xla
  File "C:\Python310\lib\site-packages\accelerate\utils\torch_xla.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

### Environment

```markdown
- OS: windows11
- Python: 3.10
- Transformers: 4.27.1
- PyTorch: 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : false
```

**Comment by poo0054** [comment]
python -m pip install --upgrade pip setuptools wheel即可解决问题
