### ISSUE TITLE
RuntimeError:  DefaultCPUAllocator: not enough memory: you tried to allocate 100663296 bytes.[BUG/Help] <title>

### ISSUE THREAD

**Issue by ccartermices** [THUDM/ChatGLM-6B#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to run chatGLM-6B-int4 on my machine but it had a bug.
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 100663296 bytes.

I change part of the code in web_demo.py:
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("E:\ChatGLM-6B-main\models\chatglm_int4", trust_remote_code=True).quantize(8).half().cuda()
model = model.eval()

### Steps To Reproduce

Run"python web_demo.py"

error:
(E:\minconda_extra_env_folder\ChatGLM6B) E:\ChatGLM-6B-main>python web_demo.py
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████| 446/446 [00:00<00:00, 112kB/s]
E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\cc\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)enization_chatglm.py: 100%|████████████████████████████████████████████████████| 16.7k/16.7k [00:00<00:00, 2.32MB/s]
Downloading ice_text.model: 100%|█████████████████████████████████████████████████████████████| 2.71M/2.71M [00:01<00:00, 1.79MB/s]
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "E:\ChatGLM-6B-main\web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("E:\ChatGLM-6B-main\models\chatglm_int4", trust_remote_code=True).quantize(8).half().cuda()
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 1047, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init)
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 844, in __init__
    [get_layer(layer_id) for layer_id in range(self.num_layers)]
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 844, in <listcomp>
    [get_layer(layer_id) for layer_id in range(self.num_layers)]
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 829, in get_layer
    return GLMBlock(
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 581, in __init__
    self.attention = SelfAttention(
  File "C:\Users\cc/.cache\huggingface\modules\transformers_modules\chatglm_int4\modeling_chatglm.py", line 388, in __init__
    self.query_key_value = init_method(
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "E:\minconda_extra_env_folder\ChatGLM6B\lib\site-packages\torch\_refs\__init__.py", line 4254, in empty_like
    return torch.empty_strided(
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 100663296 bytes.

### Environment

```markdown
- OS:win10(32GB memory + 1080ti GPU 11 GB)
- Python:3.9.0
- Transformers:4.27.1
- PyTorch:2
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :cu118
```

**Comment by duzx16** [comment]
内存不够了。可以检查一下计算机的空余内存，是否有别的程序在占用大量内存
