### ISSUE TITLE
[BUG/Help] 加载模型时遇到 RuntimeError: Library cuda is not initialized 问题

### ISSUE THREAD

**Issue by TJJ120635** [THUDM/ChatGLM-6B#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在参考官方 chatglm-6b-int4 样例提供的代码来进行测试

```python
# 测试 CUDA 可用性
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
from torch.backends import  cudnn
print(cudnn.is_available())

# 测试 GLM 模型
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("chatglm-6b-int4", trust_remote_code=True).half().cuda()
print("First:")
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
print("Second:")
response, history = model.chat(tokenizer, "请介绍一下你自己", history=history)
print(response)
```

使用 Yolov5 项目来跑目标检测，测试过 CUDA 正常可用
在 GLM 测试程序开头也添加了 CUDA 检测部分，输出正常
但是在实际运行模型的过程中，进行到 `response, history = model.chat(tokenizer, "你好", history=[])` 一句时，cpm_kernels 库提示了 RuntimeError: Library cuda is not initialized 问题

(查询过网上的相关问题，但是都找不到相同的情况，需要求助各位大佬)

![5](https://user-images.githubusercontent.com/43161566/234791432-0091e64d-a9c7-4015-b5b9-3d684871157d.png)

完整报错如下：
```shell
(chat) root@ubuntu-virtual-machine:/data1/chat_model# python test.py
2.0.0
11.7
True
True
----------------------------------------------
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 2
Parallel kernel is not recommended when parallel num < 4.
Using quantization cache
Applying quantization to glm layers
First:
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "/data1/chat_model/test.py", line 15, in <module>
    response, history = model.chat(tokenizer, "你好", history=[])
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py", line 1286, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py", line 1191, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py", line 997, in forward
    layer_ret = layer(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization.py", line 375, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization.py", line 53, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b-int4/quantization.py", line 274, in extract_weight_to_half
    func(
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 24, in get_module
    self._module[curr_device] = cuda.cuModuleLoadData(self._code)
  File "/root/anaconda3/envs/chat/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cuda is not initialized
```

### Steps To Reproduce

目录结构：
test.py (or cli_demo.py)
chatglm-6b-int4
---- 从 huggingface/THUDM/ChatGLM-6B-int4 克隆的完整项目与权重

测试语句：
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("chatglm-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("chatglm-6b-int4", trust_remote_code=True).half().cuda()
print("First:")
response, history = model.chat(tokenizer, "你好", history=[])

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- Python: 3.9
- Transformers: 4.27.1
- PyTorch: 2.0.0

- GPU: Nvidia Tesla P40
- Driver: 515.65.01
- CUDA: 11.7
- CuDNN: cudnn-linux-x86_64-8.9.0.131_cuda11
- CUDA Support: True
```

**Comment by TJJ120635** [comment]
查看代码，似乎是在 `envs/chat/lib/python3.9/site-packages/cpm_kernels/kernels/base.py` ：
调用了 self._module.get_module(), self._func_name
进一步调用了 self._module[curr_device] = cuda.cuModuleLoadData(self._code)
```python
# Line 29
class KernelFunction:
    def __init__(self, cmodule : LazyKernelCModule, func_name : str) -> None:
        self._module = cmodule
        self._funcs = {}
        self._func_name = func_name
    
    def _prepare_func(self):
        curr_device = cudart.cudaGetDevice()
        cudart.cudaSetDevice(curr_device)   # ensure cudart context
        if curr_device not in self._funcs:
            self._funcs[curr_device] = cuda.cuModuleGetFunction(
                # 这一句调用下面的 get_module
                self._module.get_module(), self._func_name
            )
        return self._funcs[curr_device]

# Line 24
class LazyKernelCModule:
    def __init__(self, code):
        self._code = code
        self._module = {}
    
    def get_module(self):
        curr_device = cudart.cudaGetDevice()
        if curr_device not in self._module:
            Device(curr_device).use()   # force initialize context
            # 这一步调用
            self._module[curr_device] = cuda.cuModuleLoadData(self._code)
        return self._module[curr_device]
```

从而使用了 `envs/chat/lib/python3.9/site-packages/cpm_kernels/library/cuda.py`：
在 cuMoudleLoadData 一步出现了问题

```python
# Line 230
@cuda.bind("cuModuleLoadData", [ctypes.POINTER(CUmodule), ctypes.c_void_p], CUresult)
def cuModuleLoadData(data : bytes) -> CUmodule:
    module = CUmodule()
    checkCUStatus(cuda.cuModuleLoadData(ctypes.byref(module), data))
    return module
```
但是由于涉及到了 C 和指针，我难以进行问题排查，需要求助

**Comment by TJJ120635** [comment]
经过检查是由于CUDA目录 `/usr/local/cuda/lib64` 中缺少 `libcuda.so` 文件
后续在 `/usr/lib/x86_64-linux-gnu` 找到 `libcuda.so.515.65.01*`
将文件复制到CUDA目录中，然后创建一个软连接 `libcuda.so -> libcuda.so.515.65.01*`
可以成功读取，解决问题

**Comment by fairylulu** [comment]
方法很有效～感谢～
