### ISSUE TITLE
piece id 超出范围错误

### ISSUE THREAD

**Issue by 503718696** [THUDM/ChatGLM-6B#84]
Traceback (most recent call last):
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/bing/文档/python-workspace/ChatGLM-6B-main-THUDM/web_demo.py", line 16, in predict
    response, history = model.chat(tokenizer, input, history)
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bing/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/c3dece3f011574955ccba53b9224ee9f78dfd54e/modeling_chatglm.py", line 1111, in chat
    response = tokenizer.decode(outputs)
  File "/home/bing/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/c3dece3f011574955ccba53b9224ee9f78dfd54e/tokenization_chatglm.py", line 276, in decode
    return self.sp_tokenizer.decode(token_ids)
  File "/home/bing/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/c3dece3f011574955ccba53b9224ee9f78dfd54e/tokenization_chatglm.py", line 133, in decode
    text = self._get_text_tokenizer(encode_special_tokens=special_tokens).decode(ids)
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/icetk/text_tokenizer.py", line 46, in decode
    return self.sp.DecodeIds(ids)
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/home/bing/anaconda3/envs/PT2_Env/lib/python3.10/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.

这段错误信息看起来像是在进行自然语言处理任务时发生了错误。具体地，这个错误是由于调用了一个无效的编码 ID 导致的。

**Comment by ASIT-KuHaku** [comment]
同样的错误，在双方对话文本共1694字符后出现。

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1059, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 868, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/kuhaku/桌面/ChatGLM-webui/./webui.py", line 47, in predict
    output, history = model.chat(
  File "/home/kuhaku/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kuhaku/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 1097, in chat
    response = tokenizer.decode(outputs)
  File "/home/kuhaku/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 276, in decode
    return self.sp_tokenizer.decode(token_ids)
  File "/home/kuhaku/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 133, in decode
    text = self._get_text_tokenizer(encode_special_tokens=special_tokens).decode(ids)
  File "/home/kuhaku/.local/lib/python3.10/site-packages/icetk/text_tokenizer.py", line 46, in decode
    return self.sp.DecodeIds(ids)
  File "/home/kuhaku/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/home/kuhaku/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/home/kuhaku/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.

**Comment by shangzhensen** [comment]
+1

**Comment by zy86603465** [comment]
+1
