### ISSUE TITLE
[BUG/Help] RuntimeError: Library cublasLt is not initialized

### ISSUE THREAD

**Issue by liuxiaocs7** [THUDM/ChatGLM-6B#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, everyone, I have met same quesiton like the closed issue: #76 , and rebooting not work for me.

```
(lx_chatglm) han@han-PC:~/lx/ChatGLM-6B$ python web_demo.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????| 8/8 [00:54<00:00,  6.79s/it]
Running on local URL:  http://0.0.0.0:7860
Running on public URL: https://5faa63bcceeac54349.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/gradio/blocks.py", line 1059, in process_api
    result = await self.call_function(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/gradio/blocks.py", line 868, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/han/lx/ChatGLM-6B/web_demo.py", line 15, in predict
    response, history = model.chat(tokenizer, input, history)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1095, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1119, in generate
    output_ids = super().generate(**kwargs)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2443, in sample
    outputs = self(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1018, in forward
    transformer_outputs = self.transformer(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 863, in forward
    layer_ret = layer(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 562, in forward
    attention_outputs = self.attention(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 387, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 137, in forward
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 21, in forward
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "/home/han/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 97, in extract_weight_to_half
    func(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/device/__init__.py", line 152, in use
    self._device.use()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/device/__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized
```

But web_demo can use:

![image](https://user-images.githubusercontent.com/42756849/225505346-09013f54-e555-4285-970a-d5e4d7558cb1.png)

```shell
han@han-PC:~$ nvidia-smi
Thu Mar 16 11:11:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:2D:00.0 Off |                  N/A |
| 44%   47C    P8    11W / 320W |   8633MiB / 10014MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2712      G   /usr/lib/xorg/Xorg                100MiB |
|    0   N/A  N/A      8625      G   /usr/bin/uengine                  151MiB |
|    0   N/A  N/A      9160      G   kwin_x11                           44MiB |
|    0   N/A  N/A    368133      C   python                           8331MiB |
+-----------------------------------------------------------------------------+
```

### Expected Behavior

No Runtime Error.

### Steps To Reproduce

1. modify the model path and add `quantize(8)`

```python
tokenizer = AutoTokenizer.from_pretrained("./chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("./chatglm-6b", trust_remote_code=True).half().quantize(8).cuda()
```

2. run `python web_demo.py`

### Environment

```markdown
- OS: Deepin 20.4
- Python: 3.9.12
- Transformers: 4.26.1
- PyTorch: 1.13.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
这个提示一般是显存超了，可以考虑用4bit量化，或者对话论数不要太长

**Comment by liuxiaocs7** [comment]
> 这个提示一般是显存超了，可以考虑用4bit量化，或者对话论数不要太长

好的，谢谢，换显卡之后跑没有问题

**Comment by MonkeyTB** [comment]
我24G的显存，仍会报这个错误

**Comment by YCG09** [comment]
@MonkeyTB 后来解决了吗？

**Comment by YefZhao** [comment]
> RuntimeError: Library cublasLt is not initialized josStorer/selfhostedAI#2

我的也是24G显存，用4 bit 微调，还是报这个错

**Comment by lulianLiu** [comment]
> > RuntimeError: Library cublasLt is not initialized [josStorer/selfhostedAI#2](https://github.com/josStorer/selfhostedAI/issues/2)
> 
> 我的也是24G显存，用4 bit 微调，还是报这个错

你解决了吗？我也是这个问题

**Comment by hechuanlong** [comment]
4bit量化我试过了，也是不行。后来改了一下代码发现可以，可以试试看： https://github.com/THUDM/ChatGLM-6B/issues/347

**Comment by YXHXianYu** [comment]
> 4bit量化我试过了，也是不行。后来改了一下代码发现可以，可以试试看： #347

这个方法成功了！感谢捏（Win11 + RTX3060 12G + 16G内存）

**Comment by lmengi** [comment]
我是win11 _RTX3070TX 8G + 16 G内存，要怎么调整。我试了一下调整model = AutoModel.from_pretrained("chatglm-6b", load_in_8bit=True, trust_remote_code=True,device_map="auto")好像不行

**Comment by zhguliangsheng** [comment]
可以看一下是否缺少cudatoolkit包，我这安装cudatoolkit后解决了该问题

**Comment by kanseaveg** [comment]
遇到了一样的问题，环境直接进行推理没问题，但是运行ptuning的时候报错，ptuning的参数为：
```
#!/bin/bash

PRE_SEQ_LEN=128
LR=2e-2

CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/dev.json \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm-6b \
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4
```

报错信息为：
```
Quantized to 4 bit
Traceback (most recent call last):
  File "main.py", line 430, in <module>
    main()
  File "main.py", line 128, in main
    model = model.quantize(model_args.quantization_bit)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 1434, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/quantization.py", line 166, in quantize
    empty_init=empty_init
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/quantization.py", line 83, in compress_int4_weight
    [ctypes.c_void_p(weight.data_ptr()), ctypes.c_void_p(out.data_ptr()), ctypes.c_int32(n), ctypes.c_int32(m)],
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/kernels/base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/kernels/base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/device/__init__.py", line 152, in use
    self._device.use()
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/device/__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized
```

使用watch查看显存发现并没有超过，显存用量约合526MiB
![image](https://github.com/THUDM/ChatGLM-6B/assets/80022154/3483c7cb-cff4-49c2-9a54-1fc543763893)

**Comment by Ikaros-521** [comment]
装了MinGW，配了gcc的环境，终于跑起来 int4了。。。难绷

**Comment by antibits** [comment]
把训练启动参数里面的  --quantization_bit 4去掉就好了。默认是half()半精度量化，

**Comment by anhaoyang** [comment]
我是安装cuda，配了gcc环境，跑起来了https://zhuanlan.zhihu.com/p/620388694

**Comment by Eyesfront-ZJG** [comment]
env CUDA_PATH=/usr/local/cuda-xxx

**Comment by panpan0000** [comment]
problem solved by install cuda-toolkit

(1)check if you have it installed cuda-toolkit

`apt list |grep cuda|grep toolkit`

my machine `apt list` have only below items:
```
cuda-toolkit-11-7-config-common/now 11.7.99-1 all [installed,local]
cuda-toolkit-11-config-common/now 11.8.89-1 all [installed,local]
cuda-toolkit-config-common/now 12.0.107-1 all [installed,local]
```
and the `env` doesn't have any `cuda` param.

(2) install it:

take my Ubuntu as an example:
```
apt install nvidia-cuda-toolkit
```

them your `env` will show up with `cuda` things.

then run `python train.py` again. the issue is gone.

**Comment by liudaoguang** [comment]
ChatGLM2-6B/ptuning/main.py
127     if model_args.pre_seq_len is not None:
128         # P-tuning v2
129         model = model.half()  ===>model = model.half().cuda()    
GPU微调训练：尝试在后面加.cuda()，半精度half是依赖cuda写的需要调用cuda函数；（ubuntu亲测有效）
CPU微调训练：model = model.float() （个人仅在macOS m1上跑通）
130         model.transformer.prefix_encoder.float()
