### ISSUE TITLE
[BUG/Help] 多卡推理stream_chat 会报错

### ISSUE THREAD

**Issue by Qingluan** [THUDM/ChatGLM-6B#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[error] : Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)
connection handler failed
Traceback (most recent call last):
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/chatglm_src/llm.py", line 436, in echo
    raise e
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/chatglm_src/llm.py", line 423, in echo
    await oneChat(**json.loads(message))
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/chatglm_src/llm.py", line 384, in __call__
    for response, history in llm.model.stream_chat(llm.tokenizer, prompt, llm.history, max_length=llm.max_token, top_p=llm.top_p,
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm/modeling_chatglm.py", line 624, in forward
    attention_input = self.input_layernorm(hidden_states)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/root/miniconda3/envs/ai/lib/python3.9/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

### Expected Behavior

 在多卡推理的条件下 怎么解决 这个报错

### Steps To Reproduce

> 我使用的 model.stream_chat ,在单卡下不会报错

1. 当我设置 'device_map='auto'' 会爆以上错误
2. 使用READme的 load_model_on_gpus(mo.model_path, num_gpus=torch.cuda.device_count()) 同样会出现这样的错误

### Environment

```markdown
- OS:ubuntu 22.04
- Python:python 3.9
- Transformers: 4.28.1
- PyTorch: 2.0.0   
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by 204313508** [comment]
同问，也遇到一样的问题

**Comment by realhsq** [comment]
请问解决了吗

**Comment by Qingluan** [comment]
发现只要half().float()一次就行。

**Comment by realhsq** [comment]
> 

哦是的，感谢

**Comment by CrazyBrick** [comment]
> 发现只要half().float()一次就行。

hi，可以详细说一下吗
