### ISSUE TITLE
[BUG/Help] finetuning遇到问题

### ISSUE THREAD

**Issue by wzhiqing** [THUDM/ChatGLM-6B#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/data/__init__.py", line 27, in <module>
    from .processors import (
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/data/processors/__init__.py", line 16, in <module>
    from .squad import SquadExample, SquadFeatures, SquadV1Processor, SquadV2Processor, squad_convert_examples_to_features
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/data/processors/squad.py", line 35, in <module>
    from torch.utils.data import TensorDataset
ImportError: cannot import name 'TensorDataset' from 'jtorch.utils.data' (/root/miniconda3/lib/python3.7/site-packages/jtorch/utils/data.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/utils/import_utils.py", line 1131, in _get_module
    ) from e
RuntimeError: Failed to import transformers.data.data_collator because of the following error (look up to see its traceback):
cannot import name 'TensorDataset' from 'jtorch.utils.data' (/root/miniconda3/lib/python3.7/site-packages/jtorch/utils/data.py)

finetuning遇到这个问题，该怎么解决？

### Expected Behavior

cannot import name 'TensorDataset' from 'jtorch.utils.data' (/root/miniconda3/lib/python3.7/site-packages/jtorch/utils/data.py)

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS:
- Python:3.7
- Transformers:4.27.1
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

无

**Comment by duzx16** [comment]
安装原版的 PyTorch，不要安装 JTorch

**Comment by wzhiqing** [comment]
嗯 将python版本换成3.8后这个问题解决了
