### ISSUE TITLE
[BUG/Help] Unknown symbol found

### ISSUE THREAD

**Issue by liuxiaocs7** [THUDM/ChatGLM-6B#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when input is:

```
小明走完一段长1公里的路，花了10分钟，请问小明的平均速度是多少？
```

sometimes may be wrong in backend.

```shell
This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/_mathtext.py", line 2237, in parse
    result = self._expression.parseString(s)
  File "/usr/local/lib/python3.8/dist-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseFatalException: Unknown symbol: \text, found '\'  (at char 2), (line:1, col:3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1062, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 987, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 402, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 5453, in postprocess
    return self.md.render(unindented_y)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/renderer.py", line 87, in render
    result += self.renderInline(token.children, options, env)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/renderer.py", line 108, in renderInline
    result += self.rules[token.type](tokens, i, options, env)
  File "/usr/local/lib/python3.8/dist-packages/mdit_py_plugins/dollarmath/index.py", line 70, in render_math_inline
    content = _renderer(str(tokens[idx].content).strip(), {"display_mode": False})
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 980, in tex2svg
    fig.savefig(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2295, in print_figure
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2837, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/text.py", line 685, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/text.py", line 317, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_svg.py", line 1276, in get_text_width_height_descent
    return self._text2path.get_text_width_height_descent(s, prop, ismath)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/textpath.py", line 61, in get_text_width_height_descent
    self.mathtext_parser.parse(s, 72, prop)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/mathtext.py", line 435, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/mathtext.py", line 456, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/_mathtext.py", line 2239, in parse
    raise ValueError("\n".join(["",
ValueError: 
10\text{分钟} = 10\text{秒} \times 60\text{秒/分钟} = 600\text{秒}
  ^
Unknown symbol: \text, found '\'  (at char 2), (line:1, col:3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/_mathtext.py", line 2237, in parse
    result = self._expression.parseString(s)
  File "/usr/local/lib/python3.8/dist-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseFatalException: Unknown symbol: \text, found '\'  (at char 2), (line:1, col:3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1062, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 987, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 402, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 5453, in postprocess
    return self.md.render(unindented_y)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/renderer.py", line 87, in render
    result += self.renderInline(token.children, options, env)
  File "/usr/local/lib/python3.8/dist-packages/markdown_it/renderer.py", line 108, in renderInline
    result += self.rules[token.type](tokens, i, options, env)
  File "/usr/local/lib/python3.8/dist-packages/mdit_py_plugins/dollarmath/index.py", line 70, in render_math_inline
    content = _renderer(str(tokens[idx].content).strip(), {"display_mode": False})
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 980, in tex2svg
    fig.savefig(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2295, in print_figure
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2837, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/text.py", line 685, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/text.py", line 317, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_svg.py", line 1276, in get_text_width_height_descent
    return self._text2path.get_text_width_height_descent(s, prop, ismath)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/textpath.py", line 61, in get_text_width_height_descent
    self.mathtext_parser.parse(s, 72, prop)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/mathtext.py", line 435, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/mathtext.py", line 456, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/_mathtext.py", line 2239, in parse
    raise ValueError("\n".join(["",
ValueError: 
10\text{分钟} = 10\text{秒} \times 60\text{秒/分钟} = 600\text{秒}
  ^
Unknown symbol: \text, found '\'  (at char 2), (line:1, col:3)
```

### Steps To Reproduce

No.

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
I think this is a bug in gradio.
