### ISSUE TITLE
[BUG/Help] 已经下载huggingface文件到本地，并更换目录，但报需下载到本地的错

### ISSUE THREAD

**Issue by BEILOP** [THUDM/ChatGLM-6B#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
tokenizer = AutoTokenizer.from_pretrained("/home/jiaojiaxin/ChatGLM-6B/chatglm_6b_int4")
model = AutoModel.from_pretrained("/home/jiaojiaxin/ChatGLM-6B/chatglm_6b_int4").half().cuda()
```
报错
```
Traceback (most recent call last):
  File "/home/jiaojiaxin/ChatGLM-6B/run.py", line 3, in <module>
    model = AutoModel.from_pretrained("/home/jiaojiaxin/ChatGLM-6B/chatglm_6b_int4").half().cuda()
  File "/home/anaconda3/envs/llm/lib/python3.8/site-packages/transformers-4.29.0.dev0-py3.8.egg/transformers/models/auto/auto_factory.py", line 445, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/anaconda3/envs/llm/lib/python3.8/site-packages/transformers-4.29.0.dev0-py3.8.egg/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    raise ValueError(
ValueError: Loading /home/jiaojiaxin/ChatGLM-6B/chatglm_6b_int4 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

### Steps To Reproduce

.

### Environment

```markdown
都是官方指定的版本
```

**Comment by blue-q** [comment]
设置trust_remote_code=True就可以
